<table cellspacing="5" cellpadding="5" border="0px" style="margin-bottom:10px" id="IdTableMain" width="100%">
	<thead>
        <tr id="headerRow">
            <th width="5%"></th>
			<th width="20px"></th>
			<th id="dialogMaalNavn" style="width: 95%;" align="right"></th>
        </tr>
    </thead>
	<tbody>
	  <tr>
	    <td>1</td><td><span class="tdbg" style="width: 20px;"><input type="checkbox" name="ckhId1" id="Table1" value="1" disabled="disabled" checked="checked" class="forceCheck css-checkbox"/><label for="Table1"  class="css-label"></label></span></td><td>Formalities<!--Formalities--></td>
	  </tr>
	  <tr>
	    <td>2.1</td><td><span class="tdbg" style="width: 20px;"><input type="checkbox" name="force[force_chk21_status]" readonly="readonly" disabled="disabled" id="Table21" value="1" <?php echo (isset($this->forceInfo['force_chk21_status']) && $this->forceInfo['force_chk21_status']==1)?'checked="checked"':''?> class="forceCheck css-checkbox"/><label for="Table21" class="css-label"></label></span></td><td><label for="Table21">&sect; 14 Tvang i akutte faresituasjoner<!--&sect; 14 Coercion in acute emergencies--></label></td>
	  </tr>
	  <tr>
	    <td>2.2</td><td><span class="tdbg" style="width: 20px;"><input type="checkbox" name="force[force_chk22_status]" readonly="readonly" disabled="disabled" id="Table22" value="1" <?php echo (isset($this->forceInfo['force_chk22_status']) && $this->forceInfo['force_chk22_status']==1)?'checked="checked"':''?> class="forceCheck css-checkbox"/><label for="Table22" class="css-label"></label></span></td><td><label for="Table22">&sect; 15 Kroppsvisitasjon<!--&sect; 15 Body Visitation--></label></td>
	  </tr>
	  <tr>
	    <td>2.3</td><td><span class="tdbg" style="width: 20px;"><input type="checkbox" name="force[force_chk23_status]" readonly="readonly" disabled="disabled" id="Table23" value="1" <?php echo (isset($this->forceInfo['force_chk23_status']) && $this->forceInfo['force_chk23_status']==1)?'checked="checked"':''?> class="forceCheck css-checkbox"/><label for="Table23" class="css-label"></label></span></td><td><label for="Table23">&sect; 16 Ransaking av rom og eiendeler.<!--&sect; 16 searches of rooms and belongings.--></label></td>
	  </tr>
	  <tr>
	    <td>2.4</td><td><span class="tdbg" style="width: 20px;"><input type="checkbox" name="force[force_chk24_status]" readonly="readonly" disabled="disabled" id="Table24" value="1" <?php echo (isset($this->forceInfo['force_chk24_status']) && $this->forceInfo['force_chk24_status']==1)?'checked="checked"':''?> class="forceCheck css-checkbox"/><label for="Table24" class="css-label"></label></span></td><td><label for="Table24">&sect; 17 Beslaglegging, tilintetgj&oslash;ring eller overlevering til politiet<!--&sect; 17 The confiscation, destruction or surrender to police--></label></td>
	  </tr>
	  <tr>
	    <td>2.5</td><td><span class="tdbg" style="width: 20px;"><input type="checkbox" name="force[force_chk25_status]" readonly="readonly" disabled="disabled" id="Table25" value="1" <?php echo (isset($this->forceInfo['force_chk25_status']) && $this->forceInfo['force_chk25_status']==1)?'checked="checked"':''?> class="forceCheck css-checkbox"/><label for="Table25" class="css-label"></label></span></td><td><label for="Table25">&sect; 18 Kontroll av beboerens post inn til institusjonen<!--&sect; 18 Inspection of the resident's entry into the institution--></label></td>
	  </tr>
	  <tr>
	    <td>2.6</td><td><span class="tdbg" style="width: 20px;"><input type="checkbox" name="force[force_chk26_status]" readonly="readonly" disabled="disabled" id="Table26" value="1" <?php echo (isset($this->forceInfo['force_chk26_status']) && $this->forceInfo['force_chk26_status']==1)?'checked="checked"':''?> class="forceCheck css-checkbox"/><label for="Table26" class="css-label"></label></span></td><td><label for="Table26">&sect; 19 Samtykke til &aring; avlegge urinpr&oslash;ver under oppholdet<!--&sect; 19 Consent to take urine samples during stay--></label></td>
	  </tr>
	  <tr>
	    <td>2.7</td><td><span class="tdbg" style="width: 20px;"><input type="checkbox" name="force[force_chk27_status]" readonly="readonly" disabled="disabled" id="Table27" value="1" <?php echo (isset($this->forceInfo['force_chk27_status']) && $this->forceInfo['force_chk27_status']==1)?'checked="checked"':''?> class="forceCheck css-checkbox"/><label for="Table27" class="css-label"></label></span></td><td><label for="Table27">&sect; 20 Tilbakef&oslash;ring ved r&oslash;mming mot beboerens vilje<!--&sect; 20 Reversal escapes the resident's willingness--></label></td>
	  </tr>
	  <tr>
	    <td>2.8</td><td><span class="tdbg" style="width: 20px;"><input type="checkbox" name="force[force_chk28_status]" readonly="readonly" disabled="disabled" id="Table28" value="1" <?php echo (isset($this->forceInfo['force_chk28_status']) && $this->forceInfo['force_chk28_status']==1)?'checked="checked"':''?> class="forceCheck css-checkbox"/><label for="Table28" class="css-label"></label></span></td><td><label for="Table28">&sect; 22 Begrensninger i adgangen til &aring; bevege seg innenfor og utenfor institusjonens omr&aring;de<!--&sect; 22 Limitations on the right to move inside and outside the institution area--></label></td>
	  </tr>
	  <tr>
	    <td>2.9</td><td><span class="tdbg" style="width: 20px;"><input type="checkbox" name="force[force_chk29_status]" readonly="readonly" disabled="disabled" id="Table29" value="1" <?php echo (isset($this->forceInfo['force_chk29_status']) && $this->forceInfo['force_chk29_status']==1)?'checked="checked"':''?> class="forceCheck css-checkbox"/><label for="Table29" class="css-label"></label></span></td><td><label for="Table29">&sect; 23 Nekte beboeren bes&oslash;k i institusjonen<!--&sect; 23 Refusal resident visiting the institution--></label></td>
	  </tr>
	  <tr>
	    <td>2.10</td><td><span class="tdbg" style="width: 20px;"><input type="checkbox" name="force[force_chk210_status]" readonly="readonly" disabled="disabled" id="Table210" value="1" <?php echo (isset($this->forceInfo['force_chk210_status']) && $this->forceInfo['force_chk210_status']==1)?'checked="checked"':''?> class="forceCheck css-checkbox"/><label for="Table210" class="css-label"></label></span></td><td><label for="Table210">&sect; 24 Nekte beboeren &aring; bruke elektroniske kommunikasjonsmidler<!--&sect; 24 Denying the resident to use electronic means--></label></td>
	  </tr>
	  <tr>
	    <td>2.11</td><td><span class="tdbg" style="width: 20px;"><input type="checkbox" name="force[force_chk211_status]" readonly="readonly" disabled="disabled" id="Table211" value="1" <?php echo (isset($this->forceInfo['force_chk211_status']) && $this->forceInfo['force_chk211_status']==1)?'checked="checked"':''?> class="forceCheck css-checkbox"/><label for="Table211" class="css-label"></label></span></td><td><label for="Table211">&sect; 25 Adgang til &aring; kreve urinpr&oslash;ver f&oslash;lger av fylkesnemndas vedtak / Samtykke til &aring; avlegge urinpr&oslash;ver ved inntak og under oppholdet<!--&sect; 25 Right to require urine samples provided by the county board's decision / Consent to take urine samples at admission and during stay--></label></td>
	  </tr>
	  <tr>
	    <td>3</td><td><span class="tdbg" style="width: 20px;"><input type="checkbox" name="ckhId3" id="Table3" value="1" disabled="disabled" checked="checked" class="forceCheck css-checkbox"/><label for="Table3" class="css-label"></label></span></td><td>- Gjennomgang av tvangsbruken med beboer<!--- Review of the use of force with occupant-->- Beboerens klage<!--- The resident&#39;s complaint--></td>
	  </tr>
	  <tr>
	    <td>4</td><td><span class="tdbg" style="width: 20px;"><input type="checkbox" name="ckhId4" id="Table4" value="1" disabled="disabled" checked="checked" class="forceCheck css-checkbox"/><label for="Table4" class="css-label"></label></span></td><td>Institusjonens kommentarer til beboers klage<!--Institution comments on the resident&#39;s complaint--></td>
	  </tr>
	  <tr>
	    <td>5</td><td><span class="tdbg" style="width: 20px;"><input type="checkbox" name="ckhId5" id="Table5" value="1" disabled="disabled" checked="checked" class="forceCheck css-checkbox"/><label for="Table5" class="css-label"></label></span></td><td>Institusjonens vurdering<!--The institution's assessment--></td>
	  </tr>
	</tbody>
</table>