<table cellspacing=0 cellpadding="0" border="0px" width="100%">
  <tr>
	<td style="padding:0px;">
		<table cellspacing=0 cellpadding="5" border="0px" class="bordercolor" style="border-collapse:collapse; margin-left:0pt" width="100%">
			<tr>
				<th style="width: 100%;" colspan="3"><h2>2.1 &sect; 14 Tvang i akutte faresituasjoner <!--&sect; 14 Coercion in acute emergencies--></h2></th>
			</tr>
		  <tr>
		  	<td colspan="3">Hver hjemmel st&aring;r p&aring; egen siden, da det kun er den dokumentasjonen som er utfylt, som skal oversendes Fylkesmannen uten ugrunnet opphold.<!--Each authority is on their side, since only the documentation is completed, which shall be submitted to the County without undue delay.--></td>
		</tr>
		  
		  <tr>
			<td class="title1" rowspan="2" width="33%">Forholdet gjelder en fare for:<!--The relationship applies a danger:--></td>
			<td align="left" colspan="2"><span class="nonecls1"><span class="tdbg"><input type="checkbox" id="force_chk21_personal" name="force214[force_chk21_personal]" <?php echo (isset($this->forceInfo['force_chk21_personal']) && $this->forceInfo['force_chk21_personal']=='1')?'checked="checked"':'';?> value="1" class="css-checkbox"/><label for="force_chk21_personal" class="css-label"></label></span></span>skade p&aring; person<!--personal injury--></td>
		  </tr>
		  <tr>
			<td align="left" colspan="2"><span class="nonecls1"><span class="tdbg"><input type="checkbox" id="force_chk21_property" name="force214[force_chk21_property]" <?php echo (isset($this->forceInfo['force_chk21_property']) && $this->forceInfo['force_chk21_property']=='1')?'checked="checked"':'';?> value="1"  class="css-checkbox"/><label for="force_chk21_property" class="css-label"></label></span></span>vesentlig skade p&aring; eiendom<!--substantial property damage--></td>
		  </tr>
		  
		  <tr>
			<td class="title1">Beskriv hva som skjedde f&oslash;r  faresituasjonen oppstod:<!--Describe what happened before the dangerous situation occurred:--><br />
			(Hva gjorde beboer, andre beboere og ansatte?)<!--(What did the resident, other residents and staff?)--></td>
			<td align="left" colspan="2" class="nonecls1">
				<span class="tdbg1"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;" class="validation" id="force_txta21_happened" name="force214[force_txta21_happened]"><?php echo (isset($this->forceInfo['force_txta21_happened']) && $this->forceInfo['force_txta21_happened']!='')?$this->forceInfo['force_txta21_happened']:'';?></textarea></span>
			</td>
		  </tr>
		  
		  <tr>
		  	<td class="title1">Gi en n&aelig;rmere beskrivelse av selve faresituasjonen og skaden du ville forhindre:<!--Give a detailed description of the risk situation and the damage you would prevent:--></td>
			<td align="left" colspan="2" class="nonecls1">
				<span class="tdbg1"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;" class="validation" id="force_txta21_prevent" name="force214[force_txta21_prevent]"><?php echo (isset($this->forceInfo['force_txta21_prevent']) && $this->forceInfo['force_txta21_prevent']!='')?$this->forceInfo['force_txta21_prevent']:'';?></textarea></span></td></tr>
		  <tr>
		  	<td class="title1">Beskriv tiltak som er fors&oslash;kt og/eller vurdert som nyttel&oslash;se, &aring;penbart forgjeves eller utilstrekkelige:<!--Describe the measures that have been tried and / or considered useless, obviously futile or inadequate:--></td>
			<td align="left" colspan="2" class="nonecls1">
				<span class="tdbg1"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;" class="validation" id="force_txta21_inadequate" name="force214[force_txta21_inadequate]"><?php echo (isset($this->forceInfo['force_txta21_inadequate']) && $this->forceInfo['force_txta21_inadequate']!='')?$this->forceInfo['force_txta21_inadequate']:'';?></textarea></span>
			</td>
		  </tr>
		  <tr>
		  	<td class="title1">Hvordan ble tvange n gjennomf&oslash;rt, herunder hvilke(t) tvangsmiddel ble benyttet?<!--How were forcibly n completed, including the (t) coercive measures were used?--></td>
			<td align="left" colspan="2" class="nonecls1">
				<span class="tdbg1"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;" id="force_txta21_coercive" class="validation"  name="force214[force_txta21_coercive]"><?php echo (isset($this->forceInfo['force_txta21_coercive']) && $this->forceInfo['force_txta21_coercive']!='')?$this->forceInfo['force_txta21_coercive']:'';?></textarea></span>
			</td>
		  </tr>
		  <tr>
		  	<td class="title1">Vurder om den grad av tvang som ble benyttet var avpasset den fare som forel&aring;?<!--Consider the degree of force used was adapted the danger that existed?--></td>
			<td align="left" colspan="2" class="nonecls1">
				<span class="tdbg1"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;" id="force_txta21_degree" class="validation"  name="force214[force_txta21_degree]"><?php echo (isset($this->forceInfo['force_txta21_degree']) && $this->forceInfo['force_txta21_degree']!='')?$this->forceInfo['force_txta21_degree']:'';?></textarea></span>
			</td>
		  </tr>
		  <tr>
		    <td class="title1">Hvor lenge varte tvangsbruken?<!--How long did the use of force?--></td>
		  	<td class="nonecls1 value1" colspan="2"><span class="tdbg1"><input type="text" class="validation" style="width:99%;" id="force_txt21_howlong" name="force214[force_txt21_howlong]" value="<?php echo (isset($this->forceInfo['force_txt21_howlong']) && $this->forceInfo['force_txt21_howlong']!='')?$this->forceInfo['force_txt21_howlong']:'';?>" /></span></td></tr>
		  <tr>
			<td class="title1" colspan="2">Opph&oslash;rte tvangsbruke n straks skaden eller faren var avverget?<!--Ceased forced to use n immediately the damage or the danger was averted?--></td>
			<td align="left" width="33%" class="nonecls1"><span class="tdbg1">
			  <select class="width98 validation" name="force214[force_sel21_averted]" id="force_sel21_averted" onchange="changeAreaClass(this.value,'yes','rem','#force_txta21_averted_res','no');">
				<option value="" <?php echo (!isset($this->forceInfo['force_sel21_averted']) || $this->forceInfo['force_sel21_averted']=='')?'selected="selected"':'';?>>Velg<!--Select--></option>
				<option value="yes" <?php echo (isset($this->forceInfo['force_sel21_averted']) && $this->forceInfo['force_sel21_averted']=='yes')?'selected="selected"':'';?>>  Yes<!--Yes--></option>
				<option value="no" <?php echo (isset($this->forceInfo['force_sel21_averted']) && $this->forceInfo['force_sel21_averted']=='no')?'selected="selected"':'';?>>  no<!--No--></option>
			  </select></span>
			</td>
		  </tr>
		  <tr><td class="title1" colspan="2">Hvis nei, hvorfor ikke:<!--If no, why not:--></td>
			<td class="nonecls1 value1">
				<span class="tdbg1"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;" id="force_txta21_averted_res"  name="force214[force_txta21_averted_res]"><?php echo (isset($this->forceInfo['force_txta21_averted_res']) && $this->forceInfo['force_txta21_averted_res']!='')?$this->forceInfo['force_txta21_averted_res']:'';?></textarea></span>
			</td>
		  </tr>	
		  <tr>
			<td class="title1" colspan="2">Var det n&oslash;dvendig &aring; isolere beboeren?<!--Was it necessary to isolate the resident?--></td>
			<td class="nonecls1 value1"><span class="tdbg1">
			  <select class="width98 validation" name="force214[force_sel21_resident]" id="force_sel21_resident" onchange="changeAreaClass(this.value,'','rem','#force_sel21_decision','yes'); changeAreaClass(this.value,'','rem','#force_sel21_adjoin','yes'); changeAreaClass(this.value,'','rem','#force_sel21_insulation','yes'); changeAreaClass(this.value,'','rem','#force_txta21_timeaspect','yes'); changeAreaClass(this.value,'','rem','#force_sel21_police','yes'); changeAreaClass(this.value,'','rem','#force_txta21_police_res','yes');">
				<option value="" <?php echo (!isset($this->forceInfo['force_sel21_resident']) || $this->forceInfo['force_sel21_resident']=='yes')?'selected="selected"':'';?>>Velg<!--Select--></option>
				<option value="yes" <?php echo (isset($this->forceInfo['force_sel21_resident']) && $this->forceInfo['force_sel21_resident']=='yes')?'selected="selected"':'';?>>  Ja<!--Yes--></option>
				<option value="no" <?php echo (isset($this->forceInfo['force_sel21_resident']) && $this->forceInfo['force_sel21_resident']=='no')?'selected="selected"':'';?>>  Nei<!--No--></option>
			  </select></span>
			</td>
		  </tr>
		  <tr>
			<td class="title1" colspan="2">Hvis ja : Hvem traff beslutning om &aring; isolere? <!--If yes : Who hit the decision to isolate?--></td>
			<td align="left"  class="nonecls1"><span class="tdbg1">
				  <select class="width98" id="force_sel21_decision" name="force214[force_sel21_decision]" onchange="changeAreaClass(this.value,'','rem','#force_txt21_decision_name','leader');">
					<option value="" <?php echo (!isset($this->forceInfo['force_sel21_decision']) || $this->forceInfo['force_sel21_decision']=='')?'selected="selected"':'';?>>Velg<!--Select--></option>
					<option value="conductor" <?php echo (isset($this->forceInfo['force_sel21_decision']) && $this->forceInfo['force_sel21_decision']=='conductor')?'selected="selected"':'';?>>  Leder<!--Director--></option>
					<option value="leader" <?php echo (isset($this->forceInfo['force_sel21_decision']) && $this->forceInfo['force_sel21_decision']=='leader')?'selected="selected"':'';?>> Fullmakt fra leder<!--Proxy Manager--></option>
				  </select></span>
			</td>
		  </tr>
		  <tr>
			<td class="title1" colspan="2">Hvis fullmakt fra leder:<!--If authorization from the manager:--></td>
			<td class="nonecls1 value1"><span class="padding5">Navn:</span><!--Name:--><span class="tdbg1"><input type="text"  id="force_txt21_decision_name"  name="force214[force_txt21_decision_name]" value="<?php echo (isset($this->forceInfo['force_txt21_decision_name']) && $this->forceInfo['force_txt21_decision_name']!='')?$this->forceInfo['force_txt21_decision_name']:'';?>" /></span></td>
		  </tr>
		  <tr>
			<td class="title1" colspan="2">
				Var minst en av personalet alltid til stede i rommet eller i naborom med ul&aring;st d&oslash;r?<!--Was at least one of the staff always present in the room or in adjoining rooms with door unlocked?--></td>
			<td class="nonecls1 value1"><span class="tdbg1">
				<select class="width98" name="force214[force_sel21_adjoin]" id="force_sel21_adjoin">
					<option value="" <?php echo (!isset($this->forceInfo['force_sel21_adjoin']) || $this->forceInfo['force_sel21_adjoin']=='')?'selected="selected"':'';?>>Velg<!--Select--></option>
					<option value="yes" <?php echo (isset($this->forceInfo['force_sel21_adjoin']) && $this->forceInfo['force_sel21_adjoin']=='yes')?'selected="selected"':'';?>>  Ja<!--Yes--></option>
					<option value="no" <?php echo (isset($this->forceInfo['force_sel21_adjoin']) && $this->forceInfo['force_sel21_adjoin']=='no')?'selected="selected"':'';?>>  Nei<!--No--></option>
				  </select></span>
			</td>
		   </tr>
		   <tr>
			 <td class="title1" colspan="2">Fant isoleringen sted i rom med vindu og med minst 8m<sup>2</sup> gulvflate?<!--Found insulation place in room with window and with at least 8m<sup>2</sup> of floor area?--></td>
			<td class="nonecls1 value1"><span class="tdbg1">
				  <select class="width98" name="force214[force_sel21_insulation]" id="force_sel21_insulation">
					<option value="" <?php echo (!isset($this->forceInfo['force_sel21_insulation']) || $this->forceInfo['force_sel21_insulation']=='')?'selected="selected"':'';?>>Velg<!--Select--></option>
					<option value="yes" <?php echo (isset($this->forceInfo['force_sel21_insulation']) && $this->forceInfo['force_sel21_insulation']=='yes')?'selected="selected"':'';?>>  Ja<!--Yes--></option>
					<option value="no" <?php echo (isset($this->forceInfo['force_sel21_insulation']) && $this->forceInfo['force_sel21_insulation']=='no')?'selected="selected"':'';?>> Nei <!--No--></option>
				  </select></span>
			</td>
		  </tr>
		  <tr>
			<td class="title1">
				Hvor lenge var det n&oslash;dvendig &aring; isolere beboe ren:<!--How long was it necessary to isolate pure habitation:--><br />
				Begrunn tidsaspektet.<!--Justify the time aspect.-->
			</td>
			<td align="left" colspan="2" class="nonecls1">
				<span class="tdbg1"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;"  name="force214[force_txta21_timeaspect]" id="force_txta21_timeaspect"><?php echo (isset($this->forceInfo['force_txta21_timeaspect']) && $this->forceInfo['force_txta21_timeaspect']!='')?$this->forceInfo['force_txta21_timeaspect']:'';?></textarea></span>
			</td>
		  </tr>
		  <tr>
			<td class="title1" >Ble politi benyttet?<!--Were police used?--></td>
			<td align="left" colspan="2" class="nonecls1"><span class="tdbg1">
				<select class="width98" name="force214[force_sel21_police]" id="force_sel21_police"  onchange="changeAreaClass(this.value,'','rem','#force_txta21_police_res','yes');">
					<option value="" <?php echo (!isset($this->forceInfo['force_sel21_police']) || $this->forceInfo['force_sel21_police']=='')?'selected="selected"':'';?>>Velg<!--Select--></option>
					<option value="yes"  <?php echo (isset($this->forceInfo['force_sel21_police']) && $this->forceInfo['force_sel21_police']=='yes')?'selected="selected"':'';?>>  Ja<!--Yes--></option>
					<option value="no" <?php echo (isset($this->forceInfo['force_sel21_police']) && $this->forceInfo['force_sel21_police']=='no')?'selected="selected"':'';?>>  Nei<!--No--></option>
				  </select></span>
			</td>
		  </tr>
		  <tr>
			<td class="title1">
				Hvis ja, begrunn hvorfor:<!--If yes, give reasons why:-->
			</td>
			<td align="left" colspan="2" class="nonecls1">
				<span class="tdbg1"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;" id="force_txta21_police_res" name="force214[force_txta21_police_res]"><?php echo (isset($this->forceInfo['force_txta21_police_res']) && $this->forceInfo['force_txta21_police_res']!='')?$this->forceInfo['force_txta21_police_res']:'';?></textarea></span>
			</td>
		  </tr>
		</table>
	</td>
  </tr>
</table>