<table cellspacing=0 cellpadding="0" border="0px" style="" width="100%">
   <tr>
	<td  style="padding:0px">
	  <table cellspacing=0 cellpadding="5" border="0px" style="border-collapse:collapse; margin-left:0pt" width="100%"  class="bordercolor">
		<thead>
			<tr>
				<th style="width: 100%;" colspan="2"><h2>4 Institusjonens kommentarer til beboers klage<!--Institution comments on the resident&#39;s complaint--></h2></th>
			</tr>
		</thead>
		<tbody>
		  <tr>
			<td align="left" colspan="2">
			  <ul type="circle">
				<li>N&aring;r beboer klager skal ansvarlig leder kommentere klagen .<!--When inmate complaints managers are responsible comment complaint.--></li>
				<li>Institusjonens kommentar sendes uten ugrunnet opphold til Fylkesmannen, sammen med beboers klage.<!--Institution comment submitted without undue delay to the County, along with the resident&#39;s complaint.--></li>
			  </ul>
			</td>
		  </tr>
		  <tr>
			<td align="left" width="100%" colspan="2" class="nonecls1">
			<span class="tdbg1">
				<textarea id="force_txta4_desc" name="force[force_txta4_desc]" onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;" ><?php echo (isset($this->forceInfo['force_txta4_desc']) && $this->forceInfo['force_txta4_desc']!='')?$this->forceInfo['force_txta4_desc']:'';?></textarea>
			</span>
			</td>
		  </tr>
		</tbody>
	  </table>
	</td>
   </tr>
 </table>