<table cellspacing=0 cellpadding="0" border="0px" width="100%">
  <tr>
	<td style="padding:0px;">
		<table cellspacing=0 cellpadding="5" border="0px" style="border-collapse:collapse; margin-left:0pt" width="100%" class="bordercolor">
			<thead>
				<tr>
					<th style="width: 100%;" colspan="2"><h2>2.8 &sect; 22 Begrensninger i adgangen til &aring; bevege seg innenfor og utenfor institusjonens omr&aring;de <!--&sect; 22 Limitations on the right to move inside and outside the institution area--></h2></th>
				</tr>
			</thead>
			<tbody>
			 <tr><td colspan="2">Hver hjemmel st&aring;r p&aring; egen siden, da det kun er den dokumentasjonen som er utfylt, som skal oversendes Fylkesmannen uten ugrunnet opphold.<!--Each authority is on their side, since only the documentation is completed, which shall be submitted to the County without undue delay.--></td></tr>
			  <tr><td colspan="2"><u>For &aring; benytte denne bestemmelsen m&aring; beboer v&aelig;re  plassert med hjemmel i barnevernloven &sect;&sect; 4-24, 4-26 eller 4-25 annet ledd.<!--To use this provision must inmate being placed pursuant to the Child Welfare Act &sect; &sect; 4-24, 4-26 or 4-25, second paragraph.--></u></td></tr>
			  <tr>
				<td class="title1" rowspan="2">Forholdet omhandler begrensning i bevegelsesfriheten:<!--Relationship deals with restriction of freedom of movement:--></td>
				<td class="value1"><span class="nonecls1"><span class="tdbg"><input type="checkbox" name="force2511[force_chk28_within]"  class="css-checkbox" id="force_chk28_within" value="1" <?php echo (isset($this->forceInfo['force_chk28_within']) && $this->forceInfo['force_chk28_within']=='1')?'checked="checked"':'';?>/><label for="force_chk28_within" class="css-label"></label></span></span><label for="force_chk28_within">innenfor institusjonen</label><!--within the institution--> </td>
			 </tr>
			 <tr>
				<td class="value1"><span class="nonecls1"><span class="tdbg"><input type="checkbox" name="force2511[force_chk28_outside]" class="css-checkbox" id="force_chk28_outside" value="1" <?php echo (isset($this->forceInfo['force_chk28_outside']) && $this->forceInfo['force_chk28_outside']=='1')?'checked="checked"':'';?>/><label for="force_chk28_outside" class="css-label"></label></span></span><label for="force_chk28_outside">utenfor institusjonen</label><!--outside the institution--></td>
			 </tr>
			 <tr>
				<td class="title1"><label for="force_chk25_drug">Beskriv begrensningen(e):</label><!--limitation(s):--></td>
				<td class="value1 nonecls1"><span class="tdbg1"><textarea class="validation" onkeyup="textAreaAdjust(this)" style="overflow:visible;width: 100%; border: none; height:auto;" name="force2511[force_txta28_limit]"><?php echo (isset($this->forceInfo['force_txta28_limit']) && $this->forceInfo['force_txta28_limit']!='')?$this->forceInfo['force_txta28_limit']:'';?></textarea><label for="force_chk25_drug" class="css-label"></label></span></td>

			  </tr>
			  <tr>
				<td class="title1" width="60%">Redegj&oslash;r for de individuelle og konkrete forhold som tilsier at begrensning i beboerens bevegelses frihet er n&oslash;dvendig ut fra form&aring;let med plasseringen:<!--Describe the individual and specific circumstances indicating that the restriction of residents&#39; movement freedom is necessary for the purpose of location:--></td>
				<td class="nonecls1 value1" width="40%"><span class="tdbg1"><textarea class="validation" id="force_txta28_location" onkeyup="textAreaAdjust(this)" style="overflow:visible;width: 100%; border: none; height:auto;" name="force2511[force_txta28_location]"><?php echo (isset($this->forceInfo['force_txta28_location']) && $this->forceInfo['force_txta28_location']!='')?$this->forceInfo['force_txta28_location']:'';?></textarea></span></td>
			  </tr>	
			  <tr>
				<td class="title1">
				Hvor lenge er det n&oslash;dvendig &aring; sette begrensning for beboerens bevegelse sfrihet:<!--How long is it necessary to put restriction on residents&#39; movement sfrihet:-->
				(Begrunn tidsaspektet opp mot form&aring;let med plasseringen.)<!--(Justify the time aspect to the purpose of the placement.)-->
				</td>
				<td class="nonecls1 value1"><span class="tdbg1"><textarea class="validation" onkeyup="textAreaAdjust(this)" style="overflow:visible;width: 100%; border: none; height:auto;" name="force2511[force_txta28_howlong]" id="force_txta28_howlong"><?php echo (isset($this->forceInfo['force_txta28_howlong']) && $this->forceInfo['force_txta28_howlong']!='')?$this->forceInfo['force_txta28_howlong']:'';?></textarea></span></td>
			  </tr>				  

			</tbody>
		</table>
	</td>
  </tr>
</table>