<table cellspacing=0 cellpadding="0" border="0px"  width="100%">
  <tr>
	<td style="padding:0px;">
		<table cellspacing=0 cellpadding="5" border="0px" style="border-collapse:collapse; margin-left:0pt" width="100%" class="bordercolor">
			<thead>
				<tr>
					<th style="width: 100%;" colspan="2"><h2>2.9 &sect; 23 Nekte beboeren bes&oslash;k i institusjonen<!--&sect; 23 Refusal resident visiting the institution--></h2></th>
				</tr>
			</thead>
			<tbody>
			 <tr><td colspan="2">Hver hjemmel st&aring;r p&aring; egen siden, da det kun er den dokumentasjonen som er utfylt, som skal oversendes Fylkesmannen uten ugrunnet opphold.<!--Each authority is on their side, since only the documentation is completed, which shall be submitted to the County without undue delay.--></td></tr>
			 <tr><td colspan="2"><u>For &aring; benytte denne bestemmelsen m&aring; beboer v&aelig;re plassert med hjemmel i barnevernloven &sect;&sect; 4-24, 4-26 eller 4-25 annet ledd.<!--To use this provision must inmate being placed pursuant to the Child Welfare Act &sect; &sect; 4-24, 4-26 or 4-25, second paragraph.--></u></td></tr>
			 <tr>
				<td class="title1" width="60%">
					Redegj&oslash;r for de individuelle og konkrete forhold som tilsier at det er n&oslash;dvendig &aring; nekte beboeren bes&oslash;k utfra form&aring;let med plasseringen:<!--Describe the individual and specific circumstances indicating that it is necessary to deny the resident visits the basis of the purpose of the position:-->
				</td>
				<td class="value1 nonecls1" width="40%">
					<span class="tdbg1"><textarea class="validation" id="force_txta29_location"  onkeyup="textAreaAdjust(this)" style="overflow:visible;width: 100%; border: none; height:auto;" name="force2511[force_txta29_location]"><?php echo (isset($this->forceInfo['force_txta29_location']) && $this->forceInfo['force_txta29_location']!='')?$this->forceInfo['force_txta29_location']:'';?></textarea></span>
				</td>
			  </tr>
			  <tr>
				<td class="title1">Beskriv begrensningen(e):<!--Describe the limitation(s):--></td>
				<td class="value1 nonecls1"><span class="tdbg1"><textarea class="validation" id="force_txta29_limit" onkeyup="textAreaAdjust(this)" style="overflow:visible;width: 100%; border: none; height:auto;"  name="force2511[force_txta29_limit]"><?php echo (isset($this->forceInfo['force_txta29_limit']) && $this->forceInfo['force_txta29_limit']!='')?$this->forceInfo['force_txta29_limit']:'';?></textarea></span></td>
			  </tr>	
			  <tr>
				<td class="title1">
				Hvor lenge er det n&oslash;dvendig &aring; nekte beboeren bes&oslash;k:<!--How long is it necessary to deny the resident visit:--><br />
				(Begrunn tidsaspektet opp mot form&aring;let med plasseringen.)<!--(Justify the time aspect to the purpose of the placement.)-->
				</td>
				<td class="value1 nonecls1"><span class="tdbg1"><textarea class="validation" id="force_txta29_howlong"  onkeyup="textAreaAdjust(this)" style="overflow:visible;width: 100%; border: none; height:auto;"  name="force2511[force_txta29_howlong]"><?php echo (isset($this->forceInfo['force_txta29_howlong']) && $this->forceInfo['force_txta29_howlong']!='')?$this->forceInfo['force_txta29_howlong']:'';?></textarea></span></td>
			  </tr>				  
			</tbody>
		</table>
	</td>
  </tr>
</table>