<div class="PSUBTCWRAPPER">
	<div class="PSUBTCLEFT">
    <?php echo $this->translate('Force');?>
    </div>
</div>
<div class="CLEARBBORDER"></div>
<table cellpadding="0" cellspacing="5" border="0" width="100%" class="scrollable">
 <tr id="IdTable1">
  <td class="force" style="padding:0px" >
  <?php echo $this->partial('force/tabsArchive/force/force1.phtml',array('forceInfo'=>$this->forceInfo));?>   
  </td>
 </tr>
 
 <tr id="IdTable21" style="width:100%; <?php echo (isset($this->forceInfo['force_chk21_status']) && $this->forceInfo['force_chk21_status']==1)?';display:block':';display:none;'?>">
  <td class="force" style="padding:0px">
  <?php echo $this->partial('force/tabsArchive/force/force21.phtml',array('forceInfo'=>$this->forceInfo));?>   
  </td>
 </tr>

 <tr id="IdTable22" style="width:100%; <?php echo (isset($this->forceInfo['force_chk22_status']) && $this->forceInfo['force_chk22_status']==1)?';display:block':';display:none;'?>">
  <td class="force" style="padding:0px">
  <?php echo $this->partial('force/tabsArchive/force/force22.phtml',array('forceInfo'=>$this->forceInfo));?>   
  </td>
 </tr>

 <tr id="IdTable23" style="width:100%; <?php echo (isset($this->forceInfo['force_chk23_status']) && $this->forceInfo['force_chk23_status']==1)?';display:block':';display:none;'?>">
  <td class="force" style="padding:0px">
  <?php echo $this->partial('force/tabsArchive/force/force23.phtml',array('forceInfo'=>$this->forceInfo));?>   
  </td>
 </tr>

 <tr id="IdTable24" style="width:100%; <?php echo (isset($this->forceInfo['force_chk24_status']) && $this->forceInfo['force_chk24_status']==1)?';display:block':';display:none;'?>">
  <td class="force" style="padding:0px">
  <?php echo $this->partial('force/tabsArchive/force/force24.phtml',array('forceInfo'=>$this->forceInfo));?>   
  </td>
 </tr>

 <tr id="IdTable25" style="width:100%; <?php echo (isset($this->forceInfo['force_chk25_status']) && $this->forceInfo['force_chk25_status']==1)?';display:block':';display:none;'?>">
  <td class="force" style="padding:0px">
  <?php echo $this->partial('force/tabsArchive/force/force25.phtml',array('forceInfo'=>$this->forceInfo));?>   
  </td>
 </tr>

 <tr id="IdTable26" style="width:100%; <?php echo (isset($this->forceInfo['force_chk26_status']) && $this->forceInfo['force_chk26_status']==1)?';display:block':';display:none;'?>">
  <td class="force" style="padding:0px" >
  <?php echo $this->partial('force/tabsArchive/force/force26.phtml',array('forceInfo'=>$this->forceInfo));?>
  </td>
 </tr>

 <tr id="IdTable27" style="width:100%; <?php echo (isset($this->forceInfo['force_chk27_status']) && $this->forceInfo['force_chk27_status']==1)?';display:block':';display:none;'?>">
  <td class="force" style="padding:0px" >
  <?php echo $this->partial('force/tabsArchive/force/force27.phtml',array('forceInfo'=>$this->forceInfo));?>
  </td>
 </tr>

 <tr id="IdTable28" style="width:100%; <?php echo (isset($this->forceInfo['force_chk28_status']) && $this->forceInfo['force_chk28_status']==1)?';display:block':';display:none;'?>">
  <td class="force" style="padding:0px" >
  <?php echo $this->partial('force/tabsArchive/force/force28.phtml',array('forceInfo'=>$this->forceInfo));?>
  </td>
 </tr>

 <tr id="IdTable29" style="width:100%; <?php echo (isset($this->forceInfo['force_chk29_status']) && $this->forceInfo['force_chk29_status']==1)?';display:block':';display:none;'?>">
  <td class="force" style="padding:0px" >
  <?php echo $this->partial('force/tabsArchive/force/force29.phtml',array('forceInfo'=>$this->forceInfo));?>
  </td>
 </tr>

 <tr id="IdTable210" style="width:100%; <?php echo (isset($this->forceInfo['force_chk210_status']) && $this->forceInfo['force_chk210_status']==1)?';display:block':';display:none;'?>">
  <td class="force" style="padding:0px" >
  <?php echo $this->partial('force/tabsArchive/force/force210.phtml',array('forceInfo'=>$this->forceInfo));?>
  </td>
 </tr>

 <tr id="IdTable211" style="width:100%; <?php echo (isset($this->forceInfo['force_chk211_status']) && $this->forceInfo['force_chk211_status']==1)?';display:block':';display:none;'?>">
  <td class="force" style="padding:0px" >
  <?php echo $this->partial('force/tabsArchive/force/force211.phtml',array('forceInfo'=>$this->forceInfo));?>
  </td>
 </tr>
 
 <tr id="IdTable3">
  <td class="force" style="padding:0px" >
  <?php echo $this->partial('force/tabsArchive/force/force3.phtml',array('forceInfo'=>$this->forceInfo));?>
  </td>
 </tr>

 <tr id="IdTable4" >
  <td class="force" style="padding:0px">
  <?php echo $this->partial('force/tabsArchive/force/force4.phtml',array('forceInfo'=>$this->forceInfo));?>
  </td>
 </tr>

 <tr id="IdTable5">
  <td class="force" style="padding:0px" >
  <?php echo $this->partial('force/tabsArchive/force/force5.phtml',array('forceInfo'=>$this->forceInfo));?>
  </td>
 </tr>
</table>