<?php $format = KD::getModel('core/format');
$weekplanId = $this->weekplanID;
if(isset($weekplanId) && $weekplanId>0 && isset($this->weekplanCollection)):?>
    <form name="frmClientEditMaal" id="frmClientEditMaal" method="post" action="<?php echo $this->getUrl("client/weekplan/editweekplanpost/id/".$weekplanId.'/pid/'.$this->weekplanCollection['weekplan_patientID']);?>">
        <input type="hidden" id="date-alt-field" name="date-alt-field" value="<?php echo date('Y-m-d', strtotime($this->weekplanCollection['weekplan_date'])); ?>" />
        <table width="100%" border="0" cellspacing="4" cellpadding="0" id="clientEditMaalTbl">
    <tr class="CURNONPOINTER">
		<th class="TSLRTDCENTER" width="50%"><?php echo $this->translate('Date');?></th>
		<th class="TSLRTDCENTER" width="50%"><?php echo $this->translate('Time'); ?></th>
      </tr>
    <tr>
          <td class="nonecls"><span class="tdbg"><input type="text" name="weekplan_date" value="<?php echo $format->FormatDate($this->weekplanCollection['weekplan_date']);?>" data-validation="required" readonly  id="weekplan_date" class="DyndatepickerImage1 width70"/></span></td>
          <td class="nonecls">
              <span class="tdbg">
                  <input type="text" id="weekplan_time" name="weekplan_time" value="<?php echo ''; ?>" />
              </span>
          </td>
      </tr>
    <tr>
        <td><?php echo $this->translate('Title');?></td>
        <td>
        </td>
    </tr>
    <tr>
        <td colspan="2" class="nonecls">
              <span class="tdbg">
                  <input type="text" id="weekplan_title" name="weekplan_title" value="<?php echo $this->weekplanCollection['weekplan_title']; ?>" />
              </span>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Description'); ?></td>
        <td></td>
    </tr>
    <tr>
          <td class="nonecls" colspan="2"><span class="tdbg1c"><textarea class="bordernone" name="weekplan_desc" id="weekplan_desc" data-validation="" ><?php echo $this->weekplanCollection['weekplan_desc'];?></textarea></span></td>
	</tr>

</table>
    <div class="floatleft">
        <a href="<?php echo $this->getUrl('client/weekplan/delete/id/' . $weekplanId . '/clientId/' . $this->weekplanCollection['weekplan_patientID']); ?>" class="button">Slett</a>
    </div>
    <div class="floatright">
        <div class="OPPRETTB" style="margin-top:0px;!important;"><input type="submit" class="OPPRETTBA" value="<?php echo $this->translate('Save');?>"/></div>
    </div>
    <div class="CLEARBBORDER"></div>
    </form>
<?php endif;?>