<?php $format=KD::getModel('core/format');?>
<div>
<form name="frmClientAddInsTiltak" id="frmClientAddInsTiltak" method="post" action="<?php echo $this->getUrl("client/mto/addinstiltak");?>">
<div class="PSUBTCWRAPPER">
	<div class="PSUBTCLEFT">
    	<?php echo $this->translate('Institute Measure');?>
    </div>
</div>
<div class="CLEARBBORDER"></div>
<div class="KKI2C">
<table width="100%" border="0" cellspacing="4" cellpadding="0" id="clientInsTiltakTbl">
      <tr class="CURNONPOINTER">
        <th class="TSLRTDNUMBER">
        <span class="tdbg2">
        	<input type="checkbox" name="checkbox_all" id="checkbox_all" class="css-checkbox" data-form="frmClientAddInsTiltak"/>
            <label for="checkbox_all" class="css-label"></label>
        </span>
		<input type="hidden" name="patient_id" id="patient_id" value="<?php echo $this->clientID;?>"/>
        </th>
		<th class="TSLRTDCENTER aligncenter"><?php echo $this->translate('Owner');?></th>
		<th class="TSLRTDCENTER" width="95%"><?php echo $this->translate('Institute Measure');?></th>
      </tr>
	  <?php  if(count($this->tiltakCollection)>0):
	  	$maalIdLoop = '';
		foreach($this->tiltakCollection as $tiltak):  ?>
		<?php $id = $tiltak['tilins_id']; 
		$maal_id = $tiltak['maal_id'];
		if($maal_id!=$maalIdLoop):
		?>
		<tr>
			<td class="head-content" colspan="3"><?php echo $tiltak['maal_desc'];?></td>
		  </tr>
		<?php endif;?>
		  <tr>
			<td class="TSLRTDNUMBER bgwhite">
				<span class="tdbg" style="width: 20px;">
				<input type="checkbox" name="<?php echo 'checkbox_'.$id;?>" id="<?php echo 'checkbox_'.$id;?>" class="css-checkbox"/>
				<label for="<?php echo 'checkbox_'.$id;?>" class="css-label"></label>
				</span>
			</td>
			<td class="bgwhite aligncenter width15"><span class="tdbg"><?php echo $tiltak['tilins_owner']; ?></span></td>
			<td><span class="tdbg dialog-ajax1" data-url="<?php echo $this->getUrl('client/mto/editinstiltak/id/'.$id);?>" data-title="<?php echo $tiltak['tilins_desc']; ?>"><?php echo $tiltak['tilins_desc']; ?></span></td>
		  </tr>
		
		<?php 
		$maalIdLoop = $maal_id;
		endforeach; 
		//echo $this->paginationControl($this->tiltakCollection, 'Sliding', 'control.phtml', array('page'=>'pi','tt'=>'61','t'=>'6'));
	  endif;?>
</table>
</div>

<div class="mtodroplist1">
<div class="mtodroplist11">
    <span class="KITINRDLISTWSPAN">
    	<select name="selAction" class="onSelectAction" data-form="frmClientAddInsTiltak">
        	<option value="" style=" font-weight:bold;"><?php echo $this->translate('Select %s %s',$this->translate('Type of Action'),$this->translate('Here!'));?></option>
            <option value="<?php echo $this->getUrl('client/mto/archiveinstiltak');?>"><?php echo $this->translate('%s %s',$this->translate('Archive'),$this->translate('Institute Measure'));?></option>
        </select> 
    </span>  	
</div>
</div>
<div class="mtodroplist2">
	<div class="CANCELB"><a class="leggtilrada" id="clientAddInsTiltak" data-val="0"><?php echo $this->translate('Add %s(s)',$this->translate('Row'));?></a></div>
	<div class="OPPRETTB"><input type="submit" class="OPPRETTBA" value="<?php echo $this->translate('Create');?>"/></div>
</div>

<script language="javascript" type="text/javascript">
// Code For adding New Raw to For add new element
$("#clientAddInsTiltak").unbind("click").click(function () { 

	var id = $(this).data('val');
    $("#clientInsTiltakTbl").each(function () {
       
        var tds = "";
		var j = 1;
		tds += '<tr class="newEle"><td class="nonecls" colspan="2" width="15% !important"><span class="tdbg VVTAC"><div><span><?php echo $this->translate('A');?><input type="radio" id="tilinsowner'+id+j+'" value="A" name="tilinsowner['+id+']" /><label for="tilinsowner'+id+j+'"><span></span></label></span><span><?php echo $this->translate('U');?><input type="radio" value="U" id="tilinsowner'+id+(j+1)+'" name="tilinsowner['+id+']" /><label for="tilinsowner'+id+(j+1)+'"><span></span></label></span><span><?php echo $this->translate('M');?><input type="radio" value="M" id="tilinsowner'+id+(j+2)+'" name="tilinsowner['+id+']" /><label for="tilinsowner'+id+(j+2)+'"><span></span></label></span></div></span></td><td class="nonecls" width="85%"><span class="tdbg" style="width: 40% !important;"><select name="maalIds['+id+']" id="maalIds[]" class="dpdn" style="width: 99% !important;">';
		tds += '<option value=""><?php echo $this->translate('Select %s %s',$this->translate('Goal'),$this->translate('Here!'));?></option>';
		<?php foreach($this->maalCollection as $maal):?>
		tds += '<option value="<?php echo $maal['maal_id'];?>"><?php echo $maal['maal_desc'];?></option>';
		<?php endforeach;?>
		tds += '</select></span><span class="tdbg" style="width: 59% !important;float:right"><input type="text" class="dptxt" name="tilinsDescs['+id+']" id="tilinsDescs[]"/></span></td></tr>';

        if ($('tbody', this).length > 0) {
            $('tbody', this).append(tds);
        } else {
            $(this).append(tds);
        }
	});
	$(this).data('val',id+1);
		
});
// Code For Validation of form
//$.validate({
//	form : '#frmClientAddInsTiltak',
//	validateOnBlur : false,
//	borderColorOnError : '#C90312',
//	addValidClassOnAll : true,
//	showHelpOnFocus : false,
//	addSuggestions : false,
//	errorMessagePosition : 'top',
//	scrollToTopOnError : true
//});
// Code For Get Dialog on click of class dialog-ajax
$(document).ready(function(){
	$( "#frmClientAddInsTiltak" ).submit(function( event ) {
		var i=0;
		var len=$('.newEle').length;
		var k=0;
		var	flg=true;
		$('.newEle').each(function(){
			var date_fst=$(this).find('#fromDates'+i).val();
			var date_scd=$(this).find('#toDates'+i).val();
			if($(this).find(':radio:checked').is(':checked') || $(this).find('.dpdn').val()!="" || $(this).find('.dptxt').val()){
				if($(this).find(':radio:checked').is(':checked')) {
					$(this).find('.tdbg').eq(0).css('border','1px solid white');
				}else{
					$(this).find('.tdbg').eq(0).css('border','1px solid red');
					flg=false;
					return flg;
				}
				if($(this).find('.dpdn').val()!=""){
					$(this).find('.tdbg').eq(1).css('border','1px solid white');
				}else{
					$(this).find('.tdbg').eq(1).css('border','1px solid red');
					flg=false;
					return flg;
				}
				if($(this).find('.dptxt').val()!=""){
					$(this).find('.tdbg').eq(2).css('border','1px solid white');
					flg=true;
				}else{
					$(this).find('.tdbg').eq(2).css('border','1px solid red');
					flg=false;
				}
			}
			i++;

		});

		if(!flg){
			return false;
		}

//		var len=$('.newEle').length;
//		var i=0;
//		$('.newEle').each(function(){
//			if($(this).find(':radio:checked').is(':checked')) {
//				i++;
//				$(this).find('.tdbg ').css('border','1px solid white');
//			}else{
//				$(this).find('.tdbg ').css('border','1px solid red');
//			}
//		});

	});


	$('.dialog-ajax1').unbind("click").click(function(){   
		var tag = $("<div></div>"); //This tag will the hold the dialog content.
		var url = $(this).data('url');
		var title = $(this).data('title');
		$.ajax({
		  url: $(this).data('url'),
		  type: 'GET',
		  beforeSend: function() {$("#loading-image").show();},
		  error: function() { alert('Could not load form') },
		  success: function(data, textStatus, jqXHR) {
			if(typeof data == "object" && data.html) { //response is assumed to be JSON
			  tag.html(data.html).dialog({modal:true, title: title}).dialog('open');
			} else { //response is assumed to be HTML
			  tag.html(data).dialog({modal: true, title: title, height: 200, width:800, hide: "scale", show : "scale",
					open: function (event, ui) {
						var startDate = $(".DyndatepickerImage1");
						startDate.unbind();
						startDate.datepicker(Mtg.Config.Datepicker);
//						$.validate({
//							form : '#frmClientEditInsTiltak',
//							validateOnBlur : false,
//							borderColorOnError : '#C90312',
//							addValidClassOnAll : true,
//							showHelpOnFocus : false,
//							addSuggestions : false,
//							errorMessagePosition : 'top',
//							scrollToTopOnError : true
//						});
						$("#loading-image").hide();
					},
					close: function (event, ui) {
						$('input.DyndatepickerImage1').datepicker("destroy");
						$(this).dialog("destroy");
						$(this).remove();
					}
				}).dialog('open');
				
			}
		  }
		});
	  });
});
</script>
<?php if($this->isAjax):?>   
<script src="<?php echo $this->getMediaUrl('ajax-load-custom.js','js');?>" language="javascript" type="text/javascript"></script>
<?php endif;?>
</form>
</div>