<?php 
//header('Content-type: $this->mimetype');
//header('Content-type: application/pdf');
//echo $this->filecontent;

if(in_array($this->mimetype,array('image/png','image/jpg','image/jpeg','image/gif')))
{
	echo '<img src= "data:'.$this->mimetype.';base64,'.base64_encode($this->filecontent).'" />';
	//echo $this->mimetype;
}
else
{
	header('Content-type: $this->mimetype');
	if(in_array($this->mimetype,array('application/pdf')))
	{
		header('Content-type: application/pdf');
		echo $this->filecontent;
	} else {
	    header("Content-Type: application/msword");
		echo $this->filecontent;
	}
}
?>