<?php $format=KD::getModel('core/format');?>
<div class="PSUBTCWRAPPER">
	<div class="PSUBTCLEFT">
    	<?php echo $this->translate('Security Reports');?>
    </div>
</div>
<div class="CLEARBBORDER"></div>
<form name="frmClientVaktrapList" id="frmClientVaktrapList" method="post" action="<?php echo $this->getUrl("client/report");?>">
<div class="VVGBG VV2IN1C2 KRV">
 	<table width="100%" border="0" cellspacing="4" cellpadding="0">
      <tr class="CURNONPOINTER">
        <th class="TSLRTDCENTER"><?php echo $this->translate('Report');?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('Department');?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('User');?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('Measure');?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('Force');?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('Date %s',$this->translate('Start'));?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('Date %s',$this->translate('End'));?></th>
      </tr>
	  <?php
        $reportIndex = 0;

        if ($this->vaktrapportCollection instanceof Zend_Paginator) {
            $reportIndex = $this->vaktrapportCollection->getTotalItemCount() + 1;
        } else {
            $reportIndex = count($this->vaktrapportCollection) + 1;
        }

        $page = $this->page > 0 ? $this->page - 1 : 1;
        $currentIndex = ($page * $this->pageSize);
        $reportIndex = ($currentIndex >= $reportIndex || $currentIndex <= 0) ? $reportIndex : $reportIndex - $currentIndex;

      foreach($this->vaktrapportCollection as $vaktrapport):

		$tmp_vaktrap_counters = array('gov'=>0,'ins'=>0,'force'=>0,'medicine'=>0);
	  	$vaktrap_counters = (isset($vaktrapport['vaktrap_counters']) && $vaktrapport['vaktrap_counters']!='')?unserialize($vaktrapport['vaktrap_counters']):$tmp_vaktrap_counters;
        $reportIndex -= 1;
        ?>
      <tr>
        <td>
		<?php if($vaktrapport['vaktrap_status']=='yes'): 
			  	$vaktrapUrl = $this->getUrl('vaktrapport/info/index/id/'.$vaktrapport['vaktrap_id']);
			  else:
			  	$vaktrapUrl = $this->getUrl('vaktrapport/info/vaktraparchive/id/'.$vaktrapport['vaktrap_id']);
			  endif;?>
			<a href="<?php echo $vaktrapUrl;?>"><span class="tdbg"><?php echo $this->translate('No.');?>: <?php echo $reportIndex; ?></span></a></td>
        <td><span class="tdbg"><?php echo $vaktrapport['dept_name'];?></span></td>
        <td><span class="tdbg"><?php echo $format->FormatName($vaktrapport['user_fname'],$vaktrapport['user_mname'],$vaktrapport['user_lname']); ?></span></td>
        <td><span class="tdbg"><?php echo $vaktrap_counters['gov']+$vaktrap_counters['ins'];?></span></td>
		<td><span class="tdbg"><?php echo $vaktrap_counters['force'];?></span></td>
        <td><span class="tdbg"><?php echo $format->FormatDate($vaktrapport['vaktrap_from_date']); ?></span></td>
        <td><span class="tdbg"><?php echo $format->FormatDate($vaktrapport['vaktrap_to_date']); ?></span></td>
      </tr>
	  <?php endforeach;?>
    </table>
	<?php if(!($this->pageSize==1000)){echo $this->paginationControl($this->vaktrapportCollection, 'Sliding', 'control.phtml', array('page'=>'pageV','tt'=>'21'));} ?>
    <div class="KRV1C2">
        <div class="KRV1C2_1">
        	<div class="KRV1C2_11"><?php echo $this->translate('Sort');?>:</div>
        	<div class="KRV1C2_12">
                <span class="tdbgkinfo padding5">
                <select class="onSelectAction" name="selPeriod" data-form="frmClientVaktrapList">
                    <option value="<?php echo $this->getUrl('client/report/index/id/'.$this->clientID.'/period/M1');?>" <?php echo ($this->periodVaktrap=='M1')?'selected="selected"':'';?>>1 <?php echo $this->translate('Month');?></option>
                    <option value="<?php echo $this->getUrl('client/report/index/id/'.$this->clientID.'/period/M2');?>" <?php echo ($this->periodVaktrap=='M2')?'selected="selected"':'';?>>2 <?php echo $this->translate('Month');?></option>
                    <option value="<?php echo $this->getUrl('client/report/index/id/'.$this->clientID.'/period/M3');?>" <?php echo ($this->periodVaktrap=='M3')?'selected="selected"':'';?>>3 <?php echo $this->translate('Month');?></option>
                    <option value="<?php echo $this->getUrl('client/report/index/id/'.$this->clientID.'/period/M6');?>" <?php echo ($this->periodVaktrap=='M6')?'selected="selected"':'';?>>6 <?php echo $this->translate('Month');?></option>
                    <option value="<?php echo $this->getUrl('client/report/index/id/'.$this->clientID.'/period/Y1');?>" <?php echo ($this->periodVaktrap=='Y1')?'selected="selected"':'';?>>1 <?php echo $this->translate('Year');?></option>
                    <option value="<?php echo $this->getUrl('client/report/index/id/'.$this->clientID.'/period/Y2');?>" <?php echo ($this->periodVaktrap=='Y2')?'selected="selected"':'';?>>2 <?php echo $this->translate('Year');?></option>
                    <option value="<?php echo $this->getUrl('client/report/index/id/'.$this->clientID.'/period/A');?>" <?php echo ($this->periodVaktrap=='A')?'selected="selected"':'';?>><?php echo $this->translate('All');?></option>
                </select> 
                </span>
            </div>
    	</div>
    	<div class="KRV1C2_1">
        	<div class="KRV1C2_11"><?php echo $this->translate('View');?>:</div>
        	<div class="KRV1C2_12">
                <span class="tdbgkinfo padding5">
                <select class="onSelectAction" name="selPageSize" data-form="frmClientVaktrapList">
                    <option value="<?php echo $this->getUrl('client/report/index/id/'.$this->clientID.'/pgs/5');?>" <?php echo ($this->pageSize==5)?'selected="selected"':'';?>>5</option>
					<option value="<?php echo $this->getUrl('client/report/index/id/'.$this->clientID.'/pgs/10');?>" <?php echo ($this->pageSize==10)?'selected="selected"':'';?>>10</option>
                    <option value="<?php echo $this->getUrl('client/report/index/id/'.$this->clientID.'/pgs/25');?>" <?php echo ($this->pageSize==25)?'selected="selected"':'';?>>25</option>
                    <option value="<?php echo $this->getUrl('client/report/index/id/'.$this->clientID.'/pgs/50');?>" <?php echo ($this->pageSize==50)?'selected="selected"':'';?>>50</option>
                    <option value="<?php echo $this->getUrl('client/report/index/id/'.$this->clientID.'/pgs/100');?>" <?php echo ($this->pageSize==100)?'selected="selected"':'';?>>100</option>
                    <option value="<?php echo $this->getUrl('client/report/index/id/'.$this->clientID.'/pgs/1000');?>" <?php echo ($this->pageSize==1000)?'selected="selected"':'';?>><?php echo $this->translate('All');?></option>
                </select> 
                </span>
            </div>
    	</div>
    </div>
    
</div>
</form>