<?php $format=KD::getModel('core/format');?>
<div>
<form name="frmClientAddMaal" id="frmClientAddMaal" method="post" action="<?php echo $this->getUrl("client/mto/addmaal");?>">
<div class="PSUBTCWRAPPER">
	<div class="PSUBTCLEFT">
    	<?php echo $this->translate('Goal');?>
    </div>
</div>
<div class="CLEARBBORDER"></div>
<div class="KKI2C">
<table width="100%" border="0" cellspacing="4" cellpadding="0" id="clientMaalTbl">
    <thead>
	  <tr class="CURNONPOINTER">
        <th class="TSLRTDNUMBER">
        <span class="tdbg2">
        	<input type="checkbox" name="checkbox_all" id="checkbox_all" class="css-checkbox" data-form="frmClientAddMaal"/>
            <label for="checkbox_all" class="css-label"></label>
        </span>
		<input type="hidden" name="patient_id" id="patient_id" value="<?php echo $this->clientID;?>"/>
        </th>
		<th class="TSLRTDCENTER" width="65%"><?php echo $this->translate('Active %s',$this->translate('Goal'));?></th>
		<?php /*?><th class="TSLRTDCENTER" width="5%"><?php echo $this->translate('Order');?></th><?php */?>
		<th class="TSLRTDCENTER" width="15%"><?php echo $this->translate('%s Date',$this->translate('From'));?></th>
        <th class="TSLRTDCENTER" width="15%"><?php echo $this->translate('%s Date',$this->translate('To'));?></th>
		<th class="TSLRTDCENTER" width="5%"><?php echo $this->translate('Action'); ?></th>
      </tr>
	</thead>
	<?php  if(count($this->maalCollection)>0):$nyPri = 0;?>
	<tbody id="sortableMaal">
	<?php 
		foreach($this->maalCollection as $maal):  ?>
		<?php $id = $maal['maal_id']; ?>
		  <?php /*?><tr class="dropPri">
			<td colspan="5"></td>
		  </tr><?php */?>
		  <tr id="maal-<?php echo $id;?>">
			<td class="TSLRTDNUMBER bgwhite">
				<span class="tdbg" style="width: 20px;">
				<input type="checkbox" name="<?php echo 'checkbox_'.$id;?>" id="<?php echo 'checkbox_'.$id;?>" class="css-checkbox"/>
				<label for="<?php echo 'checkbox_'.$id;?>" class="css-label"></label>
				</span>
			</td>
			<td><span class="tdbg cursormove"><?php echo $maal['maal_desc']; ?></span></td>
			<?php /*?><td class="bgwhite"><span class="tdbg"><?php echo $maal['maal_order']; ?></span></td><?php */?>
			<td class="bgwhite"><span class="tdbg cursormove"><?php echo $format->FormatDate($maal['maal_from_date']); ?></span></td>
			<td class="bgwhite"><span class="tdbg cursormove" style=" <?php echo $format->getColorStyle($maal['maal_to_date']);?>" ><?php echo $format->FormatDate($maal['maal_to_date']); ?></span></td>
			<td><span class="tdbg dialog-ajax1" data-url="<?php echo $this->getUrl('client/mto/editmaal/id/'.$id);?>" data-title="<?php echo $maal['maal_desc']; ?>"><?php echo $this->translate('Edit'); ?></span></td>
		  </tr>
		
		<?php endforeach; ?>
		<?php /*?><tr class="dropPri">
			<td colspan="5"></td>
		</tr><?php */?>
	</tbody>
		<?php 
		//echo $this->paginationControl($this->maalCollection, 'Sliding', 'control.phtml', array('page'=>'pm','tt'=>'61','t'=>'6'));
	endif;?>
	
</table>
</div>

<div class="mtodroplist1">
<div class="mtodroplist11">
    <span class="KITINRDLISTWSPAN">
    	<select name="selAction" class="onSelectAction" data-form="frmClientAddMaal">
        	<option value="" style=" font-weight:bold;"><?php echo $this->translate('Select %s %s',$this->translate('Type of Action'),$this->translate('Here!'));?></option>
            <option value="<?php echo $this->getUrl('client/mto/archivemaal');?>"><?php echo $this->translate('%s %s',$this->translate('Archive'),$this->translate('Goal'));?></option>
        </select> 
    </span>  	
</div>
</div>
<div class="mtodroplist2">
	<div class="CANCELB"><a class="leggtilrada" id="clientAddMaal" data-val="1"><?php echo $this->translate('Add %s(s)',$this->translate('Row'));?></a></div>
	<div class="OPPRETTB"><input type="submit" class="OPPRETTBA" value="<?php echo $this->translate('Create');?>"/></div>
</div>

<script language="javascript" type="text/javascript">
// Code For adding New Raw to For add new element
$("#clientAddMaal").unbind("click").click(function () { 

	var id = $(this).data('val');
    $("#clientMaalTbl").each(function () {
       
        var tds = "";
		tds += '<tr>' +
            '<td class="TSLRTDNUMBER bgwhite">' +
            '<span class="tdbg" style="width: 20px;">' +
            '<label for="" class="css-label"></label>' +
            '</span>' +
        '</td>' +
        '<td class="nonecls">' +
        '<span class="tdbg">' +
        //'<input type="text" name="maalDescs[]" id="maalDescs[]" data-validation="required" />' +
        '<textarea rows="3" data-validation="required" data-error-message="Aktive Mål er påkrevd" class="width100" name="maalDescs[]" id="maalDescs[]"></textarea>' +
        '</span>' +
        '</td>' +
        '<td class="nonecls">' +
        '<span class="tdbg">' +
        '<input type="text" name="fromDates[]" data-validation="required" data-error-message="Fra Dato er påkrevd" id="fromDates'+id+'" class="DyndatepickerImage width70"/>' +
        '</span>' +
        '</td>' +
        '<td class="nonecls">' +
        '<span class="tdbg">' +
        '<input type="text" name="toDates[]" id="toDates'+id+'" class="DyndatepickerImage width70" data-validation="required" data-error-message="Til Dato er påkrevd"/>' +
        '</span>' +
        '</td>' +
        '<td class="nonecls">' +
        '<span class="tdbg">' +
        '<input type="text" name="maalOrders[]" id="maalOrders[]" class="width70"/>' +
        '</span>' +
        '</td>' +
        '</tr>';

        if ($('tbody', this).length > 0) {
            $('tbody', this).append(tds);
        } else {
            $(this).append(tds);
        }
		
		$(".DyndatepickerImage").datepicker(Mtg.Config.Datepicker);
	});
	$(this).data('val',id+1);
		
});
// Code For Validation of form
$.validate({
	form : '#frmClientAddMaal', 
	validateOnBlur : false,
	borderColorOnError : '#C90312',
	addValidClassOnAll : true,
	showHelpOnFocus : false,
	addSuggestions : false,
	errorMessagePosition : 'top',
	scrollToTopOnError : true
});
// Code For Get Dialog on click of class dialog-ajax
$(document).ready(function(){

		$( "#sortableMaal" ).sortable({
		  axis: 'y',
		  placeholder: "ui-state-highlight",
			update: function (event, ui) {
				var data = $(this).sortable('serialize');
				// POST to server using $.post or $.ajax
				$.ajax({
					data: data,
					type: 'POST',
					url: '<?php echo $this->getUrl('client/mto/updatemaalorder');?>',
					beforeSend: function(){$("#loading-image").show();},
					success: function(output) {
						//alert(output);
						$('#sortableMaal').html(output);
						$("#loading-image").hide();
					},
				  	error: function (xhr, ajaxOptions, thrownError) {
						$("#loading-image").hide();
						alert('Problem while Change Order');
				  	}
				});
			}
		});
		
		
	
	
	$('.dialog-ajax1').unbind("click").click(function(){   
		var tag = $("<div></div>"); //This tag will the hold the dialog content.
		var url = $(this).data('url');
		var title = $(this).data('title');
		$.ajax({
		  url: $(this).data('url'),
		  type: 'GET',
		  beforeSend: function() {$("#loading-image").show();},
		  error: function() { alert('Could not load form') },
		  success: function(data, textStatus, jqXHR) {
			if(typeof data == "object" && data.html) { //response is assumed to be JSON
			  tag.html(data.html).dialog({modal:true, title: title}).dialog('open');
			} else { //response is assumed to be HTML
			  tag.html(data).dialog({modal: true, title: title, height: 200, width:800, hide: "scale", show : "scale",
					open: function (event, ui) {
						var startDate = $(".DyndatepickerImage1");
						startDate.unbind();
						startDate.datepicker(Mtg.Config.Datepicker);
						$.validate({
							form : '#frmClientEditMaal', 
							validateOnBlur : false,
							borderColorOnError : '#C90312',
							addValidClassOnAll : true,
							showHelpOnFocus : false,
							addSuggestions : false,
							errorMessagePosition : 'top',
							scrollToTopOnError : true
						});
						$("#loading-image").hide();
					},
					close: function (event, ui) {
						$('input.DyndatepickerImage1').datepicker("destroy");
						$(this).dialog("destroy");
						$(this).remove();
					}
				}).dialog('open');
				
			}
		  }
		});
	  });	  
});
</script>
<?php if($this->isAjax):?>   
<script src="<?php echo $this->getMediaUrl('ajax-load-custom.js','js');?>" language="javascript" type="text/javascript"></script>
<?php endif;?>
</form>
</div>