<html lang="no">
<head>
<title>Varsling</title>
<style type="text/css">
body {margin:0px auto;padding:0px;}
.body {font-family:verdana,"Trebuchet MS";font-size:11px;background-color:#CCCCCC;color:#0077BB;}
td{font-size:12px;}
.body a {color:#fff;}
.body a:hover {text-decoration:none;}
.head {padding:5px 8px 5px; margin-bottom:10px;font-size:16px;font-weight:bold;font-family:verdana,"Trebuchet MS";color:#fff;background-color:#0077BB;}
</style>
</head>
<body>
<table width="800" border="0" align="center" cellpadding="5" cellspacing="5" class="body" style="background-color:#CCCCCC;color:#0077BB;">
  <tr>
    <td  bgcolor="#FFFFFF">
	  <table cellpadding="0" cellspacing="0" border="0" width="100%">
        <tr>
          <td class="head" style="padding:5px 8px 5px; margin-bottom:10px;font-size:16px;font-weight:bold;font-family:verdana;color:#fff;background-color:#0077BB;"> Hei <?php echo $this->data['name']; ?></td>
        </tr>
        <tr>
          <td style="background:#FFFFFF;">
		  <br><br>
			En behandler har opprettet et <b><?php echo $this->data['type']; ?></b> for klient: <b><?php echo $this->data['client']; ?></b> fra avdeling <b><?php echo $this->data['department']; ?></b> dato <b><?php echo $this->data['date']; ?></b> : kl <b><?php echo $this->data['time']; ?></b><br><br>
			Denne er blitt opprettet av <b><?php echo $this->data['user']; ?></b><br><br>
          Venligst hilsen,<br><br>
            <strong>M.T.G,<br>USE Team</strong>

		  </td>
        </tr>
      </table>
	</td>
  </tr>
</table>
</body>
</html>