<?php $format = KD::getModel('core/format');?>
<div style="display: block; padding:0 10px" id="tab11">
	<table cellpadding="4" cellspacing="0" border="0" width="100%">
	  <tr>
		<th width="5%"><?php echo $this->translate('Sr No');?></th>
		<th width="15%"><?php echo $this->translate('Lock Date');?></th>
		<th width="55%"><?php echo $this->translate('Description');?></th>
		<th width="25%"><?php echo $this->translate('Create By');?></th>
	  </tr>
	<?php $cnt = 0; foreach($this->force as $force): $cnt++;?>
	  <tr>
		<td><?php echo $cnt;?></td>
		<td><?php echo $format->FormatDate($force['force_lock_date']);?></td>
		<td><?php //echo $force['logg_desc'];?></td>
		<td><?php echo KD::getModel('user/user')->getUser($force['force_lock_by']);?></td>
	  </tr>
	<?php endforeach;?>
	</table>
</div>