<?php $format = KD::getModel('core/format');?>
<form name="frmClientAddDecision" id="frmClientAddDecision" method="post" action="<?php echo $this->getUrl("client/additional/adddecision/id/".$this->clientID);?>">
<input type="hidden" readonly name="patient_id" id="patient_id" value="<?php echo $this->clientID;?>" />
<input type="hidden" readonly name="document_type" id="document_type" value="investigation" />
<input type="hidden" name="counterStatus" id="counterStatus" value="1" />
<div>
<span id="dragandrophandler">Dra og slipp filer her for &aring; laste det inn i programmet</span>
<span id="status1"></span>
<div class="CLEARBBORDER2"></div>
</div>
<div class="clearboth">
<table width="100%" border="0">
  <tr>
	<td class="nonecls"><span class="VVTAC"><div><input type="radio" readonly id="investigation_radio_tab11" name="investigation_radio" value="investigation_neuro"/><label for="investigation_radio_tab11"><span></span></label><?php echo $this->translate('Neuro Phychologist');?></div></span></td>
	<td class="nonecls"><span class="VVTAC"><div><input type="radio" readonly id="investigation_radio_tab12" name="investigation_radio" value="investigation_hospital"/><label for="investigation_radio_tab12"><span></span></label><?php echo $this->translate('Hospital');?></div></span></td>
	<td class="nonecls"><span class="VVTAC"><div><input type="radio" readonly id="investigation_radio_tab13" name="investigation_radio" value="investigation_bup"/><label for="investigation_radio_tab13"><span></span></label><?php echo $this->translate('BUP');?></div></span></td>
	<td class="nonecls"><span class="VVTAC"><div><input type="radio" readonly id="investigation_radio_tab14" name="investigation_radio" value="investigation_ppt"/><label for="investigation_radio_tab14"><span></span></label><?php echo $this->translate('PPT');?></div></span></td>
	<td class="nonecls"><span class="VVTAC"><div><input type="radio" readonly id="investigation_radio_tab15" name="investigation_radio" value="investigation_other"/><label for="investigation_radio_tab15"><span></span></label><?php echo $this->translate('Other');?></div></span></td>
  </tr>
</table>
<div class="CLEARBBORDER2"></div>
</div>
<ul id="tabs1">
	<li class="INACTIVTAB"><a href="#" name="tab11"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Neuro Phychologist');?></div></a></li>
	<li class="INACTIVTAB"><a href="#" name="tab12"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Hospital');?></div></a></li>
	<li class="INACTIVTAB"><a href="#" name="tab13"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('BUP');?></div></a></li>
	<li class="INACTIVTAB"><a href="#" name="tab14"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('PPT');?></div></a></li>
	<li class="INACTIVTAB"><a href="#" name="tab15"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Other');?></div></a></li>
</ul>
<div id="content1">
	<div class="tablebg">
		<div style="display: block; padding:0 10px" id="tab11">
			<table cellpadding="0" cellspacing="4" border="0" width="100%">
			  <tr>
			    <th width="5%"><?php echo $this->translate('Sr No');?></th>
				<th width="55%"><?php echo $this->translate('Document');?></th>
				<th width="15%"><?php echo $this->translate('Upload date');?></th>
				<th width="25%"><?php echo $this->translate('Upload by');?></th>
			  </tr>
			<?php  $cnt = 0; foreach($this->documentNeuro as $documentNeuro): $cnt++;?>
			  <tr>
			    <td><?php echo $cnt;?></td>
				<td><?php echo $documentNeuro['document_filename'];?></td>
				<td><?php echo $format->FormatDate($documentNeuro['date_of_creation']);?></td>
				<td><?php echo KD::getModel('user/user')->getUser($documentNeuro['created_by']);?></td>
			  </tr>
			<?php endforeach;?>
			</table>
		</div>
		<div style="display: block; padding:0 10px" id="tab12">
			<table cellpadding="0" cellspacing="4" border="0" width="100%">
			  <tr>
			    <th width="5%"><?php echo $this->translate('Sr No');?></th>
				<th width="55%"><?php echo $this->translate('Document');?></th>
				<th width="15%"><?php echo $this->translate('Upload date');?></th>
				<th width="25%"><?php echo $this->translate('Upload by');?></th>
			  </tr>
			<?php  $cnt = 0; foreach($this->documentHospital as $documentHospital): $cnt++;?>
			  <tr>
			    <td><?php echo $cnt;?></td>
				<td><?php echo $documentHospital['document_filename'];?></td>
				<td><?php echo $format->FormatDate($documentHospital['date_of_creation']);?></td>
				<td><?php echo KD::getModel('user/user')->getUser($documentHospital['created_by']);?></td>
			  </tr>
			<?php endforeach;?>
			</table>
		</div>
		<div style="display: block; padding:0 10px" id="tab13">
			<table cellpadding="0" cellspacing="4" border="0" width="100%">
			  <tr>
			    <th width="5%"><?php echo $this->translate('Sr No');?></th>
				<th width="55%"><?php echo $this->translate('Document');?></th>
				<th width="15%"><?php echo $this->translate('Upload date');?></th>
				<th width="25%"><?php echo $this->translate('Upload by');?></th>
			  </tr>
			<?php  $cnt = 0; foreach($this->documentBup as $documentBup): $cnt++;?>
			  <tr>
			    <td><?php echo $cnt;?></td>
				<td><?php echo $documentBup['document_filename'];?></td>
				<td><?php echo $format->FormatDate($documentBup['date_of_creation']);?></td>
				<td><?php echo KD::getModel('user/user')->getUser($documentBup['created_by']);?></td>
			  </tr>
			<?php endforeach;?>
			</table>
		</div>
		<div style="display: block; padding:0 10px" id="tab14">
			<table cellpadding="0" cellspacing="4" border="0" width="100%">
			  <tr>
			    <th width="5%"><?php echo $this->translate('Sr No');?></th>
				<th width="55%"><?php echo $this->translate('Document');?></th>
				<th width="15%"><?php echo $this->translate('Upload date');?></th>
				<th width="25%"><?php echo $this->translate('Upload by');?></th>
			  </tr>
			<?php  $cnt = 0; foreach($this->documentPpt as $documentPpt): $cnt++;?>
			  <tr>
			    <td><?php echo $cnt;?></td>
				<td><?php echo $documentPpt['document_filename'];?></td>
				<td><?php echo $format->FormatDate($documentPpt['date_of_creation']);?></td>
				<td><?php echo KD::getModel('user/user')->getUser($documentPpt['created_by']);?></td>
			  </tr>
			<?php endforeach;?>
			</table>
		</div>
		<div style="display: block; padding:0 10px" id="tab15">
			<table cellpadding="0" cellspacing="4" border="0" width="100%">
			  <tr>
			    <th width="5%"><?php echo $this->translate('Sr No');?></th>
				<th width="55%"><?php echo $this->translate('Document');?></th>
				<th width="15%"><?php echo $this->translate('Upload date');?></th>
				<th width="25%"><?php echo $this->translate('Upload by');?></th>
			  </tr>
			<?php  $cnt = 0; foreach($this->documentOther as $documentOther): $cnt++;?>
			  <tr>
			    <td><?php echo $cnt;?></td>
				<td><?php echo $documentOther['document_filename'];?></td>
				<td><?php echo $format->FormatDate($documentOther['date_of_creation']);?></td>
				<td><?php echo KD::getModel('user/user')->getUser($documentOther['created_by']);?></td>
			  </tr>
			<?php endforeach;?>
			</table>
		</div>
	</div>
</div>
</form>
<link rel="stylesheet" href="<?php echo $this->getMediaUrl('drag-drop.css','css');?>" title="default" />
<script src="<?php echo $this->getMediaUrl('drag-drop.js','js');?>"></script>
<script language="javascript" type="text/javascript">
	$("#content1").find("[id^='tab']").hide();
	$("#tabs1 li").attr("id",""); //Reset id's
	$("#content").find("[name^='tab11']").parent().attr("id","current1");
	$("#content #tab11").fadeIn();
	$('#investigation_radio_tab11').prop("checked", true)
	
	$('#tabs1 a').click(function(e) {
        e.preventDefault();
        if ($(this).closest("li").attr("id") == "current1"){ //detection for current tab
         return;       
        }
        else{    
		  $tabname =$(this).attr('name');       
		  $('#investigation_radio_'+$tabname).prop("checked", true);
          $("#content1").find("[id^='tab']").hide(); // Hide all content
          $("#tabs1 li").attr("id",""); //Reset id's
          $(this).parent().attr("id","current1"); // Activate this
          $('#' + $(this).attr('name')).fadeIn(); // Show content for the current tab
        }
    });
</script>
<script language="javascript" type="text/javascript">
	$(document).ready(function()
		{
		var obj = $("#dragandrophandler");
		obj.on('dragenter', function (e)
		{
			e.stopPropagation();
			e.preventDefault();
			$(this).css('border', '2px solid #0B85A1');
		});
		obj.on('dragover', function (e)
		{
			 e.stopPropagation();
			 e.preventDefault();
		});
		obj.on('drop', function (e)
		{
		 
			 $(this).css('border', '2px dotted #0B85A1');
			 e.preventDefault();
			 var files = e.originalEvent.dataTransfer.files;
			
			 	var button_check = $("input[name=investigation_radio]:checked").val();
				if(button_check)
				{
					var button_type =  'investigation';
					var button_subtype = $("input[name=investigation_radio]:checked").val();
					if(button_subtype === undefined || button_subtype == null || button_subtype.length <= 0)
					{
						alert('you have not choose any category for Investigation');
						return false;
					}
					else
					{
						button_type = button_subtype;
					}
				}
				else
				{
					alert('you have not choose any category for Investigation');
					return false;
				}
			 
			 var pasientId = $('#patient_id').val();
			 if(pasientId<0)
			 {
			 	alert("System facing some problem so refresh page and wait while page fullyloaded.");
				return false;
			 }
 			 //We need to send dropped files to Server
			 handleFileUpload('<?php echo $this->getUrl('client/additional/uploadfile/id/'.$this->clientID);?>',files,obj,button_type,pasientId);
		});
		
		$(document).on('dragenter', function (e)
		{
			e.stopPropagation();
			e.preventDefault();
		});
		$(document).on('dragover', function (e)
		{
		  e.stopPropagation();
		  e.preventDefault();
		  obj.css('border', '2px dotted #0B85A1');
		});
		$(document).on('drop', function (e)
		{
			e.stopPropagation();
			e.preventDefault();
		});
		});
	</script>