<form name="frmClientAddNetwork" id="frmClientAddNetwork" method="post" action="<?php echo $this->getUrl("client/additional/networkpost/id/".$this->clientID);?>">
<input type="hidden" name="patient_id" id="patient_id" value="<?php echo $this->clientID;?>" />
<div id="network">
	<table width="100%" cellspacing="4" cellpadding="0" border="0">
        <tr>
        	<td class="nonecls bordernone"><span class="tdbg1c bordernone" style="padding:0px !important;">
						<?php echo $this->partial('partials/texteditor.phtml', [
                            'key' => 'patient_network',
                            'name' => 'network[patient_network]',
                            'content' => $this->clientInfo['patient_network'],
                            'required' => 'data-validation="required"'
                        ]); ?>
                    <?php /**
                    <div class="editor_button">
						<input onClick="createEditor('patient_network');" type="button" value="Vis editor">
						<input onClick="removeEditor('patient_network');" type="button" value="Skjul editor">
					</div>
					<table width="100%" border="0" cellspacing="0" cellpadding="0">
						<tr>
							<td class="nonecls padding5"><span class="tdbg1c" style="padding:0px !important;">
									<div id="contents_patient_network" class="padding5h">
									<textarea onkeyup="textAreaAdjust(this)" name="network[patient_network]" class="validation ckeditorClass minheight20" data-name="patient_network" data-instance="" id="editor_patient_network" data-validation="required" style="overflow:hidden;width: 100%; border: none;min-height:100px; height:auto;"><?php echo $this->clientInfo['patient_network'];?></textarea>
									</div>
								</span>
							</td>
						</tr>
					</table>
 * **/?>
            	</span>
        	</td>
        </tr>
		<tr>
        	<td class="bordernone alignleft nonecls">
				<span style="width:30px !important;" class="tdbg default-border">
					<input type="checkbox" value="yes" class="css-checkbox" <?php echo ($this->clientInfo['patient_network_check']=='yes')?'checked="checked"':'';?> id="patient_network_check" name="network[patient_network_check]">
					<label class="css-label" for="patient_network_check"></label>
				</span>
				<label class="css-label" style="padding-left: 10px;line-height:30px" for="patient_network_check">-Vis i kartleggingsmal </label>
			</td>
		</tr>
	</table>
</div>
<div class="mtodroplist2">
	<div class="OPPRETTB"><input type="submit" class="OPPRETTBA ckeditorClassSubmit" id="frmClientAddNetworkSubmit" data-form="frmClientAddNetwork"  value="<?php echo $this->translate('Save');?>"/></div>
</div>
<script type="text/javascript" language="javascript"> $.validate({
  form : '#frmClientAddNetwork', 
  validateOnBlur : false,
  borderColorOnError : '#C90312',
  addValidClassOnAll : true,
  showHelpOnFocus : false,
  addSuggestions : false,
  errorMessagePosition : 'top',
  scrollToTopOnError : true,
  ignore: '.ignore'
});
</script>
<script src="<?php echo $this->getMediaUrl('ckeditor/custom-ckeditor.js','js');?>"></script>
</form>