

<!----- File Open and Close Code ---->
<div id="PaletteAndDiagram" style="position: relative; width: 100%;">
<div id="sideBar" style="width:100%; min-height: 112px; text-align:center;padding:0px 0px;">
<div class="wrapperPR">
<div class="handle">Palett:</div>
<div id="myPalette" style="width: 100%; min-height: 70px"></div>
</div>
<div class="wrapperPR">
<div class="handle">Relasjoner</div>
<div id="myRelation" style="width: 100%; min-height: 70px"></div>
</div>
</div>
<div id="myDiagram" style="position: relative; border: solid 3px #E6E6E6; width:99%; max-height:550px; min-height:450px; padding:0px 0px; background-color:white; border-radius:3px;"></div>

<div id="customTextEditor" style="width: 85px; height: 15px; border: 1px solid black; background-color: white; visibility: visible;"></div>

</div>


