<?php $format = KD::getModel('core/format');?>
<div class="VVGBG VV2IN1C2">
<div class="printvisibeltitel">
<div class="PSUBTCLEFTH26">Aktiviteter som bare foregår enkelte ukedager</div>

</div>
<table width="100%" border="0" id="clientCertainTbl">
  <tr>
    <th class="malstyringstable"><?php echo $this->translate('Weekday');?></th>
    <th><?php echo $this->translate('Description of activities');?></th>
  </tr>
  <?php foreach($this->maalPlanCertain as $maalplancertain):?>
  <tr>
    <td class="nonecls1 width15"><span class="tdbg"><input type="text" readonly name="maalplancertain[<?php echo $maalplancertain['maalplan_other_id'];?>][maalplan_other_certainDate]" value="<?php echo $format->FormatDate($maalplancertain['maalplan_other_certainDate']);?>" class="DyndatepickerImage width70 validation"></span></td>
    <td class="nonecls1"><span class="tdbg1c"><textarea onkeyup="textAreaAdjust(this)" name="maalplancertain[<?php echo $maalplancertain['maalplan_other_id'];?>][maalplan_other_certainDesc]" style="overflow:hidden; width: 100%; border: none; height:auto;" class="validation"><?php echo $maalplancertain['maalplan_other_certainDesc'];?></textarea></span></td>
  </tr>
  <?php endforeach;?>
</table>  
	<div class="mtodroplist2">
		<div class="CANCELB"><a class="leggtilrada" id="clientAddCertain" data-val="1"><?php echo $this->translate('Add %s(s)',$this->translate('Row'));?></a></div>
	</div>
</div>
<div class="printvisibeltitel">
<div class="CLEARBBORDER2"></div>
</div>
<script language="javascript" type="text/javascript">
// Code For adding New Raw to For add new element
$("#clientAddCertain").unbind("click").click(function () { 

	var id = $(this).data('val');
    $("#clientCertainTbl").each(function () {
       
        var tds = "";
		tds += '<tr><td class="nonecls1 width15"><span class="tdbg"><input type="text" name="certain[maalplan_other_certainDate][]" readonly id="maalplan_other_certainDate'+id+'" class="DyndatepickerImage width70 validation"/></span></td><td class="nonecls1"><span class="tdbg1c"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;" name="certain[maalplan_other_certainDesc][]" id="maalplan_other_certainDesc'+id+'" class="validation"></textarea></span></td></tr>';

        if ($('tbody', this).length > 0) {
            $('tbody', this).append(tds);
        } else {
            $(this).append(tds);
        }
		
		$(".DyndatepickerImage").datepicker(Mtg.Config.Datepicker);
	});
	$(this).data('val',id+1);
		
});

</script>