<div class="PSUBTCWRAPPER">
	<div class="PSUBTCLEFT">
    	<?php echo $this->translate('Documents');?>
    </div>
</div>
<div class="CLEARBBORDER"></div>
<div class="VVGBG">
<table width="100%" border="0" cellspacing="4" cellpadding="0">
      <tr class="CURNONPOINTER">
        <td class="TSLRTDNUMBER">
        <span class="tdbg">
        	<input type="checkbox" name="checkboxG0" id="checkboxG0" class="css-checkbox" />
            <label for="checkboxG0" class="css-label"></label>
        </span>
        </td>
        <th class="TSLRTDCENTER"><strong><?php echo $this->translate('No.');?></strong></th>
        <th class="TSLRTDCENTER"><strong><?php echo $this->translate('Doc Name');?></strong></th>
        <th class="TSLRTDCENTER"><strong><?php echo $this->translate('Doc Type');?></strong></th>
        <th class="TSLRTDCENTER"><strong><?php echo $this->translate('Dato');?></strong></th>
        <th class="TSLRTDCENTER"><strong><?php echo $this->translate('Uploaded by');?></strong></th>
      </tr>

      <tr>
        <td class="TSLRTDNUMBER bgwhite">
        	<span class="tdbg" style="width: 20px;">
                <input type="checkbox" name="checkboxG1" id="checkboxG1" class="css-checkbox" />
                <label for="checkboxG1" class="css-label"></label>
       		</span>
        </td>
        
        <td class="BDTDSPACE"><span class="tdbg">12546533</span></td>
        <td class="BDTDSPACE"><span class="tdbg">Test</span></td>
        <td class="BDTDSPACE"><span class="tdbg">jpeg</span></td>
        <td class="BDTDSPACE"><span class="tdbg">04/10-2014</span></td>
        <td><span class="tdbg">Andreas Balchen</span></td>
      </tr>
    </table>
</div>