<?php 	$userCollection = $this->userCollection; 
		$formatModel = KD::getModel('core/format');
		$deptList = KD::getModel('department/department')->loadList();?>
<?php //print_r($userCollection); ?>
<div class="KKI1">
	<div class="KKI1PIC">
		<div class="KKI1PICBG">
			<div class="KKI1PH"></div>
		</div>
	</div>
	<div class="KKI1WRAPPER">
<form name="frmUpdateUser" id="frmUpdateUser" method="post" action="<?php echo $this->getUrl("user/info/index");?>">	
<?php /*?>	<div class="KKI1C">
		<div class="KKI1C1">
			<?php echo $this->translate('User Code');?>
		</div>
		<span class="tdbg888p"><input type="text" name="user_code" id="user_code"  value="<?php echo $this->userCollection['user_code'] ?>" maxlength="255" data-validation="required" data-validation-length="max255"></span>
	</div><?php */?>

    <input type="hidden" name="user_id" id="user_id" value="<?php echo $this->userCollection['user_id'] ?>">	
	

	<div class="KKI1C">
		<div class="KKI1C1">
			<?php echo $this->translate('First Name');?>
		</div>
		<span class="tdbg888p"><input type="text" name="user_fname" id="user_fname"  value="<?php echo $this->userCollection['user_fname'] ?>" maxlength="255" data-validation="required" data-validation-length="max255"></span>

	</div>
	<div class="KKI1C">
		<div class="KKI1C1">
			<?php echo $this->translate('Middle Name');?>
		</div>
		<span class="tdbg888p"><input type="text" name="user_mname" id="user_mname"  value="<?php echo $this->userCollection['user_mname'] ?>" maxlength="255" data-validation="required" data-validation-length="max255"></span>
	</div>
	<div class="KKI1C">
		<div class="KKI1C1">
			<?php echo $this->translate('Last Name');?>
		</div>
		<span class="tdbg888p"><input type="text" name="user_lname" id="user_lname"  value="<?php echo $this->userCollection['user_lname'] ?>" maxlength="255" data-validation="required" data-validation-length="max255"></span>
    </div>
	<div class="KKI1C">
		<div class="KKI1C1">
			<?php echo $this->translate('Position');?>
		</div>
		<span class="tdbg888p"><input type="text" name="user_position" id="user_position"  value="<?php echo $this->userCollection['user_position'] ?>" maxlength="255" data-validation="required" data-validation-length="max255"></span>
	</div>
	<div class="KKI1C">
		<div class="KKI1C1">
			<?php echo $this->translate('Join').' ('.$this->translate('Date').')';?>
		</div>
		<span class="tdbg888p"><input type="text" name="user_date_joining" id="user_date_joining" class="datepickerMinToday disabled" readonly value="<?php echo $formatModel->FormatDate($this->userCollection['user_date_joining']);?>" maxlength="255" data-validation="required" data-validation-length="max255"></span>
	</div>
	<div class="KKI1C">
		<div class="KKI1C1">
			<?php echo $this->translate('Department');?>
		</div>
		<span class="tdbg888p">
			<select name="user_deptid" id="user_deptid" data-validation="required">
				<option value="">Kontoret</option>
				<?php foreach($deptList as $key=>$department):?>
				<option value="<?php echo $department['dept_id'];?>" <?php echo ($this->userCollection['user_deptid']==$department['dept_id'])?'selected="selected"':'';?>><?php echo $department['dept_name'];?></option>
				<?php endforeach;?>
            </select> 
        </span>
	</div>
	<div class="KKI1C">
		<div class="KKI1C1">
			<?php echo $this->translate('ID');?>
		</div>
		<span class="tdbg888p"><input type="text" name="user_code" id="user_code"  value="<?php echo $this->userCollection['user_code'] ?>" maxlength="255" data-validation="required" data-validation-length="max255"></span>
	</div>	
	<div class="KKI1C">
		<div class="KKI1C1">
			<?php echo $this->translate('Phone');?>
		</div>
		<span class="tdbg888p"><input type="text" name="user_phone" id="user_phone"  value="<?php echo $this->userCollection['user_phone'] ?>" maxlength="255" data-validation="required" data-validation-length="max255"></span>
	</div>
	<div class="KKI1C">
		<div class="KKI1C1">
			<?php echo $this->translate('Mobile');?>
		</div>
		<span class="tdbg888p"><input type="text" name="user_mobile" id="user_mobile"  value="<?php echo $this->userCollection['user_mobile'] ?>" maxlength="255" data-validation="required" data-validation-length="max255"></span>
	</div>
	<div class="KKI1C">
		<div class="KKI1C1">
			<?php echo $this->translate('Email');?>
		</div>
		<span class="tdbg888p"><input type="text" name="user_email" id="user_email"  value="<?php echo $this->userCollection['user_email'] ?>" maxlength="255"  data-validation="email" data-validation-length="max255"></span>
	</div>
	<div class="OPPRETTB"><input type="submit" class="OPPRETTBA" value="<?php echo $this->translate('Create');?>"></div>
</form>	
</div>
</div>

<?php /*?><div class="LAGREB2"><a class="LAGREBA2" href="#"><?php echo $this->translate('Save');?></a></div><?php */?>

