<?php
$user_id=$this->userCollection['user_id'];
$session = new Zend_Session_Namespace('Acl');
$session_details=$session->getIterator();


$btnFlag=false;

if(isset($session->userRole) && in_array($session->userRole,array('A','S')) || $user_id==$session_details['userID'])
{
    $btnFlag=true;
}
?>

<div class="PSUBTCWRAPPER">
	<div class="PSUBTCLEFT">
    	<?php echo $this->translate('Relatives');?>
    </div>
</div>
<div class="CLEARBBORDER"></div>
<form name="frmUpdateUserRelatives" id="frmUpdateUserRelatives" method="post" action="<?php echo $this->getUrl("user/info/index");?>">
<input type="hidden" name="user_id" id="user_id" value="<?php echo $this->userCollection['user_id'] ?>" >
<input type="hidden" name="user_code" id="user_code" value="<?php echo $this->userCollection['user_code'] ?>" >
<div class="KKI2C">
        <table width="100%" border="0" cellspacing="4" cellpadding="0">
            
            <tr>
                <td><span class="tdbg1c">
                        <textarea onkeyup="textAreaAdjust(this)" name="user_relatives" id="user_relatives" data-error-message="Pårørende er påkrevd" data-validation="required" style="overflow:hidden;width: 100%; border: none; height:auto;"><?php echo $this->userCollection['user_relatives'] ?></textarea>
                    </span>
                </td>
            </tr>
		</table> 
    </div>
<?php if($btnFlag):?>

<div class="CANCELB"><a class="CANCELBA" href="#"><?php echo $this->translate('Cancel');?></a></div>
<?php /*?><div class="LAGREB2"><a class="LAGREBA2" href="#"><?php echo $this->translate('Save');?></a></div><?php */?>
<div class="OPPRETTB"><input type="submit" class="OPPRETTBA" value="<?php echo $this->translate('Save');?>"></div>
<?php endif;?>
</form>
