<?php $format = KD::getModel('core/format');?>
<form name="clientArchiveList" id="clientArchiveList" action="" method="post">
<table width="100%" border="0" cellspacing="4" cellpadding="0">
  <tr class="CURNONPOINTER">
	<th class="TSLRTDNUMBER">
	<span class="tdbg2">
		<input type="checkbox" name="checkbox_all1" id="checkbox_all1" class="css-checkbox"  data-form="clientArchiveList"/>
		<label for="checkbox_all1" class="css-label"></label>
	</span>
	</td>
	<th class="TSLRTDCENTER"><?php echo $this->translate('Name');?></th>
	<th class="TSLRTDCENTER"><?php echo $this->translate('ODA No');?></th>
	<th class="TSLRTDCENTER"><?php echo $this->translate('Department');?></th>
	<th class="TSLRTDCENTER"><?php echo $this->translate('Date of Join');?></th>
  </tr>

<?php  if(count($this->clientArchiveCollection)>0):
foreach($this->clientArchiveCollection as $client): ?>
<?php $id = $client['patient_id']; ?>
  <tr>
	<td class="TSLRTDNUMBER">
		<span class="tdbg" style="width: 20px;">
		<input type="checkbox" name="<?php echo 'checkbox_'.$id;?>" id="<?php echo 'checkbox_'.$id;?>" class="css-checkbox" />
		<label for="<?php echo 'checkbox_'.$id;?>" class="css-label"></label>
		</span>
	</td>
	<td><span class="tdbg"><a href="<?php echo $this->getUrl('client/info/index/id/'.$id,null,false,false);?>"><?php echo $format->FormatName($client['patient_fname'],$client['patient_mname'],$client['patient_lname']); ?></a></span></td>
	<td><span class="tdbg"><?php echo $client['patient_person_no'] ?></span></td>
	<td><span class="tdbg"><?php echo $client['dept_name'] ?></span></td>
	<td><span class="tdbg"><?php echo $format->FormatDate($client['patient_date_of_joining']); ?></span></td>
  </tr>

<?php endforeach; 
endif;?>
<?php echo $this->paginationControl($this->clientArchiveCollection, 'Sliding', 'control.phtml', array('page'=>'pageCA','tab'=>'tab2')); ?>
</table>
<div class="listdroplist">
	<div class="PSUBTCLEFT"><?php echo $this->translate('Select %s',$this->translate('Type of Action'));?></div>
	<div class="KITINRDLISTW">
		<span class="KITINRDLISTWSPAN">
			<select name="selAction" class="onSelectAction" data-form="clientArchiveList">
				<option value=""><?php echo $this->translate('Select %s %s',$this->translate('Type of Action'),$this->translate('Here!'));?></option>
				<option value="<?php echo $this->getUrl('client/index/restore');?>"><?php echo $this->translate('Restore');?></option>
				<option value="<?php echo $this->getUrl('client/index/delete');?>"><?php echo $this->translate('Delete');?></option>
			</select> 
		</span>  	
	</div>
</div>
</form>