<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>M.T.G.- Index<?php //echo $title; ?></title>
  <?php //echo $this->headLink()->appendStylesheet('/zend/css/global.css') ?>
  <?php //include 'head.phhml';?>
  <?php echo $this->render('head.phtml')?>
</head>
<body oncontextmenu="return false;">
<?php echo $this->render('left.phtml')?>
<div id="CONTENT">
	<?php echo $this->render('mainmenu.phtml');?>
	<div id="NEWSW" class="CFULWRAPPER">
		<div id="content">
			<?php //echo $this->layout()->content ?>
			<?php echo $this->render('ledelsen.phtml');?>
			<?php echo $this->render('notepad.phtml');?>
		</div>	
    </div>
	<?php /*?><div class="CFULWRAPPER">
        <div id="CIDWRAPPER">
            <div id="CIDCENTERBG">
				<div id="PTCWRAPPER">
                    <div id="PTCLEFT">DATA</div>
                    <div id="PTCRIGHT"> 
                        <a class="PRINTBUTTON" href="#" title="Logg ut"></a>
                    </div>
                </div>
            	<div class="CLEARBBORDER"></div>
                <div id="BORDERTABS">					
					<?php 
					
					echo $this->render('tabs.phtml');?>
					<div id="content">
					<?php echo $this->layout()->content ?>
					</div>
					<div class="bot_shadow"></div>
				</div>
			</div>
        </div>   	
    </div><?php */?>
	<?php echo $this->render('footer.phtml');?>
</div>
<script src="<?php echo $this->getMediaUrl('custom/loader-1.js','js');?>"></script>
<script src="<?php echo $this->getMediaUrl('custom/loader-2.js','js');?>"></script>
<script src="<?php echo $this->getMediaUrl('custom/loader-3.js','js');?>"></script>
</body>
</html>
</body>
</html>
