<div id="LEFT" style="display:none">
	<div id="LOGO">
    	<img class="LOGO" src="<?php echo $this->getMediaUrl('timg/logo.png');?>" width="219" height="102" alt="<?php echo $this->translate('The Treatment center Small Devices');?>"/>
    </div>
	<?php echo $this->render('modules/left/user/user.phtml');?>
    <?php echo $this->render('modules/left/search/search.phtml');?>
    <?php echo $this->render('modules/left/calendar/calendar.phtml');?>
    <p class="copirett"><br /><br />&copy; Copyright 2013 - <?php echo date("Y") ?> <a class="copirl" href="http://www.inocurea.no" target="new">Inocurea AS</a></p>
    <p class="copirett">Utvikling, drift og support: <a class="copirl" href="<?php echo $this->getMediaUrl('support/TeamViewer-webtechit.exe');?>" target="new">Webtech IT AS</a></p> 
</div>