<div class="VVGBG VV2IN1C2">
<table width="100%" border="0">
  <tr>
    <th style="width:150px;"><?php echo $this->translate('Date');?></th>
    <th><?php echo $this->translate('Meeting with whom?');?></th>
  </tr>
  <tr>
    <td class="bgwhite"><span class="tdbg"><input type="text" value="03/07-2014"></span></td>
    <td>
    <span class="tdbg1c">
    	<textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea>
    </span>
    </td>
  </tr>
  <tr>
    <td class="bgwhite"><span class="tdbg"><input type="text" value="03/07-2014"></span></td>
    <td>
    <span class="tdbg1c">
    	<textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea>
    </span>
    </td>
  </tr>
  <tr>
    <td class="bgwhite"><span class="tdbg"><input type="text" value="03/07-2014"></span></td>
    <td>
    <span class="tdbg1c">
    	<textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea>
    </span>
    </td>
  </tr>
  <tr>
    <td class="bgwhite"><span class="tdbg"><input type="text" value="03/07-2014"></span></td>
    <td>
    <span class="tdbg1c">
    	<textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea>
    </span>
    </td>
  </tr>
  <tr>
    <td class="bgwhite"><span class="tdbg"><input type="text" value="03/07-2014"></span></td>
    <td>
    <span class="tdbg1c">
    	<textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea>
    </span>
    </td>
  </tr>
  <tr class="bgwhite">
    <td><span class="tdbg"><input type="text" value="03/07-2014"></span></td>
    <td>
    <span class="tdbg1c">
    	<textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea>
    </span>
    </td>
  </tr>
  <tr>
    <td class="bgwhite"><span class="tdbg"><input type="text" value="03/07-2014"></span></td>
    <td>
    <span class="tdbg1c">
    	<textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea>
    </span>
    </td>
  </tr>
</table>
</div>
