<div class="VVGBG VV2IN1C2">
<table width="100%" border="0">
  <tr>
    <th class="malstyringstable"><?php echo $this->translate('Weekday');?></th>
    <th><?php echo $this->translate('Description of activities');?></th>
  </tr>
  <tr>
    <td class="malstyringstable"><?php echo $this->translate('Monday');?></td>
    <td>
    <span class="tdbg1c">
    	<textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea>
    </span>
    </td>
  </tr>
  <tr>
    <td class="malstyringstable"><?php echo $this->translate('Tuesday');?></td>
    <td>
    <span class="tdbg1c">
    	<textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea>
    </span>
    </td>
  </tr>
  <tr>
    <td class="malstyringstable"><?php echo $this->translate('Wednesday');?></td>
    <td>
    <span class="tdbg1c">
    	<textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea>
    </span>
    </td>
  </tr>
  <tr>
    <td class="malstyringstable"><?php echo $this->translate('Thursday');?></td>
    <td>
    <span class="tdbg1c">
    	<textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea>
    </span>
    </td>
  </tr>
  <tr>
    <td class="malstyringstable"><?php echo $this->translate('Friday');?></td>
    <td>
    <span class="tdbg1c">
    	<textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea>
    </span>
    </td>
  </tr>
  <tr>
    <td class="malstyringstable"><?php echo $this->translate('Saturday');?></td>
    <td>
    <span class="tdbg1c">
    	<textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea>
    </span>
    </td>
  </tr>
  <tr>
    <td class="malstyringstable"><?php echo $this->translate('Sunday');?></td>
    <td>
    <span class="tdbg1c">
    	<textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea>
    </span>
    </td>
  </tr>
</table>
</div>
