<div class="VVGBG VV2IN1C2">
<table width="100%" border="0">
  <tr>
    <th width="50%"><?php echo $this->translate('Description of activities');?></th>
    <th width="50%"><?php echo $this->translate('When / how often');?></th>
  </tr>
  <tr>
    <td><span class="tdbg985p"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea></span></td>
    <td><span class="tdbg985p"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea></span></span></td>
  </tr>
  <tr>
    <td><span class="tdbg985p"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea></span></span></td>
    <td><span class="tdbg985p"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea></span></td>
  </tr>
  <tr>
    <td><span class="tdbg985p"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea></span></td>
    <td><span class="tdbg985p"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea></span></td>
  </tr>
  <tr>
    <td><span class="tdbg985p"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea></span></td>
    <td><span class="tdbg985p"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea></span></td>
  </tr>
  <tr>
    <td><span class="tdbg985p"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea></span></td>
    <td><span class="tdbg985p"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden; width: 100%; border: none; height:auto;"></textarea></span></td>
  </tr>
</table>
</div>