<div class="tablebg">
   <div style="display: block; padding:0 10px" id="tab1">
  	<?php echo $this->partial('month/tabs/showQuarterlySecurityReport.phtml',array('vaktrapInfo'=>$this->vaktrapInfo,'clientInfo'=>$this->clientInfo,'maalCollection'=>$this->maalCollection,'instTiltakCollection'=>$this->instTiltakCollection,'vakGovTiltakCollection'=>$this->vakGovTiltakCollection,'instTiltakCountCollection'=>$this->instTiltakCountCollection,'govTiltakCountCollection'=>$this->govTiltakCountCollection,'observationCollection'=>$this->observationCollection,'observationAllData'=>$this->observationAllData,'observations'=>$this->observations,'startDate'=>$this->startDate,'endDate'=>$this->endDate));?>
   </div>
</div>