<div class="tablebg">
   <div style="display: block; padding:0 10px" id="tab1">
  	<?php echo $this->partial('month/tabs/showarchiveQuarterlySecurityReport.phtml',array('vaktrapInfo'=>$this->vaktrapInfo,'clientInfo'=>$this->clientInfo,'maalCollection'=>$this->maalCollection,'instTiltakCollection'=>$this->instTiltakCollection,'vakGovTiltakCollection'=>$this->vakGovTiltakCollection,'instTiltakCountCollection'=>$this->instTiltakCountCollection,'govTiltakCountCollection'=>$this->govTiltakCountCollection));?>
   </div>
</div>