<div class="PSUBTCLEFTH2"><?php echo $this->translate('Mapping Template');?></div>

<div class="VVGBG"><br /><br /><br /><br /><br /><br /><br /><br /><br /></div>
<div class="CLEARBBORDER2"></div>
    <div class="KKI2C">
        <table width="100%" border="0" cellspacing="4" cellpadding="0">
            <tr>
                <th class="noborder"><?php echo $this->translate('Reason for placement');?> - <?php echo $this->translate('Description');?></th>
            </tr>
            <tr>
                <td><span class="tdbg1c">
                        <textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;"></textarea>
                    </span>
                </td>
            </tr>
		</table> 
    </div>
<div class="CLEARBBORDER2"></div>
<div class="KKI2C">
<table width="100%" border="0" cellspacing="4" cellpadding="0">
      <tr class="CURNONPOINTER">
        <th class="TSLRTDNUMBER">
        <span class="tdbg92pborder" style="width: 20px;">
                <input type="checkbox" name="checkboxG0" id="checkboxG0" class="css-checkbox" />
                <label for="checkboxG0" class="css-label"></label>
       		</span>
        </th>
        <th class="TSLRTDCENTER">Akt&oslash;rens &oslash;nskede resultat av behandlingen</th>
        <th class="TSLRTDCENTER">&Oslash;nsket resultat av behandlingen fra involverte parter <br />Birdrar til utformingen av felles m&aring;l</th>
      </tr>
      <tr>
        <td class="TSLRTDNUMBER bgwhite">
        	<span class="tdbg" style="width: 20px;">
                <input type="checkbox" name="checkboxG1" id="checkboxG1" class="css-checkbox" />
                <label for="checkboxG1" class="css-label"></label>
       		</span>
        </td>
        <td><span class="tdbg985p"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;"></textarea></span></td>
        <td><span class="tdbg985p"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;"></textarea></span></td>
      </tr>
</table>
<div class="slettrad"><a class="slettrada" href="#"><?php echo $this->translate('Delete %s(s)',$this->translate('Row'));?></a></div>
<div class="leggtilrad"><a class="leggtilrada" href="#"><?php echo $this->translate('Add %s(s)',$this->translate('Row'));?></a></div>
</div>
<div class="CLEARBBORDER2"></div>

<div class="KKI2C"><strong>Systemets resurser og utfordringer</strong><br />"Resurser" f&oslash;res inn i M&aring;lstringsplanen. "Utfordringer" bidrar til utforming av nye m&aring;l.</div>
<div class="CLEARBBORDER2"></div>
<div class="KKI2C">
<table width="100%" border="0" cellspacing="4" cellpadding="0">
      <tr class="CURNONPOINTER">
        <th class="TSLRTDNUMBER">
        <span class="tdbg92pborder" style="width: 20px;">
                <input type="checkbox" name="checkboxG3" id="checkboxG3" class="css-checkbox" />
                <label for="checkboxG3" class="css-label"></label>
       		</span>
        </th>
        <th class="TSLRTDCENTER" width="33%">Akt&oslash;rens beskrivelser av ressurser og utfordringer</th>
        <th class="TSLRTDCENTER" width="33%">Resurser (styrker)</th>
        <th class="TSLRTDCENTER" width="33%">Utfordringer (problemer, svakheter)</th>
      </tr>
      <tr>
        <td class="TSLRTDNUMBER bgwhite">
        	<span class="tdbg" style="width: 20px;">
                <input type="checkbox" name="checkboxG4" id="checkboxG4" class="css-checkbox" />
                <label for="checkboxG4" class="css-label"></label>
       		</span>
        </td>
        <td><span class="tdbg2c"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;"></textarea></span></td>
        <td><span class="tdbg2c"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;"></textarea></span></td>
        <td><span class="tdbg2c"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;"></textarea></span></td>
      </tr>
</table>
<div class="slettrad"><a class="slettrada" href="#"><?php echo $this->translate('Delete %s(s)',$this->translate('Row'));?></a></div>
<div class="leggtilrad"><a class="leggtilrada" href="#"><?php echo $this->translate('Add %s(s)',$this->translate('Row'));?></a></div>
</div>

<div class="CANCELB"><a class="CANCELBA" href="#"><?php echo $this->translate('Cancel');?></a></div>
<div class="LAGREB2"><a class="LAGREBA2" href="#"><?php echo $this->translate('Save');?></a></div>