<div class="PSUBTCWRAPPER">
	<div class="PSUBTCLEFTH2"><?php echo $this->translate('M.T.O');?></div>
    <div class="KITITWRAPPER">
    	<div class="PSUBTCLEFT"><?php echo $this->translate('%s Type',$this->translate('M.T.O'));?>:</div>
        <div class="KITINRDLISTW">
        	<span class="KITINRDLISTWSPAN">
            	<select>
                	<option value="0"><?php echo $this->translate('Goal');?></option>
                    <option value="1"><?php echo $this->translate('Measure');?></option>
                    <option value="2"><?php echo $this->translate('Observations');?></option>
				</select> 
			</span>  	
		</div>
	</div>
	<div class="CLEARBBORDER4"></div>
	<!-- OPPTION 1 -->  
	<div class="KKI2C">

	<div id="BORDERTABS1R">
     	<ul id="tabs6">
        	<li class="INACTIVTAB" id="current6"><a href="#" name="tab61"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Goal');?></div></a></li>
            <li class="INACTIVTAB"><a href="#" name="tab62"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('%s %s',$this->translate('Completed'),$this->translate('Goal'));?></div></a></li>
            <li class="INACTIVTAB"><a href="#" name="tab63"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Archived %s',$this->translate('Goal'));?></div></a></li>
		</ul>
		<div id="content6">
			<div class="tablebg">
				<div style="display: block; padding:0 10px" id="tab61">
                	<?php echo $this->partial('info/tabs/mto/clientActiveGoal.phtml');?>
                </div>
                <div style="display: block; padding:0 10px" id="tab62">
                	<?php echo $this->partial('info/tabs/mto/clientCompleteGoal.phtml');?>
				</div>
                <div style="display: block; padding:0 10px" id="tab63">
                	<?php echo $this->partial('info/tabs/mto/clientAchivedGoal.phtml');?>
				</div>
			</div>
		</div>
		<div class="bot_shadow"><img src="<?php echo $this->getMediaUrl('timg/bot-shadow.png');?>" width="834" height="21"></div>
	</div>    
    </div>
</div>