<div class="PSUBTCLEFTH2"><?php echo $this->translate('Statistic');?></div>

<div class="KKI2C">
<div class="statistikkcon1">
	<div class="statistikkcon1_1"><?php echo $this->translate('From and To Date:');?> 01/04-2014 - 01/04-2015</div>
    
    <div class="statistikkcon1_2">
    	<div class="statistikkcon1_21"></div>
        <div><?php echo $this->translate('Completed');?></div>
    </div>
    <div class="statistikkcon1_3">
    	<div class="statistikkcon1_31"></div>
        <div><?php echo $this->translate('Partial Complete');?></div>
    </div>
    <div class="statistikkcon1_4">
    	<div class="statistikkcon1_41"></div>
        <div><?php echo $this->translate('Not Complete');?></div>
    </div>
</div>
</div>

<div class="CLEARBBORDER2"></div>

<div class="KKI2C">
<div class="statistikkcon2">
	<div class="statistikkcon2_1">
        <div class="statistikkcon2_11"></div>
        <div class="statistikkcon2_12">
        	<table width="100%" border="0">
  <tr>
    <th class="w150025p"><?php echo $this->translate('Goal');?></th>
    <th class="w150025p"><?php echo $this->translate('Completed');?></th>
    <th class="w150025p"><?php echo $this->translate('Partial Complete');?></th>
    <th class="w150025p"><?php echo $this->translate('Not Complete');?></th>
  </tr>
  <tr>
    <td><span class="tdbg"><input type="text" value="4"></span></td>
    <td><span class="tdbg"><input type="text" value="6"></span></td>
    <td><span class="tdbg"><input type="text" value="6"></span></td>
    <td><span class="tdbg"><input type="text" value="1"></span></td>
  </tr>
</table>
        </div>
    </div>
    <div class="statistikkcon2_2">
        <div class="statistikkcon2_11"></div>
        <div class="statistikkcon2_12">
        	<table width="100%" border="0">
  <tr>
    <th><?php echo $this->translate('Ongoing Measure');?></th>
    <th><?php echo $this->translate('Completed');?></th>
    <th><?php echo $this->translate('Partial Complete');?></th>
    <th><?php echo $this->translate('Not Complete');?></th>
  </tr>
  <tr>
    <td><span class="tdbg"><input type="text" value="4"></span></td>
    <td><span class="tdbg"><input type="text" value="6"></span></td>
    <td><span class="tdbg"><input type="text" value="6"></span></td>
    <td><span class="tdbg"><input type="text" value="1"></span></td>
  </tr>
</table>
        </div>
    </div>
    <div class="statistikkcon2_3">
        <div class="statistikkcon2_11"></div>
        <div class="statistikkcon2_12">
        	<table width="100%" border="0">
  <tr>
    <th><?php echo $this->translate('Short Measure');?></th>
    <th><?php echo $this->translate('Completed');?></th>
    <th><?php echo $this->translate('Partial Complete');?></th>
    <th><?php echo $this->translate('Not Complete');?></th>
  </tr>
  <tr>
    <td><span class="tdbg"><input type="text" value="4"></span></td>
    <td><span class="tdbg"><input type="text" value="6"></span></td>
    <td><span class="tdbg"><input type="text" value="6"></span></td>
    <td><span class="tdbg"><input type="text" value="1"></span></td>
  </tr>
</table>
        </div>
    </div>  
</div>
</div>

<div class="CLEARBBORDER2"></div>

<div class="KKI2C statistikkcon3">	

    <div class="statistikkcon3_1">
    	<div class="KKI2C"><?php echo $this->translate('All observations in graph');?></div>
        <div class="statistikkcon3_12"></div>
    </div>
    
    <div class="statistikkcon3_2">
    	<div class="KKI2C1"><?php echo $this->translate('All observations in list');?></div>
    	
        <div class="statistikkcon3_31">
            <div class="statistikkcon3_41"></div>
            <div>Pusse tennene</div>
        </div>
        
        <div class="statistikkcon3_32">
            <div class="statistikkcon3_42"></div>
            <div>Vaske romm</div>
        </div>
        
        <div class="statistikkcon3_33">
            <div class="statistikkcon3_43"></div>
            <div>Selvskading</div>
        </div>
        
    </div>
</div>

<div class="CLEARBBORDER2"></div>

<div class="KKI2C statistikkcon3">	

    <div class="statistikkcon3_1">
    	<div class="KKI2C"><div class="statistikkcon3_41"></div><div><?php echo $this->translate('Graph');?></div></div>
        <div class="statistikkcon3_12"></div>
    </div>
    
    <div class="statistikkcon3_2">
    	<div class="KKI2C1"><div class="statistikkcon3_41"></div><div><?php echo $this->translate('List Information');?></div></div>
    	
        <div class="statistikkcon3_31">
            <div><?php echo $this->translate('Period');?>: 01/01-2013 - 10/01-2014</div>
        </div>
        
        <div class="statistikkcon3_32">
            <div><?php echo $this->translate('Total Remarks');?>: 20</div>
        </div>
        
    </div>
</div>

<div class="CLEARBBORDER2"></div>

<div class="KKI2C statistikkcon3">	

    <div class="statistikkcon3_1">
    	<div class="KKI2C"><div class="statistikkcon3_42"></div><div>Vaske romm <?php echo $this->translate('Graph');?></div></div>
        <div class="statistikkcon3_12"></div>
    </div>
    
    <div class="statistikkcon3_2">
    	<div class="KKI2C1"><div class="statistikkcon3_42"></div><div>Vaske romm <?php echo $this->translate('List Information');?></div></div>
    	
        <div class="statistikkcon3_31">
            <div><?php echo $this->translate('Period');?>: 01/01-2013 - 10/01-2014</div>
        </div>
        
        <div class="statistikkcon3_32">
            <div><?php echo $this->translate('Total Remarks');?>: 20</div>
        </div>
        
    </div>
</div>


	

    









