<div class="PSUBTCLEFTH2"><?php echo $this->translate('Reports');?></div>
<div id="BORDERTABS1R">
	<ul id="tabs2">
		<li class="INACTIVTAB" id="current2"><a href="#" name="tab21"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Security Reports');?></div></a></li>
		<li class="INACTIVTAB"><a href="#" name="tab22"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Quarterly Report');?></div></a></li>
		<li class="INACTIVTAB"><a href="#" name="tab23"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Monthly Summary');?></div></a></li>
		<li class="INACTIVTAB"><a href="#" name="tab24"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Quarterly Summary');?></div></a></li>
	</ul>
	<div id="content2">
		<div class="tablebg">
			<div style="display: block; padding:0 10px" id="tab21">
				<?php echo $this->partial('info/tabs/reports/clientSecurityReports.phtml');?>
			</div>
			<div style="display: block; padding:0 10px" id="tab22">
				<?php echo $this->partial('info/tabs/reports/clientQuarterlyReports.phtml');?>
			</div>
			<div style="display: block; padding:0 10px" id="tab23">
				<?php echo $this->partial('info/tabs/reports/clientMonthlySummery.phtml');?>
			</div>
			<div style="display: block; padding:0 10px" id="tab24">
				<?php echo $this->partial('info/tabs/reports/clientQuarterlySummery.phtml');?>
			</div>
		</div>
	</div>
	<div class="bot_shadow"><img src="<?php echo $this->getMediaUrl('timg/bot-shadow.png');?>" width="834" height="21"></div>
</div> 