<table width="100%" border="0" cellspacing="4" cellpadding="0">
  <tr class="CURNONPOINTER">
	<th class="TSLRTDNUMBER">
	<span class="tdbg2">
		<input type="checkbox" name="checkboxG0" id="checkboxG0" class="css-checkbox" />
		<label for="checkboxG0" class="css-label"></label>
	</span>
	</td>
	<th class="TSLRTDCENTER"><?php echo $this->translate('Name');?></th>
	<th class="TSLRTDCENTER"><?php echo $this->translate('ODA No');?></th>
	<th class="TSLRTDCENTER"><?php echo $this->translate('Department');?></th>
	<th class="TSLRTDCENTER"><?php echo $this->translate('Date of Join');?></th>
  </tr>

  <tr>
	<td class="TSLRTDNUMBER">
		<span class="tdbg" style="width: 20px;">
			<input type="checkbox" name="checkboxG1" id="checkboxG1" class="css-checkbox" />
			<label for="checkboxG1" class="css-label"></label>
		</span>
	</td>
	<td><span class="tdbg"><a href="<?php echo $this->getUrl('client/info');?>">Payam Afshar</a></span></td>
	<td><span class="tdbg">223355445</span></td>
	<td><span class="tdbg">Webtech IT As</span></td>
	<td><span class="tdbg">01.05.2014</span></td>
  </tr>
  <tr>
	<td class="TSLRTDNUMBER">
		<span class="tdbg" style="width: 20px;">
		<input type="checkbox" name="checkboxG2" id="checkboxG2" class="css-checkbox" />
		<label for="checkboxG2" class="css-label"></label>
		</span>
	</td>
	<td><span class="tdbg"><a href="<?php echo $this->getUrl('client/info');?>">Payam Afshar</a></span></td>
	<td><span class="tdbg">223355445</span></td>
	<td><span class="tdbg">Webtech IT As</span></td>
	<td><span class="tdbg">01.05.2014</span></td>
  </tr>
   <tr>
	<td class="TSLRTDNUMBER">
		<span class="tdbg" style="width: 20px;">
		<input type="checkbox" name="checkboxG3" id="checkboxG3" class="css-checkbox" />
		<label for="checkboxG3" class="css-label"></label>
		</span>
	</td>
	<td><span class="tdbg"><a href="<?php echo $this->getUrl('client/info');?>">Payam Afshar</a></span></td>
	<td><span class="tdbg">223355445</span></td>
	<td><span class="tdbg">Webtech IT As</span></td>
	<td><span class="tdbg">01.05.2014</span></td>
  </tr>
   <tr>
	<td class="TSLRTDNUMBER">
		<span class="tdbg" style="width: 20px;">
		<input type="checkbox" name="checkboxG4" id="checkboxG4" class="css-checkbox" />
		<label for="checkboxG4" class="css-label"></label>
		</span>
	</td>
	<td><span class="tdbg"><a href="<?php echo $this->getUrl('client/info');?>">Payam Afshar</a></span></td>
	<td><span class="tdbg">223355445</span></td>
	<td><span class="tdbg">Webtech IT As</span></td>
	<td><span class="tdbg">01.05.2014</span></td>
  </tr>
</table>
<div class="listdroplist">
	<div class="PSUBTCLEFT"><?php echo $this->translate('Select %s',$this->translate('Type of Action'));?></div>
	<div class="KITINRDLISTW">
		<span class="KITINRDLISTWSPAN">
			<select>
				<option value="0"><?php echo $this->translate('Select %s %s',$this->translate('Type of Action'),$this->translate('Here!'));?></option>
				<option value="1"><?php echo $this->translate('Restore');?></option>
				<option value="2"><?php echo $this->translate('Delete');?></option>
			</select> 
		</span>  	
	</div>
</div>