<div class="LMODULEW">
    <div id="UTOPTEXTW">
        <?php echo $this->translate('You are currently logged in as');?>
    </div>
    <div id="UIMGW">
        <img src="<?php echo $this->getMediaUrl('profiles/users/user_img.png');?>" width="88" height="88" alt=""/>
    </div>
    <div id="UNAMETEXTW">
        <a href="#" title="Payam Afshar">Payam Afshar</a>
    </div>
    <div id="UDEPARTMENTTEXTW">
        <?php echo $this->translate('From Department');?> Webtech IT
    </div>
</div>