<div class="tablebg">
  <div style="display: block; padding:0 10px" id="tab1">
	<?php //$clientInfoArray = $this->clientInfo;echo $this->partial('info/tabs/clientInfo.phtml',array('clientInfo'=>$clientInfoArray));?>
  </div>
  <div style="display: block; padding: 0px 10px;" id="tab2">
	<?php //echo $this->partial('info/tabs/clientReports.phtml');?>
  </div>
  <div style="display: block; padding:0 10px" id="tab3">
    <?php //echo $this->partial('info/tabs/clientScoreCard.phtml');?>
  </div>
  <div style="display: block; padding:0 10px" id="tab4">
    <?php echo $this->partial('mapping/tabs/clientMapping.phtml',array('initString'=>$this->initString,'clientID'=>$this->clientID,'type1Collection'=>$this->type1Collection,'type2Collection'=>$this->type2Collection,'plassering'=>$this->plassering));?>
  </div>
  <div style="display: block; padding:0 10px" id="tab5">
    <?php //echo $this->partial('info/tabs/clientStatistic.phtml');?>
  </div>
  <div style="display: block; padding:0 10px" id="tab6">
    <?php //echo $this->partial('info/tabs/clientMTO.phtml');?>
  </div>
  <div style="display: block; padding:0 10px" id="tab7">
    <?php //echo $this->partial('info/tabs/clientHMS.phtml');?>
  </div>
</div>