<table cellspacing=0 cellpadding="0" border="0px" width="100%">
  <tr>
	<td style="padding:0px;">
		<table cellspacing=0 cellpadding="5" border="0px" class="bordercolor" style="border-collapse:collapse; margin-left:0pt" width="100%">
			<tr>
				<th style="width: 100%;" colspan="3"><h2>2.2 &sect; 15 Kroppsvisitasjon <!--&sect; 15 Body Visitation--></h2></th>
			</tr>

			  <tr><td colspan="3">Hver hjemmel st&aring;r p&aring; egen siden, da det kun er den dokumentasjonen som er utfylt, som skal oversendes Fylkesmannen uten ugrunnet opphold .<!--Each authority is on their side, since only the documentation is completed, which shall be submitted to the County without undue delay.--></td></tr>
			  
			  <tr>
				<td class="title1">Redegj&oslash;r for hvilke fremgangsm&aring;ter som ble pr&oslash;vd f&oslash;r beslutning om &aring; foreta kroppsvisitasjon, jf. &sect; 12<!--Describe the procedures that were tried before the decision to conduct body searches, see &sect; 12--></td>
				<td align="left" width="40%" class="nonecls1" colspan="2">
					<span class="tdbg1"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;" id="force_txta22_search" class="validation"  name="force214[force_txta22_search]"><?php echo (isset($this->forceInfo['force_txta22_search']) && $this->forceInfo['force_txta22_search']!='')?$this->forceInfo['force_txta22_search']:'';?></textarea></span></td>
			  </tr>
			  <tr>
				<td class="title1">Hvem besluttet kroppsvisitasjon:<!--Who decided a body search:--></td>
				<td align="left" colspan="2" class="nonecls1"><span class="tdbg1">
					<select class="validation width98" name="force214[force_sel22_search_who]" id="force_sel22_search_who" onchange="changeAreaClass(this.value,'','rem','#force_txt22_search_name','Fullmakt');">
						<option value="" <?php echo (!isset($this->forceInfo['force_sel22_search_who']) || $this->forceInfo['force_sel22_search_who']=='')?'selected="selected"':'';?>>Velg <!-- Select--></option>
						<option value="conductor" <?php echo (isset($this->forceInfo['force_sel22_search_who']) && $this->forceInfo['force_sel22_search_who']=='conductor')?'selected="selected"':'';?>>Leder<!-- Director --></option>
						<option value="leader"  <?php echo (isset($this->forceInfo['force_sel22_search_who']) && $this->forceInfo['force_sel22_search_who']=='leader')?'selected="selected"':'';?>> Fullmakt fra leder<!--Proxy Manager --></option>
					</select></span>
				</td>
			  </tr>
			  <tr>
				<td class="title1">Hvis fullmakt fra leder:<!--If authorization from the manager:--></td>
				<td colspan="2" class="nonecls1">
					<span class="padding5">Navn:</span><!--Name:--><span class="tdbg1"><input type="text"  id="force_txt22_search_name" name="force214[force_txt22_search_name]" value="<?php echo (isset($this->forceInfo['force_txt22_search_name']) && $this->forceInfo['force_txt22_search_name']!='')?$this->forceInfo['force_txt22_search_name']:'';?>" /></span>
				</td>
			  </tr>
			  <tr>
				<td class="title1">Skjedd ved inntaket eller under oppholdet<!--Happened to admission or during stay--></td>
				<td colspan="2" class="nonecls1"><span class="tdbg1">
					  <select class="validation width98" name="force214[force_sel22_happen]" id="force_sel22_happen">
						<option value="" <?php echo (!isset($this->forceInfo['force_sel22_happen']) || $this->forceInfo['force_sel22_happen']=='')?'selected="selected"':'';?>>Velg<!--Select--> </option>
						<option value="admission" <?php echo (isset($this->forceInfo['force_sel22_happen']) && $this->forceInfo['force_sel22_happen']=='admission')?'selected="selected"':'';?>> Ved inntak<!-- admission --></option>
						<option value="stay" <?php echo (isset($this->forceInfo['force_sel22_happen']) && $this->forceInfo['force_sel22_happen']=='stay')?'selected="selected"':'';?>> Under oppholdet<!--During their stay --></option>
					  </select></span>
				</td>
			  </tr>
			  <tr>
				<td class="title1">Hvem var til stede under kroppsvisitasjonen<!--Who was present during kroppsvisitasjonen--></td>
				<td colspan="2" class="nonecls1"><span class="tdbg1">
					<textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;" class="validation"  name="force214[force_txta22_present]"><?php echo (isset($this->forceInfo['force_txta22_present']) && $this->forceInfo['force_txta22_present']!='')?$this->forceInfo['force_txta22_present']:'';?></textarea></span>
				</td>
			  </tr>
			  <tr>
			  	<td class="title1">Ble kroppsvisitasjonen foretatt av person(er) av samme kj&oslash;nn som beboeren:<!--Joined kroppsvisitasjonen made ??by person (s) of the same gender as the resident:--></td>
				<td align="left" colspan="2" class="nonecls1"><span class="tdbg1">
				  <select class="validation width98" name="force214[force_sel22_samesex]" id="force_sel22_samesex">
					<option value="" <?php echo (!isset($this->forceInfo['force_sel22_samesex']) || $this->forceInfo['force_sel22_samesex']=='')?'selected="selected"':'';?>>Velg<!--Select--></option>
					<option value="yes" <?php echo (isset($this->forceInfo['force_sel22_samesex']) && $this->forceInfo['force_sel22_samesex']=='yes')?'selected="selected"':'';?>>  Ja<!--Yes--></option>
					<option value="no" <?php echo (isset($this->forceInfo['force_sel22_samesex']) && $this->forceInfo['force_sel22_samesex']=='no')?'selected="selected"':'';?>>  Nei<!--No--></option>
				  </select></span>
			    </td>
			  </tr>
			  <tr>
				<td width="40%" colspan="3">Mistanke om besittelse av:<!--Suspicion of possession of:--></td>
			  </tr>
			  <tr>
				<td class="title1"><label for="force_chk22_sus_stolen">Tyvgods</label><!--Stolen goods--></td>
				<td colspan="2"><span class="nonecls1"><span class="tdbg"><input type="checkbox" name="force214[force_chk22_sus_stolen]" id="force_chk22_sus_stolen" value="1" class="css-checkbox" <?php echo (isset($this->forceInfo['force_chk22_sus_stolen']) && $this->forceInfo['force_chk22_sus_stolen']=='1')?'checked="checked"':'';?>/><label for="force_chk22_sus_stolen" class="css-label"></label></span></span></td>
			  </tr>
			  <tr>
				<td class="title1"><label for="force_chk22_sus_danger">Farlige gjenstander</label><!--Dangerous objects--></td>
				<td colspan="2"><span class="nonecls1"><span class="tdbg"><input type="checkbox" name="force214[force_chk22_sus_danger]" id="force_chk22_sus_danger" value="1"  class="css-checkbox" <?php echo (isset($this->forceInfo['force_chk22_sus_danger']) && $this->forceInfo['force_chk22_sus_danger']=='1')?'checked="checked"':'';?>/><label for="force_chk22_sus_danger" class="css-label"></label></span></span></td>
			  </tr>
			  <tr>
				<td class="title1"><label for="force_chk22_sus_alcohol">Rusmid ler</label><!--Substance laughs--></td>
				<td colspan="2"><span class="nonecls1"><span class="tdbg"><input type="checkbox" name="force214[force_chk22_sus_alcohol]" id="force_chk22_sus_alcohol" value="1"  class="css-checkbox" <?php echo (isset($this->forceInfo['force_chk22_sus_alcohol']) && $this->forceInfo['force_chk22_sus_alcohol']=='1')?'checked="checked"':'';?>/><label for="force_chk22_sus_alcohol" class="css-label"></label></span></span></td>
			  </tr>
			  <tr>
				<td class="title1"><label for="force_chk22_sus_other">Andre skadelige medikamenter</label><!--Other adverse drug--></td>
				<td colspan="2"><span class="nonecls1"><span class="tdbg"><input type="checkbox" name="force214[force_chk22_sus_other]" id="force_chk22_sus_other" value="1"  class="css-checkbox" <?php echo (isset($this->forceInfo['force_chk22_sus_other']) && $this->forceInfo['force_chk22_sus_other']=='1')?'checked="checked"':'';?>/><label for="force_chk22_sus_other" class="css-label"></label></span></span></td>
			  </tr>
			  <tr>
				<td class="title1"><label for="force_chk22_sus_parapher">Brukerutstyr</label><!--Paraphernalia--></td>
				<td colspan="2"><span class="nonecls1"><span class="tdbg"><input type="checkbox" name="force214[force_chk22_sus_parapher]" id="force_chk22_sus_parapher" value="1"  class="css-checkbox" <?php echo (isset($this->forceInfo['force_chk22_sus_parapher']) && $this->forceInfo['force_chk22_sus_parapher']=='1')?'checked="checked"':'';?>/><label for="force_chk22_sus_parapher" class="css-label"></label></span></span></td>
			  </tr>
			  <tr>
				<td class="title1">Beskriv n&aelig;rmere:<!--Describe in more detail:--></td>
				<td colspan="2" class="nonecls1"><span class="tdbg1"><textarea class="validation" onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;" id="force_txta22_closer" name="force214[force_txta22_closer]"><?php echo (isset($this->forceInfo['force_txta22_closer']) && $this->forceInfo['force_txta22_closer']!='')?$this->forceInfo['force_txta22_closer']:'';?></textarea></span></td>
			  </tr>

			  
			  <tr>
			  	<td class="title1">Redegj&oslash;r for de individuelle og konkrete forholdene som<!--Describe the individual and specific conditions--> ga mistanke om bes ittelse av tyvgods, farlige gjenstander, rusmidler, andre skadelige medikamenter eller brukerutstyr:<!--raised suspicion kindly ittelse of stolen goods, dangerous items, drugs, other harmful drugs or paraphernalia:--></td>
				<td align="left"  colspan="2" class="nonecls1">
				<span class="tdbg1"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;" class="validation" id="force_txta22_individual" name="force214[force_txta22_individual]"><?php echo (isset($this->forceInfo['force_txta22_individual']) && $this->forceInfo['force_txta22_individual']!='')?$this->forceInfo['force_txta22_individual']:'';?></textarea></span></td>
			  </tr>
		  	  <tr>
				<td class="title1">Omfattet kroppsvisitasjonen:<!--Encompassed kroppsvisitasjonen:--></td>
				<td colspan="2"></td>
			  </tr>
			  <tr>
				<td class="title1"><label for="force_chk22_encp_body">Kroppens overflater</label><!--The body surfaces--></td>
				<td colspan="2"><span class="nonecls1"><span class="tdbg"><input type="checkbox" name="force214[force_chk22_encp_body]" id="force_chk22_encp_body" value="1"  class="css-checkbox" <?php echo (isset($this->forceInfo['force_chk22_encp_body']) && $this->forceInfo['force_chk22_encp_body']=='1')?'checked="checked"':'';?>/><label for="force_chk22_encp_body" class="css-label"></label></span></span></td>
			  </tr>
			  <tr>
				<td class="title1"><label for="force_chk22_encp_through">Gjennoms&oslash;kning av kl&aelig;r</label> <!--Through Increase of clothing--></td>
				<td colspan="2"><span class="nonecls1"><span class="tdbg"><input type="checkbox" name="force214[force_chk22_encp_through]" id="force_chk22_encp_through" value="1"  class="css-checkbox" <?php echo (isset($this->forceInfo['force_chk22_encp_through']) && $this->forceInfo['force_chk22_encp_through']=='1')?'checked="checked"':'';?>/><label for="force_chk22_encp_through" class="css-label"></label></span></span></td>
			  </tr>
			  <tr>
				<td class="title1"><label for="force_chk22_encp_undress">Avkledning</label><!--Undressing--></td>
				<td colspan="2"><span class="nonecls1"><span class="tdbg"><input type="checkbox" name="force214[force_chk22_encp_undress]" id="force_chk22_encp_undress" value="1"  class="css-checkbox" <?php echo (isset($this->forceInfo['force_chk22_encp_undress']) && $this->forceInfo['force_chk22_encp_undress']=='1')?'checked="checked"':'';?>/><label for="force_chk22_encp_undress" class="css-label"></label></span></span></td>
			  </tr>
			  <tr>
				<td class="title1"><label for="force_chk22_encp_oral">Munnhulen</label><!--The oral cavity--></td>
				<td colspan="2"><span class="nonecls1"><span class="tdbg"><input type="checkbox" name="force214[force_chk22_encp_oral]" id="force_chk22_encp_oral" value="1"  class="css-checkbox" <?php echo (isset($this->forceInfo['force_chk22_encp_oral']) && $this->forceInfo['force_chk22_encp_oral']=='1')?'checked="checked"':'';?>/><label for="force_chk22_encp_oral" class="css-label"></label></span></span></td>

			  </tr>
			  <tr>
				<td class="title1">
					Beskriv n&aelig;rmere hvordan kroppsvisitasjonen ble gjennomf&oslash;rt?<!--Describe further how kroppsvisitasjonen was completed?-->
				</td>
				<td class="nonecls1 value1" colspan="2">
					<span class="tdbg1"><textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;" class="validation" id="force_txta22_complete" name="force214[force_txta22_complete]"><?php echo (isset($this->forceInfo['force_txta22_complete']) && $this->forceInfo['force_txta22_complete']!='')?$this->forceInfo['force_txta22_complete']:'';?></textarea></span>
				</td>
			  </tr>
		</table>
	</td>
  </tr>
</table>