<table cellspacing=0 cellpadding="0" border="0px" width="100%">
  <tr>
	<td style="padding:0px;">
		<table cellspacing=0 cellpadding="5" border="0px" class="bordercolor" style="border-collapse:collapse; margin-left:0pt"  width="100%">
			<tr>
				<th style="width: 100%;" colspan="2"><h2>2.4 &sect; 17 Beslaglegging, tilintetgj&oslash;ring eller overlevering til politiet<!--&sect; 17 The confiscation, destruction or surrender to police--></h2></th>
			</tr>
			<tr><td colspan="2">Hver hjemmel st&aring;r p&aring; egen siden, da det kun er den dokumentasjonen som er utfylt, som skal oversendes Fylkesmannen uten ugrunnet opphold.<!--Each authority is on their side, since only the documentation is completed, which shall be submitted to the County without undue delay.--></td></tr>
			
			
			<tr>
				<td class="title1" width="60%">Beslag ble foretatt:<!--Seizures were made:--></td>
				<td align="left" width="40%">
					<span class="nonecls1"><span class="tdbg"><input type="checkbox" class="css-checkbox" id="force_chk24_ingestion" name="force214[force_chk24_ingestion]" value="1" <?php echo (isset($this->forceInfo['force_chk24_ingestion']) && $this->forceInfo['force_chk24_ingestion']=='1')?'checked="checked"':'';?>/><label for="force_chk24_ingestion" class="css-label"></label></span></span><label for="force_chk24_ingestion">ved inntak</label><!--by ingestion--><br /><br />
					<span class="nonecls1"><span class="tdbg"><input type="checkbox" class="css-checkbox" id="force_chk24_stay" name="force214[force_chk24_stay]" value="1" <?php echo (isset($this->forceInfo['force_chk24_stay']) && $this->forceInfo['force_chk24_stay']=='1')?'checked="checked"':'';?>/><label for="force_chk24_stay" class="css-label"></label></span></span><label for="force_chk24_stay">under oppholdet</label><!--during stay-->
				</td>
			</tr>
			<tr>
				<td  class="title1">Det ble tatt beslag i:<!--It was seized:--></td>
				<td class="value1"></td>
			</tr>
			<tr>
				<td class="title1"><label for="force_chk24_seiz_stolen">Tyvegods</label><!--Loot--></td>
				<td class="value1"><span class="nonecls1"><span class="tdbg"><input type="checkbox" class="css-checkbox" id="force_chk24_seiz_stolen" name="force214[force_chk24_seiz_stolen]" value="1" <?php echo (isset($this->forceInfo['force_chk24_seiz_stolen']) && $this->forceInfo['force_chk24_seiz_stolen']=='1')?'checked="checked"':'';?>/><label for="force_chk24_seiz_stolen" class="css-label"></label></span></span></td>
			</tr>
			<tr>
				<td class="title1"><label for="force_chk24_seiz_danger">Farlige gjenstander</label><!--Dangerous objects--></td>
				<td class="value1"><span class="nonecls1"><span class="tdbg"><input type="checkbox" class="css-checkbox" id="force_chk24_seiz_danger" name="force214[force_chk24_seiz_danger]" value="1" <?php echo (isset($this->forceInfo['force_chk24_seiz_danger']) && $this->forceInfo['force_chk24_seiz_danger']=='1')?'checked="checked"':'';?>/><label for="force_chk24_seiz_danger" class="css-label"></label></span></span></td>
			</tr>
			<tr>
				<td class="title1"><label for="force_chk24_seiz_intox">Rusmidler</label><!--Drugs--></td>
				<td class="value1"><span class="nonecls1"><span class="tdbg"><input type="checkbox" class="css-checkbox" id="force_chk24_seiz_intox" name="force214[force_chk24_seiz_intox]" value="1" <?php echo (isset($this->forceInfo['force_chk24_seiz_intox']) && $this->forceInfo['force_chk24_seiz_intox']=='1')?'checked="checked"':'';?>/><label for="force_chk24_seiz_intox" class="css-label"></label></span></span></td>
			</tr>
			<tr>
				<td class="title1"><label for="force_chk24_seiz_other">Andre skadelige medikamenter</label><!--Other adverse drug--></td>
				<td class="value1"><span class="nonecls1"><span class="tdbg"><input type="checkbox" class="css-checkbox" id="force_chk24_seiz_other" name="force214[force_chk24_seiz_other]" value="1" <?php echo (isset($this->forceInfo['force_chk24_seiz_other']) && $this->forceInfo['force_chk24_seiz_other']=='1')?'checked="checked"':'';?>/><label for="force_chk24_seiz_other" class="css-label"></label></span></span></td>
			</tr>
			<tr>
				<td class="title1"><label for="force_chk24_seiz_parapher">Brukerutstyr</label><!--Paraphernalia--></td>
				<td class="value1"><span class="nonecls1"><span class="tdbg"><input type="checkbox" class="css-checkbox" id="force_chk24_seiz_parapher" name="force214[force_chk24_seiz_parapher]" value="1" <?php echo (isset($this->forceInfo['force_chk24_seiz_parapher']) && $this->forceInfo['force_chk24_seiz_parapher']=='1')?'checked="checked"':'';?>/><label for="force_chk24_seiz_parapher" class="css-label"></label></span></span></td>
			</tr>
			<tr>
				<td class="title1">Beskriv n&aelig;rmere:<!--Describe in more detail:--></td>
				<td class="value1 nonecls1"><span class="tdbg1"><textarea onkeyup="textAreaAdjust(this)" style="overflow:visible;width: 100%; border: none; height:auto;" class="validation" id="force_txta24_closer"  name="force214[force_txta24_closer]"><?php echo (isset($this->forceInfo['force_txta24_closer']) && $this->forceInfo['force_txta24_closer']!='')?$this->forceInfo['force_txta24_closer']:'';?></textarea></td>
			</tr>					
			<tr>
				<td class="title1">Beslaget skjedde ved:<!--The seizure occurred at:--></td>
				<td class="value1"><span class="nonecls1"><span class="tdbg"><input type="checkbox" class="css-checkbox" id="force_chk24_occur_body" name="force214[force_chk24_occur_body]" value="1" <?php echo (isset($this->forceInfo['force_chk24_occur_body']) && $this->forceInfo['force_chk24_occur_body']=='1')?'checked="checked"':'';?>/><label for="force_chk24_occur_body" class="css-label"></label></span></span><label for="force_chk24_occur_body">kroppsvisitasjon</span><!--body search--></td>
			</tr>
			<tr>
				<td class="title1"></td>
				<td class="value1"><span class="nonecls1"><span class="tdbg"><input type="checkbox" class="css-checkbox" id="force_chk24_occur_ransak" name="force214[force_chk24_occur_ransak]" value="1" <?php echo (isset($this->forceInfo['force_chk24_occur_ransak']) && $this->forceInfo['force_chk24_occur_ransak']=='1')?'checked="checked"':'';?>/><label for="force_chk24_occur_ransak" class="css-label"></label></span></span><label for="force_chk24_occur_ransak">ransaking av rom og eiendeler</span><!--searches of rooms and property--></td>
			</tr>
			<tr>
				<td class="title1"></td>
				<td class="value1"><span class="nonecls1"><span class="tdbg"><input type="checkbox" class="css-checkbox" id="force_chk24_occur_mail" name="force214[force_chk24_occur_mail]" value="1" <?php echo (isset($this->forceInfo['force_chk24_occur_mail']) && $this->forceInfo['force_chk24_occur_mail']=='1')?'checked="checked"':'';?>/><label for="force_chk24_occur_mail" class="css-label"></label></span></span><label for="force_chk24_occur_mail">&aring;pning av post</span><!--opening the mail--></td>
			</tr>
			<tr>
				<td class="title1"></td>
				<td class="value1"><span class="nonecls1"><span class="tdbg"><input type="checkbox" class="css-checkbox" id="force_chk24_occur_other" name="force214[force_chk24_occur_other]" value="1" <?php echo (isset($this->forceInfo['force_chk24_occur_other']) && $this->forceInfo['force_chk24_occur_other']=='1')?'checked="checked"':'';?>/><label for="force_chk24_occur_other" class="css-label"></label></span></span><label for="force_chk24_occur_other">annet tilfelle</span><!--Another case--></td>
			</tr>
			<tr>
				<td class="title1">Hvis annet tilfelle, beskriv:</td>
				<td class="value1 nonecls1"><span class="tdbg1"><textarea onkeyup="textAreaAdjust(this)" style="overflow:visible;width: 100%; border: none; height:auto;"   id="force_txta24_other_res"  name="force214[force_txta24_other_res]"><?php echo (isset($this->forceInfo['force_txta24_other_res']) && $this->forceInfo['force_txta24_other_res']!='')?$this->forceInfo['force_txta24_other_res']:'';?></textarea></span></td>
			</tr>
			<tr>
				<td class="title1">Hva ble gjort med det som ble funnet?<!--What was done with what was found?--></td>
				<td class="value1"><span class="nonecls1"><span class="tdbg"><input type="checkbox" class="css-checkbox" id="force_chk24_done_police" name="force214[force_chk24_done_police]" value="1" <?php echo (isset($this->forceInfo['force_chk24_done_police']) && $this->forceInfo['force_chk24_done_police']=='1')?'checked="checked"':'';?>/><label for="force_chk24_done_police" class="css-label"></label></span></span><label for="force_chk24_done_police">Overlevert til politiet (ulovlige gjenstander, rusmidler eller medikamenter)</span><!--Handed over to the police (illegal items, drugs or medication)--></td>
			</tr>
			<tr>
				<td class="title1"></td>
				<td class="value1"><span class="nonecls1"><span class="tdbg"><input type="checkbox" class="css-checkbox" id="force_chk24_done_loot" name="force214[force_chk24_done_loot]" value="1" <?php echo (isset($this->forceInfo['force_chk24_done_loot']) && $this->forceInfo['force_chk24_done_loot']=='1')?'checked="checked"':'';?>/><label for="force_chk24_done_loot" class="css-label"></label></span></span><label for="force_chk24_done_loot">Overlevert til politiet (tyvegods)</span><!--Handed over to the police (loot)--></td>
			</tr>
			<tr>
				<td class="title1"></td>
				<td class="value1"><span class="nonecls1"><span class="tdbg"><input type="checkbox" class="css-checkbox" id="force_chk24_done_return" name="force214[force_chk24_done_return]" value="1" <?php echo (isset($this->forceInfo['force_chk24_done_return']) && $this->forceInfo['force_chk24_done_return']=='1')?'checked="checked"':'';?>/><label for="force_chk24_done_return" class="css-label"></label></span></span><label for="force_chk24_done_return">Levert tilbake til rette eier (tyvegods)</span><!--Returned to the rightful owner (loot)--></td>
			</tr>
			<tr>
				<td class="title1"></td>
				<td class="value1"><span class="nonecls1"><span class="tdbg"><input type="checkbox" class="css-checkbox" id="force_chk24_done_crus" name="force214[force_chk24_done_crus]" value="1" <?php echo (isset($this->forceInfo['force_chk24_done_crus']) && $this->forceInfo['force_chk24_done_crus']=='1')?'checked="checked"':'';?>/><label for="force_chk24_done_crus" class="css-label"></label></span></span><label for="force_chk24_done_crus">Tilintetgjort (f.eks. alkohol)</span><!--Destroyed (eg. Alcohol)--></td>
			</tr>
			<tr>
				<td class="title1"></td>
				<td class="value1"><span class="nonecls1"><span class="tdbg"><input type="checkbox" class="css-checkbox" id="force_chk24_done_storage" name="force214[force_chk24_done_storage]" value="1" <?php echo (isset($this->forceInfo['force_chk24_done_storage']) && $this->forceInfo['force_chk24_done_storage']=='1')?'checked="checked"':'';?>/><label for="force_chk24_done_storage" class="css-label"></label></span></span><label for="force_chk24_done_storage">Oppbevaring (f.eks. speiderkniv)</span><!--Storage (eg. Scout knife)--></td>
			</tr>
		</table>
	</td>
  </tr>
</table>