<div style="margin: 15px;">
<ul>
    <li>Under kolonnen til venstre skal du krysse av for hvilke(n) hjemmel/hjemler tvangen omhandler. Dette for at Fylkesmannen skal få oversikt.</li>
    <li>På forsiden i dette dokumentet skal du velge om dokumentet er et enkeltvedtak og protokoll eller en protokoll med begrunnelse. Oversikten i høyre kolonne under er til hjelp for å foreta dette valget.</li>
    <li>Bestemmelsene er farget i blått og rødt for å skille mellom tvang som gjelder ved alle plasseringer, og de som kun gjelder for atferdsplasseringer.</li>
    <li>Fra del 2.1. til del 2.11. skal du kun fylle ut den hjemmel eller de hjemler som er aktuelle.</li>
</ul>
</div>