<div class="PSUBTCWRAPPER">
	<div class="PSUBTCLEFT">
    	<?php echo $this->translate('Quarterly Summary');?>
    </div>
    <div class="OPPRETTSUMERINGB"><a class="OPPRETTSUMERINGBA" href="#"><?php echo $this->translate('Create %s',$this->translate('Quarterly Summary'));?></a></div>
</div>
<div class="CLEARBBORDER"></div>
<div class="VVGBG VV2IN1C2 KRV">
<table width="100%" border="0" cellspacing="4" cellpadding="0">
    <tr class="CURNONPOINTER">
        <th class="TSLRTDCENTER"><?php echo $this->translate('Report');?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('Department');?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('User');?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('Measure');?></th>
		<th class="TSLRTDCENTER"><?php echo $this->translate('Force');?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('Date %s',$this->translate('Start'));?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('Date %s',$this->translate('End'));?></th>
		<th class="TSLRTDCENTER"><?php echo $this->translate('Action');?></th>
    </tr>
    <tr>
        <td><span class="tdbg"><?php echo $this->translate('No.');?>: 1</span></td>
        <td><span class="tdbg">Webtech IT</span></td>
        <td><span class="tdbg">Andreas Balchen</span></td>
        <td><span class="tdbg">1</span></td>
        <td><span class="tdbg">6</span></td>
        <td><span class="tdbg">13/10-2014</span></td>
        <td><span class="tdbg">19/10-2014</span></td>
        <td>
        	<span class="tdbg">
                <select>
                    <option value=""><?php echo $this->translate('Edit');?></option>
                    <option value=""><?php echo $this->translate('Delete');?></option>
                </select> 
            </span>
        </td>
    </tr>
</table>
<div class="KRV1C2">
      <div class="KRV1C2_1">
        	<div class="KRV1C2_11"><?php echo $this->translate('Sort');?>:</div>
        	<div class="KRV1C2_12">
                <span class="tdbgkinfo">
                <select>
                    <option value="">1 <?php echo $this->translate('Month');?></option>
                    <option value="">2 <?php echo $this->translate('Month');?></option>
                    <option value="">3 <?php echo $this->translate('Month');?></option>
                    <option value="">6 <?php echo $this->translate('Month');?></option>
                    <option value="">1 <?php echo $this->translate('Year');?></option>
                    <option value="">2 <?php echo $this->translate('Year');?></option>
                    <option value=""><?php echo $this->translate('All');?></option>
                </select> 
                </span>
            </div>
    	</div>
    	<div class="KRV1C2_1">
        	<div class="KRV1C2_11"><?php echo $this->translate('View');?>:</div>
        	<div class="KRV1C2_12">
                <span class="tdbgkinfo">
                <select>
                    <option value="">10</option>
                    <option value="">25</option>
                    <option value="">50</option>
                    <option value="">100</option>
                    <option value=""><?php echo $this->translate('All');?></option>
                </select> 
                </span>
            </div>
    	</div>
    </div>
</div>