<?php
$format = KD::getModel('core/format');
$decrypt = KD::getModel('core/Endecrypt');
?>
<div class="PSUBTCWRAPPER">
  <div class="PSUBTCLEFT">
    <?php echo $this->translate('Deviation');?>
  </div>
</div>
<div class="CLEARBBORDER"></div>

<?php if(empty($this->deviationArchive)): ?>
  <?php echo $this->translate('No log items found'); ?>
<?php else: ?>
  <table class="width100">
    <tr>
      <th width="20%"><?php echo $this->translate('Date'); ?></th>
      <th width="10%"><?php echo $this->translate('Avvik type');?></th>
      <th width="40%"><?php echo $this->translate('Avvik description'); ?></th>
      <th width="30%"><?php echo $this->translate('signature'); ?></th>
    </tr>
    <?php foreach($this->deviationArchive as $deviation): ?>
      <tr>
        <td><?php echo $format->formatDate($deviation['date_of_creation']) . ' kl: ' . $format->formatTime($deviation['date_of_creation']); ?></td>
        <td><?php echo $deviation['deviation_type']; ?></td>
        <td><?php echo $deviation['deviation_desc']; ?></td>
        <td><?php echo $decrypt->getDec($deviation['user_fname']) . ' ' . $decrypt->getDec($deviation['user_lname']); ?></td>
      </tr>
    <?php endforeach;?>
  </table>
<?php endif; ?>




