<?php $format = KD::getModel('core/format');
$tiltakId = $this->tiltakID;
if(isset($tiltakId) && $tiltakId>0 && isset($this->tiltakCollection)):?>
<form name="frmClientEditfutTiltak" id="frmClientEditfutTiltak" method="post" action="<?php echo $this->getUrl("client/mto/editfeatiltakpost/id/".$tiltakId.'/pid/'.$this->tiltakCollection['tilfut_patientID']);?>">
<table width="100%" border="0" cellspacing="4" cellpadding="0" id="clientEditGovTiltakTbl">
      <tr class="CURNONPOINTER">
		<th class="TSLRTDCENTER" width="15%"><?php echo $this->translate('Owner');?></th>
		<th class="TSLRTDCENTER" width="55%"><?php echo $this->translate('Future Measure');?></th>
		<th class="TSLRTDCENTER" width="15%"><?php echo $this->translate('From Date');?></th>
		<th class="TSLRTDCENTER" width="15%"><?php echo $this->translate('To Date');?></th>
      </tr>
	  <tr>
	  	<td class="nonecls"><span class="tdbg VVTAC"><div><span><?php echo $this->translate('A');?><input type="radio" id="tilfut_owner1" value="A" name="tilfut_owner" data-validation="radio" <?php echo ($this->tiltakCollection['tilfut_owner']=='A')?'checked="checked"':'';?>/><label for="tilfut_owner1"><span></span></label></span><span><?php echo $this->translate('U');?><input type="radio" data-validation="radio" value="U" id="tilfut_owner2" name="tilfut_owner" <?php echo ($this->tiltakCollection['tilfut_owner']=='U')?'checked="checked"':'';?>/><label for="tilfut_owner2"><span></span></label></span><span><?php echo $this->translate('M');?><input type="radio" data-validation="radio" value="M" id="tilfut_owner3" name="tilfut_owner" <?php echo ($this->tiltakCollection['tilfut_owner']=='M')?'checked="checked"':'';?>/><label for="tilfut_owner3"><span></span></label></span></div>
		</span></td>
	  	<td class="nonecls"><span class="tdbg"><input type="text" name="tilfut_desc" value="<?php echo $this->tiltakCollection['tilfut_desc'];?>" id="tilfut_desc" data-validation="required" /></span></td>
		<td class="nonecls"><span class="tdbg"><input type="text" readonly name="tilfut_from_date" value="<?php echo $format->FormatDate($this->tiltakCollection['tilfut_from_date']);?>" data-validation="required"  id="tilfut_from_date" class="DyndatepickerImage1 width70"/></span></td>
		<td class="nonecls"><span class="tdbg"><input type="text" readonly name="tilfut_to_date" style=" <?php echo $format->getColorStyle($this->tiltakCollection['tilfut_to_date']);?>" value="<?php echo $format->FormatDate($this->tiltakCollection['tilfut_to_date']);?>" id="tilfut_to_date" class="DyndatepickerImage1 width70" data-validation="required" /></span></td></tr>
</table>
<div class="mtodroplist2">
	<div class="OPPRETTB"><input type="submit" class="OPPRETTBA" value="<?php echo $this->translate('Save');?>"/></div>
</div>
</form>
<?php endif;?>
