<?php $format=KD::getModel('core/format');?>
<?php 
foreach($this->maalCollection as $maal):  ?>
<?php $id = $maal['maal_id']; ?>
  <?php /*?><tr class="dropPri">
	<td colspan="5"></td>
  </tr><?php */?>
  <tr id="maal-<?php echo $id;?>">
	<td class="TSLRTDNUMBER bgwhite">
		<span class="tdbg" style="width: 20px;">
		<input type="checkbox" name="<?php echo 'checkbox_'.$id;?>" id="<?php echo 'checkbox_'.$id;?>" class="css-checkbox"/>
		<label for="<?php echo 'checkbox_'.$id;?>" class="css-label"></label>
		</span>
	</td>
	<td><span class="tdbg cursormove"><?php echo $maal['maal_desc']; ?></span></td>
	<?php /*?><td class="bgwhite"><span class="tdbg"><?php echo $maal['maal_order']; ?></span></td><?php */?>
	<td class="bgwhite"><span class="tdbg cursormove"><?php echo $format->FormatDate($maal['maal_from_date']); ?></span></td>
	<td class="bgwhite"><span class="tdbg cursormove" style=" <?php echo $format->getColorStyle($maal['maal_to_date']);?>" ><?php echo $format->FormatDate($maal['maal_to_date']); ?></span></td>
	<td><span class="tdbg dialog-ajax1" data-url="<?php echo $this->getUrl('client/mto/editmaal/id/'.$id);?>" data-title="<?php echo $maal['maal_desc']; ?>">Edit</span></td>
  </tr>

<?php endforeach; ?>
<script language="javascript">
$(document).ready(function(){
	$('.dialog-ajax1').unbind("click").click(function(){   
		var tag = $("<div></div>"); //This tag will the hold the dialog content.
		var url = $(this).data('url');
		var title = $(this).data('title');
		$.ajax({
		  url: $(this).data('url'),
		  type: 'GET',
		  beforeSend: function() {$("#loading-image").show();},
		  error: function() { alert('Could not load form') },
		  success: function(data, textStatus, jqXHR) {
			if(typeof data == "object" && data.html) { //response is assumed to be JSON
			  tag.html(data.html).dialog({modal:true, title: title}).dialog('open');
			} else { //response is assumed to be HTML
			  tag.html(data).dialog({modal: true, title: title, height: 200, width:800, hide: "scale", show : "scale",
					open: function (event, ui) {
						var startDate = $(".DyndatepickerImage1");
						startDate.unbind();
						startDate.datepicker(Mtg.Config.Datepicker);
						$.validate({
							form : '#frmClientEditMaal', 
							validateOnBlur : false,
							borderColorOnError : '#C90312',
							addValidClassOnAll : true,
							showHelpOnFocus : false,
							addSuggestions : false,
							errorMessagePosition : 'top',
							scrollToTopOnError : true
						});
						$("#loading-image").hide();
					},
					close: function (event, ui) {
						$('input.DyndatepickerImage1').datepicker("destroy");
						$(this).dialog("destroy");
						$(this).remove();
					}
				}).dialog('open');
				
			}
		  }
		});
	  });	
});
</script>