<ul id="tab">
  <li class="INACTIVTAB" <?php echo ($this->defaultTab=='1')?'id="current"':'';?>><a href="#" name="tab1"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Active %s',$this->translate('Clients'));?></div></a></li>
  <li class="INACTIVTAB" <?php echo ($this->defaultTab=='2')?'id="current"':'';?>><a href="#" name="tab2"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Archived %s',$this->translate('Clients'));?></div></a></li> 
</ul>