<ul id="tab">
  <li class="INACTIVTAB" <?php echo ($this->defaultTab=='1')?'id="current"':'';?>><a href="<?php echo $this->getUrl('vaktrapport/index');?>" name="tab1"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Security Report');?></div></a></li>
  
  <li class="INACTIVTAB" <?php echo ($this->defaultTab=='2')?'id="current"':'';?>><a href="#" name="tab2"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Force');?></div></a></li>
  <li class="INACTIVTAB" <?php echo ($this->defaultTab=='6')?'id="current"':'';?>><a href="#" name="tab6"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Avvik');?></div></a></li>
  <li class="INACTIVTAB" <?php echo ($this->defaultTab=='3')?'id="current"':'';?>><a href="#" name="tab3"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Log');?></div></a></li>
  <li class="INACTIVTAB" <?php echo ($this->defaultTab=='4')?'id="current"':'';?>><a href="#" name="tab4"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Medicine');?></div></a></li>
  <li class="INACTIVTAB" <?php echo ($this->defaultTab=='5')?'id="current"':'';?>><a href="#" name="tab5"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Weekly Schedule');?></div></a></li>
</ul>	