<ul id="tab">
	<li class="INACTIVTAB" <?php echo ($this->defaultTab=='1')?'id="current"':'';?>>
        <a href="#" name="tab1">
            <div class="ACTIVETLZI TLZI">
				<?php echo $this->translate('User Info');?>
            </div>
        </a>
    </li>
	<li class="INACTIVTAB" <?php echo ($this->defaultTab=='2')?'id="current"':'';?>>
	        <a href="#" name="tab2"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Expertise');?></div></a>
        
    </li>
	<li class="INACTIVTAB" <?php echo ($this->defaultTab=='3')?'id="current"':'';?>>
        	<a href="#" name="tab3"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Education');?></div></a>
    </li>
	<li class="INACTIVTAB" <?php echo ($this->defaultTab=='4')?'id="current"':'';?>>
	        <a href="#" name="tab4"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Relatives');?></div></a>
    </li>
	<li class="INACTIVTAB" <?php echo ($this->defaultTab=='5')?'id="current"':'';?>>
        	<a href="#" name="tab5"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Documents');?></div></a>
    </li>
</ul>