<ul id="tab">
  <li class="INACTIVTAB" <?php echo ($this->defaultTab=='1')?'id="current"':'';?>><a href="#" name="tab1"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Info Management');?></div></a></li>
  <li class="INACTIVTAB" <?php echo ($this->defaultTab=='2')?'id="current"':'';?>><a href="#" name="tab2"><div class="ACTIVETLZI TLZI"><?php echo $this->translate('Scratch Pad');?></div></a></li>
</ul>