<ul id="tab">
	<li class="INACTIVTAB"  <?php echo ($this->defaultTab=='1')?'id="current"':'';?>><a href="#" name="tab1"><div class="ACTIVETLZI TLZI">TAB1</div></a></li>
	<li class="INACTIVTAB" <?php echo ($this->defaultTab=='2')?'id="current"':'';?>><a href="#" name="tab2"><div class="ACTIVETLZI TLZI">TAB2</div></a></li>
	<li class="INACTIVTAB" <?php echo ($this->defaultTab=='3')?'id="current"':'';?>><a href="#" name="tab3"><div class="ACTIVETLZI TLZI">TAB3</div></a></li>
	<li class="INACTIVTAB" <?php echo ($this->defaultTab=='4')?'id="current"':'';?>><a href="#" name="tab4"><div class="ACTIVETLZI TLZI">TAB4</div></a></li>
	<li class="INACTIVTAB" <?php echo ($this->defaultTab=='5')?'id="current"':'';?>><a href="#" name="tab5"><div class="ACTIVETLZI TLZI">TAB5</div></a></li>
	<li class="INACTIVTAB" <?php echo ($this->defaultTab=='6')?'id="current"':'';?>><a href="#" name="tab6"><div class="ACTIVETLZI TLZI">TAB6</div></a></li>  
</ul>