<?php $format = KD::getModel('core/format');?>

    <table width="100%" border="0" cellspacing="2" cellpadding="2">
      <tr class="CURNONPOINTER">
        <th class="TSLRTDNUMBER">
        <span class="tdbg2">
        	<input type="checkbox" name="checkboxG0" id="checkboxG0" class="css-checkbox" />
            <label for="checkboxG0" class="css-label"></label>
        </span>
        </td>
        <th class="TSLRTDCENTER"><?php echo $this->translate('Name');?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('ODA No');?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('Department');?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('Date %s',$this->translate('In'));?></th>
      </tr>

	<?php foreach($this->vaktrapportCollection as $vaktrapport):?>
      <tr>
        <td class="TSLRTDNUMBER">
        	<span class="tdbg" style="width: 20px;">
                <input type="checkbox" name="checkboxG1" id="checkboxG1" class="css-checkbox" />
                <label for="checkboxG1" class="css-label"></label>
       		</span>
        </td>
        <td><span class="tdbg"><a href="<?php echo $this->getUrl('vaktrapport/info/index/id/'.$vaktrapport['vaktrap_id']);?>"><?php echo $format->FormatName($vaktrapport['patient_fname'],$vaktrapport['patient_mname'],$vaktrapport['patient_lname']);?></a></span></td>
        <td><span class="tdbg"><?php echo $vaktrapport['patient_birk_no'];?></span></td>
        <td><span class="tdbg"><?php echo $vaktrapport['dept_name'];?></span></td>
        <td><span class="tdbg"><?php echo $format->FormatDate($vaktrapport['patient_date_of_joining']);?></span></td>
      </tr>
    <?php endforeach;?>

    </table>