<div class="PSUBTCWRAPPER">
	<div class="PSUBTCLEFT">
    <?php echo $this->translate('%s List',$this->translate('Task'));?>
    </div>
</div>
<div class="CLEARBBORDER"></div>
<div class="VVGBG">
<table width="100%" border="0" cellspacing="4" cellpadding="0">
      <tr class="CURNONPOINTER">
        <th class="TSLRTDNUMBER">
        <span class="tdbg2">
        	<input type="checkbox" name="checkboxG0" id="checkboxG0" class="css-checkbox" />
            <label for="checkboxG0" class="css-label"></label>
        </span>
        </th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('Title');?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('Probability');?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('Consequence');?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('Classification');?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('Responsible');?></th>
      </tr>

      <tr>
        <td class="TSLRTDNUMBER">
        	<span class="tdbg" style="width: 20px;">
                <input type="checkbox" name="checkboxG1" id="checkboxG1" class="css-checkbox" />
                <label for="checkboxG1" class="css-label"></label>
       		</span>
        </td>
        
        <td><span class="tdbg">Payam Afshar</span></td>
        <td><span class="tdbg">Brann i kj&oslash;kken</span></td>
        <td><span class="tdbg">Inne</span></td>
        <td><span class="tdbg">Webtech IT As</span></td>
        <td><span class="tdbg">3</span></td>
      </tr>
      <tr>
        <td class="TSLRTDNUMBER">
        	<span class="tdbg" style="width: 20px;">
            <input type="checkbox" name="checkboxG2" id="checkboxG2" class="css-checkbox" />
            <label for="checkboxG2" class="css-label"></label>
        	</span>
        </td>
        <td><span class="tdbg">Payam Afshar</span></td>
        <td><span class="tdbg">Brann i kj&oslash;kken</span></td>
        <td><span class="tdbg">Inne</span></td>
        <td><span class="tdbg">Webtech IT As</span></td>
        <td><span class="tdbg">3</span></td>
      </tr>
       <tr>
        <td class="TSLRTDNUMBER">
        	<span class="tdbg" style="width: 20px;">
            <input type="checkbox" name="checkboxG3" id="checkboxG3" class="css-checkbox" />
            <label for="checkboxG3" class="css-label"></label>
        	</span>
        </td>
        <td><span class="tdbg">Payam Afshar</span></td>
        <td><span class="tdbg">Brann i kj&oslash;kken</span></td>
        <td><span class="tdbg">Inne</span></td>
        <td><span class="tdbg">Webtech IT As</span></td>
        <td><span class="tdbg">3</span></td>
      </tr>
       <tr>
        <td class="TSLRTDNUMBER">
        	<span class="tdbg" style="width: 20px;">
            <input type="checkbox" name="checkboxG4" id="checkboxG4" class="css-checkbox" />
            <label for="checkboxG4" class="css-label"></label>
        	</span>
        </td>
        <td><span class="tdbg">Payam Afshar</span></td>
        <td><span class="tdbg">Brann i kj&oslash;kken</span></td>
        <td><span class="tdbg">Inne</span></td>
        <td><span class="tdbg">Webtech IT As</span></td>
        <td><span class="tdbg">3</span></td>
      </tr>
      <tr>
        <td class="TSLRTDNUMBER">
        	<span class="tdbg" style="width: 20px;">
            <input type="checkbox" name="checkboxG5" id="checkboxG5" class="css-checkbox" />
            <label for="checkboxG5" class="css-label"></label>
        	</span>
        </td>
        <td><span class="tdbg">Payam Afshar</span></td>
        <td><span class="tdbg">Brann i kj&oslash;kken</span></td>
        <td><span class="tdbg">Inne</span></td>
        <td><span class="tdbg">Webtech IT As</span></td>
        <td><span class="tdbg">3</span></td>
      </tr>
      <tr>
        <td class="TSLRTDNUMBER">
        	<span class="tdbg" style="width: 20px;">
            <input type="checkbox" name="checkboxG6" id="checkboxG6" class="css-checkbox" />
            <label for="checkboxG6" class="css-label"></label>
        	</span>
        </td>
        <td><span class="tdbg">Payam Afshar</span></td>
        <td><span class="tdbg">Brann i kj&oslash;kken</span></td>
        <td><span class="tdbg">Inne</span></td>
        <td><span class="tdbg">Webtech IT As</span></td>
        <td><span class="tdbg">3</span></td>
      </tr>
      <tr>
        <td class="TSLRTDNUMBER">
        	<span class="tdbg" style="width: 20px;">
            <input type="checkbox" name="checkboxG7" id="checkboxG7" class="css-checkbox" />
            <label for="checkboxG7" class="css-label"></label>
        	</span>
        </td>
        <td><span class="tdbg">Payam Afshar</span></td>
        <td><span class="tdbg">Brann i kj&oslash;kken</span></td>
        <td><span class="tdbg">Inne</span></td>
        <td><span class="tdbg">Webtech IT As</span></td>
        <td><span class="tdbg">3</span></td>
      </tr>
      <tr>
        <td class="TSLRTDNUMBER">
        	<span class="tdbg" style="width: 20px;">
            <input type="checkbox" name="checkboxG8" id="checkboxG8" class="css-checkbox" />
            <label for="checkboxG8" class="css-label"></label>
        	</span>
        </td>
        <td><span class="tdbg">Payam Afshar</span></td>
        <td><span class="tdbg">Brann i kj&oslash;kken</span></td>
        <td><span class="tdbg">Inne</span></td>
        <td><span class="tdbg">Webtech IT As</span></td>
        <td><span class="tdbg">3</span></td>
      </tr>
    </table>
  </div>
  
  <div class="listdroplist">
    	<div class="PSUBTCLEFT"><?php echo $this->translate('Select %s',$this->translate('Type of Action'));?></div>
        <div class="KITINRDLISTW">
        	<span class="KITINRDLISTWSPAN">
            	<select>
                	<option value="0"><?php echo $this->translate('Select %s %s',$this->translate('Type of Action'),$this->translate('Here!'));?></option>
                    <option value="1"><?php echo $this->translate('Finished');?>/<?php echo $this->translate('Performed');?></option>
                    <option value="2"><?php echo $this->translate('Change');?></option>
                    <option value="2"><?php echo $this->translate('Delete');?></option>
				</select> 
			</span>  	
		</div>
	</div>