<div class="PSUBTCWRAPPER">
	<div class="PSUBTCLEFT">
    	<?php echo $this->translate('Create %s',$this->translate('Task'));?>
    </div>
</div>
<div class="CLEARBBORDER"></div>

<div class="VVGBG">
     	<table width="100%" border="0" cellspacing="4" cellpadding="0">
  <tbody>
    <tr>
      <th scope="col" width="20%"><?php echo $this->translate('Title');?></th>
      <th scope="col" width="20%"><?php echo $this->translate('Probability');?></th>
      <th scope="col" width="20%"><?php echo $this->translate('Consequence');?></th>
      <th scope="col" width="20%"><?php echo $this->translate('Classification');?></th>
      <th scope="col" width="20%"><?php echo $this->translate('Responsible');?></th>
    </tr>
    <tr>
      <td><span class="tdbg45"><input type="text" value="Brann i kj&oslash;kken"></span></td>
      <td>
      	<span class="tdbg96p">
            <select>
                <option value=""><?php echo $this->translate('Low');?></option>
                <option value=""><?php echo $this->translate('Medium');?></option>
                <option value=""><?php echo $this->translate('High');?></option>
            </select> 
        </span>
      </td>
      <td>
      	<span class="tdbg96p">
            <select>
                <option value=""><?php echo $this->translate('Low');?></option>
                <option value=""><?php echo $this->translate('Medium');?></option>
                <option value=""><?php echo $this->translate('High');?></option>
            </select> 
        </span>
      </td>
      <td>
      	<span class="tdbg96p">
            <select>
                <option value=""><?php echo $this->translate('Low');?></option>
                <option value=""><?php echo $this->translate('Medium');?></option>
                <option value=""><?php echo $this->translate('High');?></option>
            </select> 
        </span>
      </td>      
      <td><span class="tdbg45"><input type="text" value="Andreas Balchen"></span></td>
    </tr>
    
  </tbody>
</table>
</div>

<div class="CLEARBBORDER2"></div>
	<div class="KKI2C">
        <table width="100%" border="0" cellspacing="4" cellpadding="0">
            <tr>
                <th class="noborder"><?php echo $this->translate('Hazard Source');?></th>
            </tr>
            <tr>
                <td><span class="tdbg1c">
                        <textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;"><?php echo $this->translate('Description');?></textarea>
                    </span>
                </td>
            </tr>
		</table> 
    </div>
    <div class="CLEARBBORDER2"></div>
    <div class="KKI2C">
        <table width="100%" border="0" cellspacing="4" cellpadding="0">
            <tr>
                <th class="noborder"><?php echo $this->translate('What might happen and how likely is it?');?></th>
            </tr>
            <tr>
                <td><span class="tdbg1c">
                        <textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;"><?php echo $this->translate('Description');?></textarea>
                    </span>
                </td>
            </tr>
		</table> 
    </div>
    <div class="CLEARBBORDER2"></div>
    <div class="KKI2C">
        <table width="100%" border="0" cellspacing="4" cellpadding="0">
            <tr>
                <th class="noborder"><?php echo $this->translate('What can prevent the danger?');?></th>
            </tr>
            <tr>
                <td><span class="tdbg1c">
                        <textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;"><?php echo $this->translate('Description');?></textarea>
                    </span>
                </td>
            </tr>
		</table> 
    </div>
    <div class="CLEARBBORDER2"></div>
    <div class="KKI2C">
        <table width="100%" border="0" cellspacing="4" cellpadding="0">
            <tr>
                <th class="noborder"><?php echo $this->translate('Measures and further work');?></th>
            </tr>
            <tr>
                <td><span class="tdbg1c">
                        <textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;"><?php echo $this->translate('Description');?></textarea>
                    </span>
                </td>
            </tr>
		</table> 
    </div>
    <div class="CLEARBBORDER2"></div>
    <div class="KKI2C">
        <table width="100%" border="0" cellspacing="4" cellpadding="0">
            <tr>
                <th class="noborder"><?php echo $this->translate('Furthermore after his fathers fixed');?></th>
            </tr>
            <tr>
                <td><span class="tdbg1c">
                        <textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden;width: 100%; border: none; height:auto;"><?php echo $this->translate('Description');?></textarea>
                    </span>
                </td>
            </tr>
		</table> 
    </div>
    <div class="CLEARBBORDER2"></div>
<div class="VVGBG">
<table width="100%" border="0">
  <tr>
    <th><?php echo $this->translate('Signature');?></th>
    <th><?php echo $this->translate('Date');?></th>
  </tr>
  <tr>
    <td><span class="tdbg1c">Andreas Balchen</span></td>
    <td><span class="tdbg1c">02/09-2014:10-25-29</span></td>
  </tr>
</table>
</div>
<div class="LAGREB3"><a class="LAGREBA2" href="#"><?php echo $this->translate('Create');?></a></div>
<div class="FERDIGB"><a class="FERDIGBA" href="#"><?php echo $this->translate('Finished');?></a></div>