<div class="tablebg">
	<div style="display: block; padding:0 10px" id="tab1">
		<?php echo $this->partial('index/tabs/statisticDepartment.phtml',array('departmentCollection'=>$this->departmentCollection,'deptId'=>$this->deptId,'startDate'=>$this->startDate,'endDate'=>$this->endDate,'period'=>$this->period,'year'=>$this->year,'instTiltakCountCollection'=>$this->instTiltakCountCollection,'govTiltakCountCollection'=>$this->govTiltakCountCollection,'observationCollection'=>$this->observationCollection,'observations'=>$this->observations,'observationAllData'=>$this->observationAllData));?>
	</div>
	<div style="display: block; padding:0 10px" id="tab2">
		<?php //echo $this->partial('index/tabs/statisticClient.phtml',array('departmentCollection'=>$this->departmentCollection,'deptId'=>$this->deptId,'startDate'=>$this->startDate,'endDate'=>$this->endDate,'period'=>$this->period,'year'=>$this->year,'clientInfo'=>$this->clientInfo,'instTiltakCountCollection'=>$this->instTiltakCountCollection,'govTiltakCountCollection'=>$this->govTiltakCountCollection,'observationCollection'=>$this->observationCollection,'observations'=>$this->observations,'observationAllData'=>$this->observationAllData));?>
	</div>
</div>