<div class="tablebg">
  <div style="display: block; padding:0 10px" id="tab1">
	<?php //$clientInfoArray = $this->clientInfo;echo $this->partial('info/tabs/clientInfo.phtml',array('clientInfo'=>$clientInfoArray));?>
  </div>
  <div style="display: block; padding: 0px 10px;" id="tab2">
	<?php //echo $this->partial('info/tabs/clientReports.phtml');?>
  </div>
  <div style="display: block; padding:0 10px" id="tab3">
    <?php //echo $this->partial('info/tabs/clientScoreCard.phtml');?>
  </div>
  <div style="display: block; padding:0 10px" id="tab4">
    <?php //echo $this->partial('info/tabs/clientMapping.phtml');?>
  </div>
  <div style="display: block; padding:0 10px" id="tab5">
    <?php echo $this->partial('statistikk/tabs/clientStatistic.phtml',array('startDate'=>$this->startDate,'endDate'=>$this->endDate,'period'=>$this->period,'year'=>$this->year,'clientInfo'=>$this->clientInfo,'instTiltakCountCollection'=>$this->instTiltakCountCollection,'govTiltakCountCollection'=>$this->govTiltakCountCollection,'observationCollection'=>$this->observationCollection,'observations'=>$this->observations,'observationAllData'=>$this->observationAllData,'maalCountCollection'=>$this->maalCountCollection,'monthReports'=>$this->monthReports, 'totalItems' => $this->totalItems));?>
  </div>
  <div style="display: block; padding:0 10px" id="tab6">
    <?php //echo $this->partial('info/tabs/clientMTO.phtml');?>
  </div>
  <div style="display: block; padding:0 10px" id="tab7">
    <?php //echo $this->partial('info/tabs/clientHMS.phtml');?>
  </div>
</div>