<?php $format=KD::getModel('core/format');//echo KD::getHelper('client/mto')->getObserRel('M',31);//->getHelper('Data')//->getObserRel();?>
<div>
<form name="frmClientAddObservation" id="frmClientAddObservation" method="post" action="<?php echo $this->getUrl("client/mto/addobservation");?>">
<div class="PSUBTCWRAPPER">
	<div class="PSUBTCLEFT">
    	<?php echo $this->translate('Observations');?>
    </div>
</div>
<div class="CLEARBBORDER"></div>
<div class="KKI2C">
<table width="100%" border="0" cellspacing="4" cellpadding="0" id="clientObservationTbl">
      <thead>
	  <tr class="CURNONPOINTER">
        <th class="TSLRTDNUMBER">
        <span class="tdbg2">
        	<input type="checkbox" name="checkbox_all" id="checkbox_all" class="css-checkbox" data-form="frmClientAddObservation"/>
            <label for="checkbox_all" class="css-label"></label>
        </span>
		<input type="hidden" name="patient_id" id="patient_id" value="<?php echo $this->clientID;?>"/>
        </th>
		<th class="TSLRTDCENTER" width="15%"><?php echo $this->translate('Observations Type');?></th>
		<th class="TSLRTDCENTER" width="15%"><?php echo $this->translate('Dependent');?></th>
		<th class="TSLRTDCENTER" width="65%"><?php echo $this->translate('Observations');?></th>
		<th class="TSLRTDCENTER" width="5%"><?php echo $this->translate('Action'); ?></th>
      </tr>
	  </thead>
	  <?php  if(count($this->observationCollection)>0):?>
	  <tbody id="sortableObservation">
	  <?php foreach($this->observationCollection as $observation):  ?>
		<?php $id = $observation['observation_id'];
			  $obType = $observation['observation_type']; 
			  if(isset($obType) && $obType=='M'):$obRel = $observation['relation1'];elseif(isset($obType) && $obType=='T'):$obRel = $observation['relation2'];else:$obRel = '';endif;
		?>
		  <tr id="observation-<?php echo $id;?>">
			<td class="TSLRTDNUMBER bgwhite">
				<span class="tdbg" style="width: 20px;">
				<input type="checkbox" name="<?php echo 'checkbox_'.$id;?>" id="<?php echo 'checkbox_'.$id;?>" class="css-checkbox"/>
				<label for="<?php echo 'checkbox_'.$id;?>" class="css-label"></label>
				</span>
			</td>
			<td><span class="tdbg cursormove"><?php echo $obType; ?></span></td>
			<td><span class="tdbg cursormove"><?php echo $obRel; ?></span></td>
			<td><span class="tdbg cursormove"><?php echo $observation['observation_desc']; ?></span></td>
			<td><span class="tdbg dialog-ajax1" data-url="<?php echo $this->getUrl('client/mto/editobservation/po/'.$this->page.'/id/'.$id);?>" data-title="<?php echo $observation['observation_desc']; ?>"><?php echo $this->translate('Edit'); ?></span></td>
		  </tr>
		<?php endforeach;?>
	  </tbody>
	  <?php 
		//echo $this->paginationControl($this->observationCollection, 'Sliding', 'control.phtml', array('page'=>'po','tt'=>'61','t'=>'6'));
	  endif;?>
</table>
</div>

<div class="mtodroplist1">
<div class="mtodroplist11">
    <span class="KITINRDLISTWSPAN">
    	<select name="selAction" class="onSelectAction" data-form="frmClientAddObservation">
        	<option value="" style=" font-weight:bold;"><?php echo $this->translate('Select %s %s',$this->translate('Type of Action'),$this->translate('Here!'));?></option>
            <option value="<?php echo $this->getUrl('client/mto/archiveobservation');?>"><?php echo $this->translate('%s %s',$this->translate('Archive'),$this->translate('Observations'));?></option>
        </select> 
    </span>  	
</div>
</div>
<div class="mtodroplist2">
	<div class="CANCELB"><a class="leggtilrada" id="clientAddObservation" data-val="0"><?php echo $this->translate('Add %s(s)',$this->translate('Row'));?></a></div>
	<div class="OPPRETTB"><input type="submit" class="OPPRETTBA" value="<?php echo $this->translate('Create');?>"/></div>
</div>

<script language="javascript" type="text/javascript">
$("#clientAddObservation").unbind("click").click(function () { 

	var id = $(this).data('val');
    $("#clientObservationTbl").each(function () {
       
        var tds = "";
		tds += '<tr><td colspan="2" class="width20"><span class="tdbg97"><select class="get-ajax1" name="types['+id+']" id="types['+id+']" data-target="dataList'+id+'" style="width: 99% !important;" data-validation="required"><option value="I"><?php echo $this->translate('Independant');?></option><option value="M"><?php echo $this->translate('Goal');?></option><option value="T"><?php echo $this->translate('Government Measure');?></option></select></span></td><td class="nonecls width20"><span class="tdbg tdbg97" id="dataList'+id+'"><input type="text" readonly="" class="disable width90" name="relations[]"/></span></td><td class="nonecls width60"><span class="tdbg"><input type="text" name="observationDescs[]" id="observationDescs[]" data-validation="required" /></span></td></tr>';

        if ($('tbody', this).length > 0) {
            $('tbody', this).append(tds);
        } else {
            $(this).append(tds);
        }
	});
	$(this).data('val',id+1);	
	$('.get-ajax1').change(function(e) {
		var target_id = $(this).data('target');
		if (target_id == "") {alert('Target Id Not Set');return false;}
		var target_action = '<?php echo $this->getUrl('client/mto/gettype/id/'.$this->clientID.'/key/');?>';
		var initial_target_html = 'Data Not Fetched';
		var load_target_html = 'Loading';
		$('#'+target_id).html(initial_target_html); //Give the target select the prompt option
		//Grab the chosen value on first select list change
		var selectvalue = $(this).val();
		//Display 'loading' status in the target select list
		$('#'+target_id).html(load_target_html);	
		if (selectvalue == "") {
			//Display initial prompt in target select if blank value selected
		   $('#'+target_id).html(initial_target_html);
		} else {
		  //Make AJAX request, using the selected value as the GET
		  $.ajax({url: target_action+selectvalue,
				 success: function(output) {
					$('#'+target_id).html(output);
				},
			  error: function (xhr, ajaxOptions, thrownError) {
				alert(xhr.status + " "+ thrownError);
			  }});
			}
	});
});

$.validate({
	form : '#frmClientAddObservation', 
	validateOnBlur : false,
	borderColorOnError : '#C90312',
	addValidClassOnAll : true,
	showHelpOnFocus : false,
	addSuggestions : false,
	errorMessagePosition : 'top',
	scrollToTopOnError : true
});
// Code For Get Dialog on click of class dialog-ajax
$(document).ready(function(){

	$( "#sortableObservation" ).sortable({
	  axis: 'y',
	  placeholder: "ui-state-highlight",
		update: function (event, ui) {
			var data = $(this).sortable('serialize');
			// POST to server using $.post or $.ajax
			$.ajax({
				data: data,
				type: 'POST',
				url: '<?php echo $this->getUrl('client/mto/updateobserorder');?>',
				beforeSend: function(){$("#loading-image").show();},
				success: function(output) {
					//alert(output);
					$('#sortableObservation').html(output);
					$("#loading-image").hide();
				},
				error: function (xhr, ajaxOptions, thrownError) {
					$("#loading-image").hide();
					alert('Problem while Change Order');
				}
			});
		}
	});
	
		
	$('.dialog-ajax1').unbind("click").click(function(){   
		var tag = $("<div></div>"); //This tag will the hold the dialog content.
		var url = $(this).data('url');
		var title = $(this).data('title');
		$.ajax({
		  url: $(this).data('url'),
		  type: 'GET',
		  //beforeSend: options.beforeSend,
		  beforeSend: function() {$("#loading-image").show();},
		  error: function() { alert('Could not load form') },
		  success: function(data, textStatus, jqXHR) {
			if(typeof data == "object" && data.html) { //response is assumed to be JSON
			  tag.html(data.html).dialog({modal:true, title: title}).dialog('open');
			} else { //response is assumed to be HTML
			  tag.html(data).dialog({modal: true, title: title, height: 200, width:800, hide: "scale", show : "scale",
					open: function (event, ui) {
						var startDate = $(".DyndatepickerImage1");
						startDate.unbind();
						startDate.datepicker(Mtg.Config.Datepicker);
						$.validate({
							form : '#frmClientEditObservation', 
							validateOnBlur : false,
							borderColorOnError : '#C90312',
							addValidClassOnAll : true,
							showHelpOnFocus : false,
							addSuggestions : false,
							errorMessagePosition : 'top',
							scrollToTopOnError : true
						});
						$("#loading-image").hide();
						/*$('.get-ajax2').change(function(e) {
							var target_id = $('#dataList');
							var target_action = '<?php echo $this->getUrl('client/mto/gettype/edit/1/id/'.$this->clientID.'/key/');?>';
							var initial_target_html = 'Data Not Fetched';
							var load_target_html = 'Loading';
							$('#'+target_id).html(initial_target_html); //Give the target select the prompt option
							//Grab the chosen value on first select list change
							var selectvalue = $(this).val();
							//Display 'loading' status in the target select list
							$('#'+target_id).html(load_target_html);	
							if (selectvalue == "") {
								//Display initial prompt in target select if blank value selected
							   $('#'+target_id).html(initial_target_html);
							} else {
							  //Make AJAX request, using the selected value as the GET
							  $.ajax({url: target_action+selectvalue,
									 success: function(output) {
										$('#'+target_id).html(output);
									},
								  error: function (xhr, ajaxOptions, thrownError) {
									alert(xhr.status + " "+ thrownError);
								  }});
								}
						});*/
					},
					close: function (event, ui) {
						$('input.DyndatepickerImage1').datepicker("destroy");
						$(this).dialog("destroy");
						$(this).remove();
					}
				}).dialog('open');
				
			}
		  }
		});
	  });
});
</script>
<?php if($this->isAjax):?>   
<script src="<?php echo $this->getMediaUrl('ajax-load-custom.js','js');?>" language="javascript" type="text/javascript"></script>
<?php endif;?>
</form>
</div>