<?php $AssoArray = array('NOTCOMPLETE'=>$this->translate('Not Complete'),'PARTIALCOMPLETE'=>$this->translate('Partial Complete'),'COMPLETE'=>$this->translate('Completed'),'NOTEVALUATED'=>$this->translate('Non Evaluated'));?>
<div class="PSUBTCWRAPPER">
	<div class="PSUBTCLEFT">
    <?php echo $this->translate('Quarterly Summary');?>
    </div>
</div>
<div class="CLEARBBORDER"></div>
<?php  
	$dateJoin = new DateTime($this->clientInfo['patient_date_of_joining']);
	$startYear = $dateJoin->format('Y');
	$tilDate = new DateTime();
	$endYear = $tilDate->format('Y');
?>
<form name="frmSearchMonthVaktrapport" id="frmSearchMonthVaktrapport" method="post" action="<?php echo $this->getUrl("vaktrapport/month/searchk/id/".$this->clientInfo['patient_id']);?>">
<input type="hidden" name="clientId" value="<?php echo $this->clientInfo['patient_id'];?>" />
<input type="hidden" name="reportType" value="kvartal" />
<div class="PSUBTCWRAPPER">
	<div class="VVGBG VV2IN1C2 floatleft">
	  <div class="width20 floatleft" style="line-height: 40px;">
		<div class="floatleft"><?php echo $this->translate('Year');?></div>
		<span class="tdbg888p floatleft marginleft20 width60" style="margin-top:5px;">
			<select name="year" id="year">
			<?php for($i=$startYear;$i<=$endYear;$i++)
			{
			?>
				<option value="<?php echo $i;?>" <?php echo (isset($this->vaktrapInfo['vaktrap_year']) && $this->vaktrapInfo['vaktrap_year']==$i)?'selected="selected"':'';?>><?php echo $i;?></option>
			<?php 
			}?>
			</select>
		</span>
	  </div>
	  <div class="width20 floatleft marginleft20" style="line-height: 40px;">
		<div class="floatleft"><?php echo $this->translate('Period');?></div>
		<span class="tdbg888p floatleft width50 marginleft20" style="margin-top:5px;">
			<select name="period" id="period">
			<?php for($i=1;$i<=4;$i++)
			{
			?>
				<option value="<?php echo $i;?>" <?php echo (isset($this->vaktrapInfo['vaktrap_period']) && $this->vaktrapInfo['vaktrap_period']==$i)?'selected="selected"':'';?>><?php echo $this->translate('Quarter').' '.$i;?></option>
			<?php 
			}?>
			</select>
		</span>
	  </div>
	  <div class="width20 floatleft" style="margin:0px">
		<div class="KKI1C1"><div class="OPPRETTB floatleft marginleft20" style="margin-top:0px"><input type="submit" name="show_report" id="show_report" class="OPPRETTBA" value="<?php echo $this->translate('Show');?>"></div></div>
	  </div>
	</div>
</div>
</form>

<script src="<?php echo $this->getMediaUrl('jsapi.js','js');?>" type="text/javascript"></script>
<script>
        
      // Load the Visualization API and the piechart package.
      google.load('visualization', '1.0', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
        
	function drawChart() {

			var pieResultCodes = ['<?php echo $this->translate('Not Complete');?>','<?php echo $this->translate('Partial Complete');?>', '<?php echo $this->translate('Completed');?>','<?php echo $this->translate('Non Evaluated');?>'];
			// Create Pie Chart For Institutional Tiltak.
			var dataInst = new google.visualization.DataTable();
			dataInst.addColumn('string', 'Resultat');
			dataInst.addColumn('number', 'Antall');
			dataInst.addRows([
				<?php
				$colorsOption = '[';
				if (isset($this->instTiltakCountCollection)) {
					foreach($this->instTiltakCountCollection as $title => $resultArray) {
						$count = $resultArray['count'];
						echo "['$AssoArray[$title]', $count],\n";
						$colorsOption .= "'" . $resultArray['color'] . "',";
					}
				}
				else $title = '';
				$colorsOption .= "]";
				?>
			]);
			// Set chart options
			var options = {'title':'<?php echo $this->translate('Institute Tiltak');?>',
							'legend': 'right',
						   'width':350,
						   'height':200,
						   'pieSliceTextStyle': {color: 'black', fontName: 'Ubuntu', fontSize: 12},
						   'colors': <?php echo $colorsOption; ?>,
						   'titleTextStyle': {color: 'black', fontName: 'Ubuntu', fontSize: 16},
						   is3D: true
						   };
	
			// Instantiate and draw our chart, passing in some options.
			var chartInst = new google.visualization.PieChart(document.getElementById('chartInstPie_div'));
	
			// Add a listener to the pie's select event - when someone clicks on a pice slice
			// The handler is implemented below, and the dialog is Initialized at page bottom
			google.visualization.events.addListener(chartInst, 'select', selectHandlerInstChart);
			
			// The select handler for pie chart. Define a new one for each chart
			function selectHandlerInstChart() {
				var pieChartInstDetails = new Array(3);
				<?php
					
				if (isset($this->instTiltakCountCollection)) {
					foreach($this->instTiltakCountCollection as $title => $resultArray) {
						$result = $resultArray['result'];
						echo "pieChartInstDetails[$result] = new Array(" . count($resultArray['data']) .");";
						$cnt = 0;
						foreach($resultArray['data'] as $resultDesc) {
							echo "pieChartInstDetails[$result][$cnt] = '".$resultDesc['tilins_desc']."';";
							$cnt++;
						}
					}
				}
				?>
				// The chart and data objects are globa
				var selectedItem = chartInst.getSelection()[0];
				if (selectedItem) {
					var title = dataInst.getValue(selectedItem.row, 0);
					var percent = dataInst.getValue(selectedItem.row, 1);
					
					var tag = $('<div></div>'); //This tag will the hold the dialog content.
					var titleDialog = title+' : '+percent+' <?php echo $this->translate('Institute Tiltak');?>';
					var resultCode = pieResultCodes.indexOf(title);
					// First remove any previously added rows
					$('.chartData').remove();
					// Now build a list of Tiltak and add them to the dialogs table
					var html = '<table border="0" width="100%" cellpadding="0" cellspacing="4" class="KRV">';
					// Get the names of the Tiltak that is part of this result
					for (var i = 0; i < pieChartInstDetails[resultCode].length; i++) {
						html += '<tr class="chartData"><td class="padding5">'+(i+1)+'</td><td class="padding5">' + pieChartInstDetails[resultCode][i] + '</td></tr>';
					}
					html += '</table>';
					tag.append(html);
					
					tag.dialog({modal:true, title: titleDialog, width:'500px'}).dialog('open');
				}
			}
			
			// Done. Draw the Instituional Pie chart
			chartInst.draw(dataInst, options);
			
			// Create Pie Chart For Government Tiltak.
			var dataGov = new google.visualization.DataTable();
			dataGov.addColumn('string', 'Resultat');
			dataGov.addColumn('number', 'Antall');
			dataGov.addRows([
				<?php
				$colorsOption = '[';
				if (isset($this->govTiltakCountCollection)) {
					foreach($this->govTiltakCountCollection as $title => $resultArray) {
						$count = $resultArray['count'];
						echo "['$AssoArray[$title]', $count],\n";
						$colorsOption .= "'" . $resultArray['color'] . "',";
					}
				}
				else $title = '';
				$colorsOption .= "]";
				?>
			]);
			// Set chart options
			var options = {'title':'<?php echo $this->translate('Government Tiltak');?>',
							'legend': 'right',
						   'width':350,
						   'height':200,
						   'pieSliceTextStyle': {color: 'black', fontName: 'Ubuntu', fontSize: 12},
						   'colors': <?php echo $colorsOption; ?>,
						   'titleTextStyle': {color: 'black', fontName: 'Ubuntu', fontSize: 16},
						   is3D: true
						   };
	
			// Government and draw our chart, passing in some options.
			var chartGov = new google.visualization.PieChart(document.getElementById('chartGovPie_div'));
	
			// Add a listener to the pie's select event - when someone clicks on a pice slice
			// The handler is implemented below, and the dialog is Initialized at page bottom
			google.visualization.events.addListener(chartGov, 'select', selectHandlerGovChart);
			
			// The select handler for pie chart. Define a new one for each chart
			function selectHandlerGovChart() {
				var pieChartGovDetails = new Array(3);
				<?php
					
				if (isset($this->govTiltakCountCollection)) {
					foreach($this->govTiltakCountCollection as $title => $resultArray) {
						$result = $resultArray['result'];
						echo "pieChartGovDetails[$result] = new Array(" . count($resultArray['data']) .");";
						$cnt = 0;
						foreach($resultArray['data'] as $resultDesc) {
							echo "pieChartGovDetails[$result][$cnt] = '".$resultDesc['vaktrap_tilgov_desc']."';";
							$cnt++;
						}
					}
				}
				?>
				// The chart and data objects are globa
				var selectedItem = chartGov.getSelection()[0];
				if (selectedItem) {
					var title = dataGov.getValue(selectedItem.row, 0);
					var percent = dataGov.getValue(selectedItem.row, 1);
					
					var tag = $('<div></div>'); //This tag will the hold the dialog content.
					var titleDialog = title+' : '+percent+' <?php echo $this->translate('Government Tiltak');?>';
					var resultCode = pieResultCodes.indexOf(title);
					// First remove any previously added rows
					$('.chartData').remove();
					// Now build a list of Tiltak and add them to the dialogs table
					var html = '<table border="0" width="100%" cellpadding="0" cellspacing="4" class="KRV">';
					// Get the names of the Tiltak that is part of this result
					for (var i = 0; i < pieChartGovDetails[resultCode].length; i++) {
						html += '<tr class="chartData"><td class="padding5">'+(i+1)+'</td><td class="padding5">' + pieChartGovDetails[resultCode][i] + '</td></tr>';
					}
					html += '</table>';
					tag.append(html);
					
					tag.dialog({modal:true, title: titleDialog, width:'500px'}).dialog('open');
				}
			}
			
			// Done. Draw the chart
			chartGov.draw(dataGov, options);
	}
</script>
<?php if(!empty($this->vaktrapInfo)):?>
<?php $format = KD::getModel('core/format');
	$vaktrapFromDate = $this->vaktrapInfo['vaktrap_from_date'];
	$vaktrapToDate = $this->vaktrapInfo['vaktrap_to_date'];
	if(!empty($this->vaktrapInfo['vaktrap_counters']))
	{
		$vaktrapCounters = $this->vaktrapInfo['vaktrap_counters'];
	}
	else
	{
		$vaktrapCounters = array('gov'=>0,'ins'=>0,'force'=>0,'medicine'=>0,'logg'=>0,'avvik'=>0);
	}
?>
<?php $minVak = new DateTime($vaktrapFromDate);?>
<?php $maxVak = new DateTime($vaktrapFromDate);$maxVak = $maxVak->add(new DateInterval('P6D'));?>
<form name="frmEditClientVaktrapport" id="frmEditClientVaktrapport" method="post" action="<?php echo $this->getUrl("vaktrapport/month/save/type/kvartal/id/".$this->vaktrapInfo['vaktrap_patientID']);?>">
<div id="section1">
<?php if($this->vaktrapInfo['vaktrap_status']=='yes'):?>
<input type="hidden" name="vaktrap_deptID" value="<?php echo $this->vaktrapInfo['vaktrap_deptID'];?>" />
<input type="hidden" name="vaktrap_patientID" value="<?php echo $this->vaktrapInfo['vaktrap_patientID'];?>" />
<input type="hidden" name="year" value="<?php echo $this->vaktrapInfo['vaktrap_year'];?>" />
<input type="hidden" name="period" value="<?php echo $this->vaktrapInfo['vaktrap_period'];?>" />
<input type="hidden" name="reportType" value="kvartal" />
<?php endif;?>
<div class="VVGBG VV2IN1C2 floatleft">
<table width="100%" border="0">
  <tr>
    <th class="th12p"><?php echo $this->translate('Security Report Period From');?></th>
    <th class="th12p"><?php echo $this->translate('Security Report Period To');?></th>
    <th class="th25p"><?php echo $this->translate('Current Client');?></th>
    <th class="th25p"><?php echo $this->translate('Legal Placement');?></th>
    <th class="th25p"><?php echo $this->translate('User');?></th>
  </tr>
  <tr>
    <td width="15%"><span class="tdbg"><?php echo $format->FormatDate($vaktrapFromDate); ?></span></td>
    <td width="15%"><span class="tdbg"><?php echo $format->FormatDate($vaktrapToDate);?></span></td>
    <td width="25%"><a href="<?php echo $this->getUrl('client/info/index/id/'.$this->vaktrapInfo['vaktrap_patientID']);?>"><span class="tdbg"><?php echo $this->vaktrapInfo['patient_name'];?></span></a></td>
    <td width="20%"><span class="tdbg"><?php echo $this->vaktrapInfo['patient_legal'];?></span></td>
    <td width="20%"><a href="<?php echo $this->getUrl('user/info/index/id/'.$this->vaktrapInfo['vaktrap_userID']);?>"><span class="tdbg"><?php echo $this->vaktrapInfo['user_name'];?></span></td>
  </tr>
</table>
</div>

<div class="CLEARBBORDER2"></div>
<div class="VVGBG VV2IN1C2">
<table width="100%" border="0">
  <tr>
    <th class="th2p">A )</th>
    <th class="th2p"></th>
    <th class="th95p"><?php echo $this->translate('Measure from scorecard plan');?></th>
  </tr>
  <?php 
  foreach($this->maalCollection as $maal):
  ?>
  <tr>
    <td class="bgwhite"><span class="tdbg71p"><?php echo $maal['counter'];?></span></td>
    <td class="bgwhite"><span class="tdbgtextacenter">+</span></td>
    <td><span class="tdbg"><?php echo $maal['maal_desc'];?></span></td>
  </tr>
  <?php endforeach;?>
</table>
</div>
<div class="CLEARBBORDER2"></div>
<div class="VVGBG VV2IN1C2">
<table width="100%" border="0">
  <tr>
    <th class="th2p">B )</th>
    <th class="th66p"><?php echo $this->translate('Ongoing Measure');?>( <?php echo $this->translate('measures over time');?> )</th>
    <th class="th10p"><?php echo $this->translate('Completed');?></th>
    <th class="th10p"><?php echo $this->translate('Partial Complete');?></th>
    <th class="th10p"><?php echo $this->translate('Not Complete');?></th>
  </tr>
  <?php $explainGovs = array();
  		foreach($this->vakGovTiltakCollection as $maalId=>$vakGovTiltaks):?>
	  <?php if(count($this->vakGovTiltakCollection[$maalId])>0):?>
	  <tr><td class="head-content"><?php echo $this->maalCollection[$maalId]['counter'];?></td><td colspan="4" class="head-content"><?php echo $this->maalCollection[$maalId]['maal_desc'];?></td></tr>
		<?php foreach($vakGovTiltaks as $cnt=>$vakGovTiltak):
			$explainGovs[] = array('id' => $vakGovTiltak['vaktrap_tilgov_id'], 'explanation' => $vakGovTiltak['vaktrap_tilgov_explanation'], 'result' => $vakGovTiltak['vaktrap_tilgov_result'], 'no' => $this->maalCollection[$maalId]['counter'].'.'.($cnt+1));?>
		  <tr>
			<td class="bgwhite"><span class="tdbg71p"><?php echo $this->maalCollection[$maalId]['counter'].'.'.($cnt+1);?></span></td>
			<td><span class="tdbg"><?php echo $vakGovTiltak['vaktrap_tilgov_desc'];?><?php echo $vakGovTiltak['vaktrap_tilgov_result'];?></span></td>
			<td><span class="tdbg VVTAC"><div><input type="radio" id="vakGovTiltak2[<?php echo $vakGovTiltak['vaktrap_tilgov_id'];?>]" disabled="disabled" name="vakGovTiltakRes[<?php echo $vakGovTiltak['vaktrap_tilgov_id'];?>]" <?php echo ($vakGovTiltak['vaktrap_tilgov_result']=='2')?'checked="checked"':'';?> value="2"  data-explaination="govExplainID<?php echo $vakGovTiltak['vaktrap_tilgov_id'];?>" /><label for="vakGovTiltak2[<?php echo $vakGovTiltak['vaktrap_tilgov_id'];?>]"><span></span></label></div></span></td>
			<td><span class="tdbg VVTAC"><div><input type="radio" id="vakGovTiltak1[<?php echo $vakGovTiltak['vaktrap_tilgov_id'];?>]" disabled="disabled" name="vakGovTiltakRes[<?php echo $vakGovTiltak['vaktrap_tilgov_id'];?>]" <?php echo ($vakGovTiltak['vaktrap_tilgov_result']=='1')?'checked="checked"':'';?> value="1" data-explaination="govExplainID<?php echo $vakGovTiltak['vaktrap_tilgov_id'];?>" /><label for="vakGovTiltak1[<?php echo $vakGovTiltak['vaktrap_tilgov_id'];?>]"><span></span></label></div></span></td>
			<td><span class="tdbg VVTAC"><div><input type="radio" id="vakGovTiltak0[<?php echo $vakGovTiltak['vaktrap_tilgov_id'];?>]" disabled="disabled" name="vakGovTiltakRes[<?php echo $vakGovTiltak['vaktrap_tilgov_id'];?>]" <?php echo ($vakGovTiltak['vaktrap_tilgov_result']=='0')?'checked="checked"':'';?> value="0" data-explaination="govExplainID<?php echo $vakGovTiltak['vaktrap_tilgov_id'];?>" /><label for="vakGovTiltak0[<?php echo $vakGovTiltak['vaktrap_tilgov_id'];?>]"><span></span></label></div></span></td>
		  </tr>
		<?php endforeach;?>
  	<?php endif;?>
  <?php endforeach;?>
</table>
<div class="CLEARBBORDER2"></div>
<div class="margintop">
<table width="100%" border="0">
  <tr>
    <th class="th3p">B.1 )</th>
    <th class="th97p"><?php echo $this->translate('Reason why the measures are only partially or not implemented');?></th>
  </tr>
    <?php
	foreach ($explainGovs as $explainGov):
		if ($explainGov['result']==2 || is_null($explainGov['result'])) {$show_hide = 'style="display:none"';}
		else {$show_hide = '';}
	?>
	<tr id="govExplainID<?php echo $explainGov['id'];?>" <?php echo $show_hide;?>>
		<td class="bgwhite"><span class="tdbg71p"><?php echo $explainGov['no'];?></span></td>
		<td class="nonecls"><span class="tdbg1c"><?php echo isset($explainGov['explanation'])?$explainGov['explanation']:'';?></span></td>
    </tr>
	<?php 
	endforeach;
	?> 
</table>
</div>
</div>
<div class="CLEARBBORDER2"></div>
<div class="VVGBG VV2IN1C2">
<table width="100%" border="0">
  <tr>
    <th class="th2p">C )</th>
	<th class="th66p"><?php echo $this->translate('Short Measure');?></th>
    <th class="th10p"><?php echo $this->translate('Completed');?></th>
    <th class="th10p"><?php echo $this->translate('Partial Complete');?></th>
    <th class="th10p"><?php echo $this->translate('Not Complete');?></th>
  </tr>
  <?php 
  	$explainInsts = array();
  	foreach($this->instTiltakCollection as $maalId=>$instTiltaks):?>
	  <?php if(count($this->instTiltakCollection[$maalId])>0):?>
	  <tr><td class="head-content"><?php echo $this->maalCollection[$maalId]['counter'];?></td><td colspan="4" class="head-content"><?php echo $this->maalCollection[$maalId]['maal_desc'];?></td></tr>
		<?php foreach($instTiltaks as $cnt=>$instTiltak):
			$explainInsts[] = array('id' => $instTiltak['tilins_id'], 'explanation' => $instTiltak['tilins_explanation'], 'result' => $instTiltak['tilins_result'], 'no' => $this->maalCollection[$maalId]['counter'].'.'.($cnt+1));?>
		  <tr>
			<td class="bgwhite"><span class="tdbg71p"><?php echo $this->maalCollection[$maalId]['counter'].'.'.($cnt+1);?></span></td>
			<td><span class="tdbg"><?php echo $instTiltak['tilins_desc'];?></span></td>
			<td><span class="tdbg VVTAC"><div><input type="radio" id="vakInsTiltak2[<?php echo $instTiltak['tilins_id'];?>]" disabled="disabled" name="vakInsTiltakRes[<?php echo $instTiltak['tilins_id'];?>]" data-explaination="instExplainID<?php echo $instTiltak['tilins_id'];?>" <?php echo ($instTiltak['tilins_result']=='2')?'checked="checked"':'';?>  value="2"  /><label for="vakInsTiltak2[<?php echo $instTiltak['tilins_id'];?>]"><span></span></label></div></span></td>
			<td><span class="tdbg VVTAC"><div><input type="radio" id="vakInsTiltak1[<?php echo $instTiltak['tilins_id'];?>]" disabled="disabled" name="vakInsTiltakRes[<?php echo $instTiltak['tilins_id'];?>]" data-explaination="instExplainID<?php echo $instTiltak['tilins_id'];?>" <?php echo ($instTiltak['tilins_result']=='1')?'checked="checked"':'';?>  value="1" class="showexplanation validation" /><label for="vakInsTiltak1[<?php echo $instTiltak['tilins_id'];?>]"><span></span></label></div></span></td>
			<td><span class="tdbg VVTAC"><div><input type="radio" id="vakInsTiltak0[<?php echo $instTiltak['tilins_id'];?>]" disabled="disabled" name="vakInsTiltakRes[<?php echo $instTiltak['tilins_id'];?>]" data-explaination="instExplainID<?php echo $instTiltak['tilins_id'];?>" <?php echo ($instTiltak['tilins_result']=='0')?'checked="checked"':'';?>  value="0" class="showexplanation validation" /><label for="vakInsTiltak0[<?php echo $instTiltak['tilins_id'];?>]"><span></span></label></div></span></td>
		  </tr>
		<?php endforeach;?>
  	<?php endif;?>
  <?php endforeach;?>
</table>
<div class="CLEARBBORDER2"></div>
<div class="margintop">
<table width="100%" border="0">
  <tr>
    <th class="th3p">C.1 )</th>
    <th class="th97p"><?php echo $this->translate('Reason why the measures are only partially or not implemented');?></th>
  </tr>
   <?php
	foreach ($explainInsts as $explainInst):
		if ($explainInst['result']==2 || is_null($explainInst['result'])) {$show_hide = 'style="display:none"';}
		else {$show_hide = '';}
	?>
	<tr id="instExplainID<?php echo $explainInst['id'];?>" <?php echo $show_hide;?>>
		<td class="bgwhite"><span class="tdbg71p"><?php echo $explainInst['no'];?></span></td>
		<td class="nonecls"><span class="tdbg1c"><?php echo isset($explainInst['explanation'])?$explainInst['explanation']:'';?></span></td>
    </tr>
	<?php 
	endforeach;
	?> 
</table>
</div>
</div>
<div class="CLEARBBORDER2"></div>

<?php /*?>Maal Pie Chart<?php */?>
<div class="statistikkcon2">
    <div class="statistikkcon2_1">
        <div id="chartGovPie_div"></div>
        <div class="statistikkcon2_12 floatleft">
        	<table width="100%" border="0">
			  <tr>
				<th width="20%"><?php echo $this->translate('Ongoing Measure');?></th>
				<th width="20%"><?php echo $this->translate('Not Complete');?></th>
				<th width="20%"><?php echo $this->translate('Partial Complete');?></th>
				<th width="20%"><?php echo $this->translate('Completed');?></th>
				<th width="20%"><?php echo $this->translate('Non Evaluated');?></th>
			  </tr>
			  <tr>
				<td></td>
			  <?php
				if (isset($this->govTiltakCountCollection)) {
					foreach($this->govTiltakCountCollection as $title => $resultArray) {
						echo '<td><span class="tdbg">'.$count = $resultArray['count'].'</span></td>';
					}
				}
			  ?>
			  </tr>
			</table>
        </div>
    </div>
    <div class="statistikkcon2_2">
        <div id="chartInstPie_div"></div>
        <div class="statistikkcon2_12 floatleft">
        	<table width="100%" border="0">
			  <tr>
				<th width="20%"><?php echo $this->translate('Short Measure');?></th>
				<th width="20%"><?php echo $this->translate('Not Complete');?></th>
				<th width="20%"><?php echo $this->translate('Partial Complete');?></th>
				<th width="20%"><?php echo $this->translate('Completed');?></th>
				<th width="20%"><?php echo $this->translate('Non Evaluated');?></th>
			  </tr>
			  <tr>
				<td></td>
			  <?php
				if (isset($this->instTiltakCountCollection)) {
					foreach($this->instTiltakCountCollection as $title => $resultArray) {
						echo '<td><span class="tdbg">'.$count = $resultArray['count'].'</span></td>';
					}
				}
			  ?>
			  </tr>
			</table>
        </div>
    </div>  
</div>
<div class="CLEARBBORDER2"></div>

<div class="VVGBG VV2IN1C2">
<table width="100%" border="0">
  <tr>
	<?php
	$vaktrapFromDate = $this->vaktrapInfo['vaktrap_from_date'];
	$vaktrapToDate = $this->vaktrapInfo['vaktrap_to_date'];
	$begin = new DateTime($vaktrapFromDate);
	$endcheck = new DateTime($vaktrapToDate);
	$hideObservation = false;
	$difference = $endcheck->diff($begin)->format("%a");
	if(isset($vaktrapToDate) && $vaktrapToDate!='' && (strpos($vaktrapToDate,'0000')===false) && $difference<=7)
	{
		$end = new DateTime($vaktrapToDate);
	}
	else
	{
		$end = clone $begin;
		$end->add(new DateInterval('P6D'));
		$hideObservation = true;
	}
	$end = $end->modify( '+1 day' );
	$interval = new DateInterval('P1D');
	$daterange = new DatePeriod($begin, $interval ,$end);
	?>
	<th class="th2p">D )</th>
    <th class="<?php echo (!$hideObservation)?'th76p':'th50p';?>">Tall på observasjoner, jf.mål (EKS, utagering, selvskading, manglende oppmøte skole)</th>
  </tr>
  <?php 
  $obserCnt =1;
  foreach($this->vaktrapInfo['vaktrap_observationdesc'] as $observationID => $observation):
  ?>
  <tr>
    <td class="bgwhite"><span class="tdbg71p"><?php echo  $obserCnt++;?></span></td>
    <td class="nonecls"><span class="tdbg"><?php echo $observation['observation_desc'];?><?php echo $observation['observation_desc'];?></span></td>
  </tr>
  <?php endforeach;?>
</table>
</div>
<div class="CLEARBBORDER2"></div>
	<div class="KKI2C">
        <table width="100%" border="0" cellspacing="4" cellpadding="0">
            <tr>
                <th class="noborder">E ) Beskriv kort fremgang i behandlingen</th>
            </tr>
            <tr>
                <td><span class="tdbg1c"><?php echo $this->vaktrapInfo['vaktrap_fremgang'];?></span></td>
            </tr>
		</table> 
    </div>
    <div class="CLEARBBORDER2"></div>
    <div class="KKI2C">
        <table width="100%" border="0" cellspacing="4" cellpadding="0">
            <tr>
                <th class="noborder">F ) Helt spesielle hendelser i perioden</th>
            </tr>
            <tr>
                <td><span class="tdbg1c"><?php echo $this->vaktrapInfo['vaktrap_hendelser'];?></span></td>
            </tr>
		</table> 
    </div>
    <div class="CLEARBBORDER2"></div>
    <div class="KKI2C">
		<table width="100%" border="0">
		  <tr>
			<th>G.1 )&nbsp;&nbsp;&nbsp;Årsaksforklaring</th>
		  </tr>
		  <tr>
			<td><span class="tdbg1c"><?php echo $this->vaktrapInfo['vaktrap_aarsak'];?></span></td>
		  </tr>
		</table>
    </div>

	<div class="CLEARBBORDER2"></div>
	<div class="KKI2C">
		<table width="100%" border="0">
		  <tr>
			<th>H) Merknader til rapporten</th>
		  </tr>
		  <tr>
			<td><?php echo $this->vaktrapInfo['vaktrap_merknader'];?></span></td>
		  </tr>
		</table>
	</div>

	<div class="CLEARBBORDER2"></div>
	<div class="KKI2C">
		<table width="100%" border="0">
		  <tr>
			<th>I) Oppsumering</th>
		  </tr>
		  <tr>
		    <?php if(!($this->vaktrapInfo['vaktrap_status']=='no')):?>
			<td class="nonecls"><span class="tdbg1c"><textarea onkeyup="textAreaAdjust(this)" name="vaktrap_oppsumering" id="vaktrap_oppsumering" style="overflow:hidden;width: 100%; border: none; height:auto;"><?php echo isset($this->vaktrapInfo['vaktrap_oppsumering'])?$this->vaktrapInfo['vaktrap_oppsumering']:'';?></textarea></span></td>
			<?php else:?>
			<td><span class="tdbg1c"><?php echo isset($this->vaktrapInfo['vaktrap_oppsumering'])?$this->vaktrapInfo['vaktrap_oppsumering']:'';?></span></td>
			<?php endif;?>
		  </tr>
		</table>
	</div>
	
<div class="CLEARBBORDER2"></div>
 <?php if(!($this->vaktrapInfo['vaktrap_status']=='no')):?>
<div class="CANCELB"><a class="CANCELBA" href="#"><?php echo $this->translate('Cancel');?></a></div>
<?php /*?><div class="LAGREB3"><a class="LAGREBA2" href="#"><?php echo $this->translate('Save');?></a></div><?php */?>
<div class="OPPRETTB floatleft marginleft20"><input type="submit" name="save_report" id="save_report" class="OPPRETTBA" value="<?php echo $this->translate('Save');?>"></div>
<div class="OPPRETTB floatleft marginleft20"><input type="submit" name="lock_report" id="lock_report" class="OPPRETTBA LAASARKIVERBA" value="<?php echo $this->translate('Lock Quarterly Security Report');?>"></div>

<?php /*?><script src="<?php echo $this->getMediaUrl('jquery.validate.min.js','js');?>"></script><?php */?>
<script language="javascript" type="text/javascript">
	$(document).ready(function(e){
			
			$("#save_report").unbind().click(function(){
			    $('.validation').each(function () {
					$(this).attr( "data-validation", '' );
					//$(this).data('validation','');
				}); 
				$('#vaktrap_merknader').attr( "data-validation", '' );
			});
			$("#lock_report").unbind().click(function(){

					$('.validation').each(function () {
						if($(this).is(':radio'))
						{
							$(this).attr( "data-validation", 'radio' );
							//$(this).data('validation','radio');
						}
						else
						{
							$(this).attr( "data-validation", 'required' );
							//$(this).data('validation','required');
						}
					}); 

			});
	 });
</script>
<?php endif;?>
</div>
</form>
<?php endif;?>
