<div class="PSUBTCWRAPPER">
	<div class="PSUBTCLEFT">
    	<?php echo $this->translate('%s %s',$this->translate('Completed'),$this->translate('Goal'));?>
    </div>
</div>
<div class="CLEARBBORDER"></div>
<div class="KKI2C">
<table width="100%" border="0" cellspacing="4" cellpadding="0">
      <tr class="CURNONPOINTER">
        <th class="TSLRTDCENTER"><?php echo $this->translate('Goal');?></th>
		<th class="TSLRTDCENTER"><?php echo $this->translate('%s Date',$this->translate('From'));?></th>
        <th class="TSLRTDCENTER"><?php echo $this->translate('%s Date',$this->translate('To'));?></th>		
      </tr>
      <tr>
        <td><span class="tdbg">Vedkommende utsetter seg ikke for alvorlige selvdestrukte handlinger</span></td>
        <td class="bgwhite"><span class="tdbg">01/09-2014</span></td>
        <td class="bgwhite"><span class="tdbg">14/12-2014</span></td>
      </tr>
      <tr>
        <td><span class="tdbg">Vedkommende mottar behandling for spiseforstyrrelsen ved Capio</span></td>
        <td class="bgwhite"><span class="tdbg">01/09-2014</span></td>
        <td class="bgwhite"><span class="tdbg">14/12-2014</span></td>
      </tr>
      <tr>
        <td><span class="tdbg">Vedkommende følger oppsatt skoleplan</span></td>
        <td><span class="tdbg">01/09-2014</span></td>
        <td><span class="tdbg">14/12-2014</span></td>
      </tr>
      <tr>
        <td><span class="tdbg">Opsatt ukeplan og ingåtte avtaler følges</span></td>
        <td><span class="tdbg">01/09-2014</span></td>
        <td><span class="tdbg">14/12-2014</span></td>
      </tr>
</table>
</div>